// === input.svelte ===
// generated by svelte-check-native; do not edit
type $$ComponentProps = { a: T, b: string };
async function $$render_6b1a6441<T>() {

    let { a, b }: { a: T, b: string } = $props();
    let x = $state<T>(0);
    let y = $derived(x * 2);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_6b1a6441;
declare class __svn_Render_6b1a6441<T> {
    props(): Awaited<ReturnType<typeof $$render_6b1a6441<T>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_6b1a6441<T>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_6b1a6441<T>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_6b1a6441<T>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_6b1a6441<T>>>['exports'];
}
interface $$IsomorphicComponent {
    new <T>(options: import('svelte').ComponentConstructorOptions<ReturnType<__svn_Render_6b1a6441<T>['props']>>): import('svelte').SvelteComponent<ReturnType<__svn_Render_6b1a6441<T>['props']>, ReturnType<__svn_Render_6b1a6441<T>['events']>, ReturnType<__svn_Render_6b1a6441<T>['slots']>> & { $$bindings?: ReturnType<__svn_Render_6b1a6441<T>['bindings']> } & ReturnType<__svn_Render_6b1a6441<T>['exports']>;
    <T>(internal: unknown, props: ReturnType<__svn_Render_6b1a6441<T>['props']>): ReturnType<__svn_Render_6b1a6441<T>['exports']> & { $set?: any; $on?: any };
    z_$$bindings?: ReturnType<__svn_Render_6b1a6441<any>['bindings']>;
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default<T> = InstanceType<typeof __svn_component_default<T>>;
export default __svn_component_default;

