// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_34355e12() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             (fade(__svn_map_element_tag('div'), (option.)));
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_34355e12;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_34355e12>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

