// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d92c900a() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        let hello: any = undefined;
        void hello;
        let aStr: any = undefined;
        void aStr;
        let aStr2: any = undefined;
        void aStr2;
        let aNum: any = undefined;
        void aNum;
        if ((name == "world")) {
            void [name];
        } else if ((true)) {
        } else {
        }
        if ((typeof a === 'string')) {
            void [a];
        } else if ((typeof a === 'number')) {
            void [a];
        }
        if ((typeof a === 'string')) {
            void [a];
        }
        if ((typeof a === 'string')) {
            void [a];
        } else {
        }
    }
    void __svn_tpl_check;
}
$$render_d92c900a;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

