// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9164d0bc() {
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            { svelteHTML.createElement("h1", {});             }
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_9164d0bc;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_9164d0bc>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

