// === input.svelte ===
// generated by svelte-check-native; do not edit
type $$ComponentProps = { someProp: typeof $store };
async function $$render_7503ba6a() {
    let $store!: __SvnStoreValue<typeof store>;

    let store = null;
    let { someProp }: { someProp: typeof $store } = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $store;
    void store;
    void someProp;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_7503ba6a;
declare const __svn_component_default: import('svelte').Component<$$ComponentProps>;
declare type __svn_component_default = import('svelte').SvelteComponent<$$ComponentProps>;
export default __svn_component_default;

