// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_468914b6() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            let foo: any;
            void foo;
            let baz: any;
            void baz;
            {
                const __svn_C_0 = __svn_ensure_component(Parent);
                new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            }
            {
                let bla: any;
                void bla;
                {
                    const __svn_C_23 = __svn_ensure_component(Component);
                    new __svn_C_23({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                }
                (foo);
                (baz);
                (bla);
            }
            {
                let blubb: any;
                void blubb;
                {
                    const __svn_C_73 = __svn_ensure_component(Component);
                    new __svn_C_73({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                }
                (blubb);
            }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_468914b6;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_468914b6>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

