// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{prop?: boolean}} $$ComponentProps */
async function $$render_e40e2c10() {
    const x = () => { async () => {
        (await promise);
        };
        return null;
    };
    void x;

    let { prop = true } = $props();
    const foo = await fetch('/foo');
    const promise = fetch('/bar');
    ;(async () => {
        // template type-check body (incremental)
        (foo);
        (await promise);
        for (let item of __svn_each_items(await promise)) {
            (item);
        }
        for (let item of __svn_each_items(await promise)) {
            let i = 1;
            (item);
            (i);
        }
        for (let item of __svn_each_items(await promise)) {
            let i = 1;
            (item.x);
            (item);
            (i);
        }
        for (let __svn_each_unused of __svn_each_items(await promise)) {
            __svn_each_unused;
        }
        if ((await promise)) {
        } else if ((await promise)) {
        }
        {
            const __svn_C_1d8 = __svn_ensure_component(Component);
            new __svn_C_1d8({ target: __svn_any(), props: {"prop": (await promise)} });
        }
        { svelteHTML.createElement("p", {
            "attribute": (await promise),
        });
        }
        (x(await promise));
        if ((true)) {
            const x = await promise;
            (x);
        }
    });
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

