// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_406d5f3a() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        ;(async () => {
            const $$_await = await (thePromise); const [ a, b ] = $$_await;
            void a;
            void b;
        });
        {
            const c = undefined;
            const d = undefined;
            const e = undefined;
            void c;
            void d;
            void e;
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_406d5f3a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_406d5f3a>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

