// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_97dfe1c3() {
    ;(async () => {
        // template type-check body (incremental)
        if ((''?.)) {
        } else if ((''.)) {
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_97dfe1c3;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_97dfe1c3>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

