// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e3c769f2() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        (a?.);
    }
    return { props: /** @type {any} */({}) };
}
$$render_e3c769f2;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e3c769f2>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

