// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_aa07c32b() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const value: any = undefined;
            void value;
        }
    }
    void __svn_tpl_check;
}
$$render_aa07c32b;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

