// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_cae62ddc() {

    let { a, b = $bindable(), c = $bindable(0) as number } = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
}
$$render_cae62ddc;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

