// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { a as b } from "./test.svelte"
    import * as c from "b.ts"
async function $$render_df4c5ef7() {

                                          

                             
           let world = "name"
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (world);
        }
    });
    void world;
    return { props: /** @type {{ world?: typeof world; }} */({}) };
}
$$render_df4c5ef7;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_df4c5ef7>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

