// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_3b561e62() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (somePromise);
        ;(async () => {
            const $$_await = await $$_promise; void $$_await;
            { svelteHTML.createElement("h1", {});             }
        }); }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_3b561e62;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_3b561e62>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_3b561e62>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

