// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6affb005() {

           let bla = false;
           let blubb = true;
           let bla1: boolean = false;
           let blubb1: boolean = true;
           let a1 = true, a2 = false, b1: boolean = true, b2: boolean = false;
    ;(async () => {
        // template type-check body (incremental)
    });
    void bla;
    void blubb;
    void bla1;
    void blubb1;
    void a1;
    void a2;
    void b1;
    void b2;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ bla: typeof bla; blubb: typeof blubb; bla1: boolean; blubb1: boolean; a1: typeof a1; a2: typeof a2; b1: boolean; b2: boolean; }} */ ({}) };
}
$$render_6affb005;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6affb005>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6affb005>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

