// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6affb005() {

           let bla = false;
           let blubb = true;
           let bla1: boolean = false;
           let blubb1: boolean = true;
           let a1 = true, a2 = false, b1: boolean = true, b2: boolean = false;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void bla;
    void blubb;
    void bla1;
    void blubb1;
    void a1;
    void a2;
    void b1;
    void b2;
    return { props: /** @type {any} */({}) };
}
$$render_6affb005;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6affb005>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

