// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_c1ba3c89() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_c1ba3c89;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

