// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    const snippetBlock = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
        {
            const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                };
                return __svn_any(0);
            };
            void foo;
            const foo2 = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                };
                return __svn_any(0);
            };
            void foo2;
            __svn_ensure_snippet(foo());
        }
        };
        return __svn_any(0);
    };
    void snippetBlock;
    ;(async () => {
        // template type-check body (incremental)
        if ((true)) {
            {
                const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                    };
                    return __svn_any(0);
                };
                void foo;
                __svn_ensure_snippet(foo());
            }
        }
        for (let item of __svn_each_items(arr)) {
            {
                const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                    };
                    return __svn_any(0);
                };
                void foo;
                __svn_ensure_snippet(foo());
            }
        }
        ;(key);
        {
            {
                const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                    };
                    return __svn_any(0);
                };
                void foo;
                __svn_ensure_snippet(foo());
            }
        }
        {
            const $$_value = await (Promise.resolve());
            { const bar = $$_value;
            {
                const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                    };
                    return __svn_any(0);
                };
                void foo;
                __svn_ensure_snippet(foo());
            }
            }
        }
        { svelteHTML.createElement("div", {});             {
                const foo = /** @returns {ReturnType<import('svelte').Snippet>} */ () => { async () => {
                    };
                    return __svn_any(0);
                };
                void foo;
                __svn_ensure_snippet(foo());
            }
        }
        {
            const __svn_C_1f7 = __svn_ensure_component(Component);
            const __svn_inst_1f7 = new __svn_C_1f7({
                target: __svn_any(),
                props: {
                    children: () => __svn_snippet_return(),
                    foo: () => { async () => {
                        };
                        return __svn_snippet_return();
                    },
                },
            });
            /*svn:ignore_start*/const { foo } = __svn_inst_1f7.$$prop_def;/*svn:ignore_end*/
            /*svn:ignore_start*/void foo;/*svn:ignore_end*/
            __svn_ensure_snippet(foo());
        }
    });
    return { props: /** @type {Record<string, never>} */ ({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

