// === input.svelte ===
// generated by svelte-check-native; do not edit

declare const Abc: { [key: string]: any } & ((...args: any[]) => any);
type A = {
    Abc: A
}
async function $$render_28c7ccd4() {

          
          
 

let {Abc}: A = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void Abc;
    return { props: undefined as any as (A), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_28c7ccd4;
declare const __svn_component_default: import('svelte').Component<A>;
declare type __svn_component_default = import('svelte').SvelteComponent<A>;
export default __svn_component_default;

