// === +page.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_aad4163e() {

           const snapshot: any = {};
    let { form, data }: {form: boolean, data: true } = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    void snapshot;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ snapshot: any; }} */ ({}) };
}
$$render_aad4163e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_aad4163e>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_aad4163e>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

