// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2d42b761() {
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(SomeComponent);
            new __svn_C_0({ target: __svn_any(), props: {"attrName": "text", "attrCase": "text"} });
        }
        { svelteHTML.createElement("someelement", {
            "attrname": `text`,
            "attrcase": true,
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_2d42b761;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2d42b761>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2d42b761>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

