// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2d42b761() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        SomeComponent(__svn_any(), {attrName: "text", attrCase: "text"});
    }
    void __svn_tpl_check;
}
$$render_2d42b761;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

