// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_c7e1c908() {
    ;(async () => {
        // template type-check body (incremental)
        for (const __svn_each_unused of __svn_each_items({ length: 5 })) {
            void __svn_each_unused;
        }
        for (const __svn_each_unused of __svn_each_items({ length: 5 }, index)) {
            (index);
            void __svn_each_unused;
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_c7e1c908;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_c7e1c908>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

