// === input.svelte ===
// generated by svelte-check-native; do not edit
    interface $$Props {
        /**
         * comment
         */
         a: boolean;
         b?: string;
    }
async function $$render_1764a80f() {
    let $$props: Record<string, any> = {};
    void $$props;

                       
           
                  
           
                    
                    
     
           function c() {}
    ;(async () => {
        // template type-check body (incremental)
        ($$props);
    });
    void c;
    return { props: undefined as any as ($$Props), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ c: () => void; }) };
}
$$render_1764a80f;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_1764a80f>>['props'] & __SvnAllProps>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_1764a80f>>['props'] & __SvnAllProps, Awaited<ReturnType<typeof $$render_1764a80f>>['events'], Awaited<ReturnType<typeof $$render_1764a80f>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_1764a80f>>['bindings'] } & Awaited<ReturnType<typeof $$render_1764a80f>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_1764a80f>>['props'] & __SvnAllProps): Awaited<ReturnType<typeof $$render_1764a80f>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_1764a80f>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

