// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_08571d44() {

    const schema = {
        key: "value"
    };
    ;(async () => {
        // template type-check body (incremental)
        (`<script type="application/ld+json">${JSON.stringify(schema)}</script>`);
    });
    void schema;
    return { props: /** @type {any} */({}) };
}
$$render_08571d44;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_08571d44>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

