// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ac9e756f() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (blink(__svn_map_element_tag('h1'), __svn_AnimationMove));
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_ac9e756f;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ac9e756f>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

