// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_85f76a10() {
    ;(async () => {
        // template type-check body (incremental)
        (myfile + someOtherFile);
    });
    return { props: /** @type {any} */({}) };
}
$$render_85f76a10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_85f76a10>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

