// === +page.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{form: any, data: any}} $$ComponentProps */
async function $$render_1c6cdc07() {

    let { form, data } = $props();
           const snapshot = {};
    ;(async () => {
        // template type-check body (incremental)
    });
    void snapshot;
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ snapshot: typeof snapshot; }} */ ({}) };
}
$$render_1c6cdc07;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_1c6cdc07>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_1c6cdc07>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

