// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        for (let item of __svn_each_items(items)) {
            for (let { a } of __svn_each_items(item)) {
                void a;
            }
            void item;
        }
        {
            const __svn_C_89 = __svn_ensure_component(Component);
            const __svn_inst_89 = new __svn_C_89({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, c } = __svn_inst_89.$$slot_def.default; $$_$$;
                void c;
                (c);
            }
        }
        { const $$_promise = (promise);
            const $$_await = await $$_promise; const d = $$_await;
            (d);
            void d;
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': { a: ((({ a }) => a)(__svn_unwrap_arr((__svn_unwrap_arr(items))))) }, 'second': { a: (a) }, 'third': { d: (d), c: (c) } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {__SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

