// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ce1c3a62() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const item of __svn_each_items(items)) {
            for (const { a } of __svn_each_items(item)) {
                void a;
            }
            void item;
        }
        {
            const __svn_C_89 = __svn_ensure_component(Component);
            const __svn_inst_89 = new __svn_C_89({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, c } = __svn_inst_89.$$slot_def.default; $$_$$;
                (c);
            }
        }
        ;(async () => {
            const $$_await = await (promise); const d = $$_await;
            (d);
            void d;
        });
    }
    return { props: /** @type {any} */({}) };
}
$$render_ce1c3a62;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ce1c3a62>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

