// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_557cd70e() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             __svn_ensure_transition(slide(__svn_map_element_tag('div')));
            (item);
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_557cd70e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_557cd70e>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_557cd70e>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

