//! TypeScript emission for the Svelte → `.svelte.ts` pipeline.
//!
//! ### Status: scaffolding pass only
//!
//! Currently emits a minimal-but-valid TypeScript wrapper around each Svelte
//! component:
//!
//! ```text
//! /// <reference types="svelte" />
//! [module script verbatim]
//! function $$render() {
//!     [instance script verbatim]
//!     async function __svn_tpl_check() { /* template check stub */ }
//!     void __svn_tpl_check;
//! }
//! ```
//!
//! Template-aware emission (real type-checking of the `<template>` body,
//! component instantiation, prop reference, store aliases, action attrs,
//! bind pairs, definite-assignment rewrites, etc.) lands incrementally as
//! the analyze crate exposes more `SemanticModel` data.
//!
//! The crucial design rule (from todo.md §1.4): every synthesized name
//! emitted here is registered in a `VoidRefRegistry` upstream and emitted
//! in a single consolidated `void (...)` block. The scaffolding emits
//! `void __svn_tpl_check` directly because there's only one synthesized
//! name in this pass; the registry-based emission switches on once we
//! have multiple names to coordinate.

// Tests are allowed to panic loudly on setup failures.
#![cfg_attr(test, allow(clippy::expect_used, clippy::unwrap_used))]

use svn_parser::Document;

/// Output of [`emit_document`].
///
/// Currently a thin wrapper around the emitted TypeScript string. Will grow
/// to carry source-map mappings and synthesized-name metadata as the emit
/// crate matures.
#[derive(Debug, Clone)]
pub struct EmitOutput {
    pub typescript: String,
}

/// Emit the TypeScript scaffold for a parsed Svelte document.
///
/// Scaffolding-pass behavior: passes script bodies through verbatim,
/// wraps in `function $$render() { ... }`, and registers
/// `__svn_tpl_check` as a void reference. No template traversal yet.
pub fn emit_document(doc: &Document<'_>) -> EmitOutput {
    let estimated_capacity = doc.source.len().saturating_mul(2).saturating_add(256);
    let mut out = String::with_capacity(estimated_capacity);

    out.push_str("/// <reference types=\"svelte\" />\n");
    out.push_str("// generated by svelte-check-native; do not edit\n");

    if let Some(module_script) = &doc.module_script {
        out.push_str(module_script.content);
        if !module_script.content.ends_with('\n') {
            out.push('\n');
        }
    }

    out.push_str("function $$render() {\n");
    if let Some(instance_script) = &doc.instance_script {
        out.push_str(instance_script.content);
        if !instance_script.content.ends_with('\n') {
            out.push('\n');
        }
    }

    out.push_str("    async function __svn_tpl_check() {\n");
    out.push_str("        // template type-check body (not yet emitted)\n");
    out.push_str("    }\n");
    out.push_str("    void __svn_tpl_check;\n");

    out.push_str("}\n");
    out.push_str("$$render;\n"); // reference $$render so noUnusedLocals doesn't fire

    EmitOutput { typescript: out }
}

#[cfg(test)]
mod tests {
    use super::*;
    use svn_parser::parse_sections;

    fn emit_str(src: &str) -> String {
        let (doc, errors) = parse_sections(src);
        assert!(errors.is_empty(), "parse errors: {errors:?}");
        emit_document(&doc).typescript
    }

    #[test]
    fn empty_source_still_emits_scaffold() {
        let out = emit_str("");
        assert!(out.contains("function $$render"));
        assert!(out.contains("__svn_tpl_check"));
        assert!(out.contains("void __svn_tpl_check"));
    }

    #[test]
    fn passes_instance_script_verbatim() {
        let out = emit_str("<script lang=\"ts\">let x: number = 1;</script>");
        assert!(out.contains("let x: number = 1;"));
    }

    #[test]
    fn passes_module_script_verbatim() {
        let out = emit_str("<script context=\"module\">export const A = 1;</script>");
        assert!(out.contains("export const A = 1;"));
    }

    #[test]
    fn both_scripts_in_order_module_first() {
        let src = "<script context=\"module\">export const A = 1;</script>\
                   <script>let b = 2;</script>";
        let out = emit_str(src);
        let a_pos = out.find("export const A").expect("module content present");
        let b_pos = out.find("let b = 2").expect("instance content present");
        assert!(a_pos < b_pos, "module script should come before instance");
    }

    #[test]
    fn includes_svelte_reference_directive() {
        let out = emit_str("<p>hi</p>");
        assert!(out.starts_with("/// <reference types=\"svelte\" />"));
    }

    #[test]
    fn template_check_wrapper_is_void_referenced() {
        // Bug fixture #7 grey-box: the wrapper must be referenced.
        let out = emit_str("<p>hi</p>");
        assert!(out.contains("void __svn_tpl_check"));
    }

    #[test]
    fn render_function_is_referenced() {
        let out = emit_str("<p>hi</p>");
        // $$render must also be self-referenced to avoid TS6133.
        assert!(out.contains("$$render;"));
    }
}
