//! TypeScript emission for the Svelte → `.svelte.ts` pipeline.
//!
//! ### Status: scaffolding pass only
//!
//! Currently emits a minimal-but-valid TypeScript wrapper around each Svelte
//! component:
//!
//! ```text
//! /// <reference types="svelte" />
//! [module script verbatim]
//! function $$render() {
//!     [instance script verbatim]
//!     async function __svn_tpl_check() { /* template check stub */ }
//!     void __svn_tpl_check;
//! }
//! ```
//!
//! Template-aware emission (real type-checking of the `<template>` body,
//! component instantiation, prop reference, store aliases, action attrs,
//! bind pairs, definite-assignment rewrites, etc.) lands incrementally as
//! the analyze crate exposes more `SemanticModel` data.
//!
//! The crucial design rule (from todo.md §1.4): every synthesized name
//! emitted here is registered in a `VoidRefRegistry` upstream and emitted
//! in a single consolidated `void (...)` block. The scaffolding emits
//! `void __svn_tpl_check` directly because there's only one synthesized
//! name in this pass; the registry-based emission switches on once we
//! have multiple names to coordinate.

// Tests are allowed to panic loudly on setup failures.
#![cfg_attr(test, allow(clippy::expect_used, clippy::unwrap_used))]

use std::fmt::Write;

use smol_str::SmolStr;
use svn_analyze::TemplateSummary;
use svn_parser::Document;
use svn_parser::{EachBlock, Fragment, Node};

/// Output of [`emit_document`].
///
/// Currently a thin wrapper around the emitted TypeScript string. Will grow
/// to carry source-map mappings and synthesized-name metadata as the emit
/// crate matures.
#[derive(Debug, Clone)]
pub struct EmitOutput {
    pub typescript: String,
}

/// Emit the TypeScript scaffold for a parsed Svelte document.
///
/// `fragment` is the parsed template AST; the emitter walks it to generate
/// per-block scaffolding (currently just `for`-loops for `{#each}`).
///
/// Reads the [`TemplateSummary`] from analyze to know which synthesized names
/// need void-references. The summary's [`VoidRefRegistry`] is the single
/// source of truth for what gets emitted in the consolidated `void (...)`
/// block — replaces the per-feature reactive `void x;` emissions that
/// littered `-rs`'s transformer.
///
/// [`VoidRefRegistry`]: svn_analyze::VoidRefRegistry
pub fn emit_document(
    doc: &Document<'_>,
    fragment: &Fragment,
    summary: &TemplateSummary,
) -> EmitOutput {
    let estimated_capacity = doc.source.len().saturating_mul(2).saturating_add(256);
    let mut out = String::with_capacity(estimated_capacity);

    out.push_str("/// <reference types=\"svelte\" />\n");
    out.push_str("// generated by svelte-check-native; do not edit\n");

    if let Some(module_script) = &doc.module_script {
        out.push_str(module_script.content);
        if !module_script.content.ends_with('\n') {
            out.push('\n');
        }
    }

    out.push_str("function $$render() {\n");
    if let Some(instance_script) = &doc.instance_script {
        let bind_target_names: Vec<SmolStr> = summary
            .bind_this_targets
            .iter()
            .map(|t| t.name.clone())
            .collect();
        let rewritten = rewrite_definite_assignment(instance_script.content, &bind_target_names);
        out.push_str(&rewritten);
        if !rewritten.ends_with('\n') {
            out.push('\n');
        }
    }

    out.push_str("    async function __svn_tpl_check() {\n");
    out.push_str("        // template type-check body (incremental)\n");
    emit_action_attrs_declarations(&mut out, summary);
    emit_bind_pair_declarations(&mut out, summary);
    emit_template_body(&mut out, doc.source, fragment, 2);
    out.push_str("    }\n");

    emit_void_block(&mut out, summary);

    out.push_str("}\n");
    out.push_str("$$render;\n");

    EmitOutput { typescript: out }
}

/// Walk the fragment tree and emit per-construct scaffolding.
///
/// Currently handles `{#each}` blocks (for fixture #25 + general iteration)
/// and recurses into other block bodies / element children. Element- and
/// component-level type-checking is not yet implemented; nodes other than
/// each blocks contribute only via their nested children.
fn emit_template_body(out: &mut String, source: &str, fragment: &Fragment, depth: usize) {
    for node in &fragment.nodes {
        emit_template_node(out, source, node, depth);
    }
}

fn emit_template_node(out: &mut String, source: &str, node: &Node, depth: usize) {
    match node {
        Node::EachBlock(b) => emit_each_block(out, source, b, depth),
        Node::IfBlock(b) => {
            emit_template_body(out, source, &b.consequent, depth);
            for arm in &b.elseif_arms {
                emit_template_body(out, source, &arm.body, depth);
            }
            if let Some(alt) = &b.alternate {
                emit_template_body(out, source, alt, depth);
            }
        }
        Node::AwaitBlock(b) => {
            if let Some(p) = &b.pending {
                emit_template_body(out, source, p, depth);
            }
            if let Some(t) = &b.then_branch {
                emit_template_body(out, source, &t.body, depth);
            }
            if let Some(c) = &b.catch_branch {
                emit_template_body(out, source, &c.body, depth);
            }
        }
        Node::KeyBlock(b) => emit_template_body(out, source, &b.body, depth),
        Node::SnippetBlock(b) => emit_template_body(out, source, &b.body, depth),
        Node::Element(e) => emit_template_body(out, source, &e.children, depth),
        Node::Component(c) => emit_template_body(out, source, &c.children, depth),
        Node::SvelteElement(s) => emit_template_body(out, source, &s.children, depth),
        Node::Text(_) | Node::Interpolation(_) | Node::Comment(_) => {}
    }
}

/// Emit a `for`-of loop for an `{#each}` block.
///
/// Uses a fallback binding name when the block has no `as` clause —
/// fixes the `for (const  of ...)` syntax error from `-rs` bug #25.
fn emit_each_block(out: &mut String, source: &str, b: &EachBlock, depth: usize) {
    let indent = "    ".repeat(depth);
    let expr_text = source
        .get(b.expression_range.start as usize..b.expression_range.end as usize)
        .unwrap_or("undefined")
        .trim();
    let binding_text = match &b.as_clause {
        Some(c) => source
            .get(c.context_range.start as usize..c.context_range.end as usize)
            .unwrap_or("__svn_each_unused")
            .to_string(),
        None => "__svn_each_unused".to_string(),
    };
    let _ = writeln!(
        out,
        "{indent}for (const {binding_text} of __svn_each_items({expr_text})) {{"
    );
    emit_template_body(out, source, &b.body, depth + 1);
    let _ = writeln!(out, "{indent}    void {};", first_identifier(&binding_text));
    let _ = writeln!(out, "{indent}}}");

    if let Some(alt) = &b.alternate {
        emit_template_body(out, source, alt, depth);
    }
}

/// Extract the first identifier-looking token from a binding pattern (for
/// the `void <name>;` reference inside a for-loop body — keeps the
/// destructured name "used" even if the inner template emit doesn't reach
/// it yet).
fn first_identifier(binding: &str) -> &str {
    let trimmed =
        binding.trim_start_matches(|c: char| !c.is_ascii_alphanumeric() && c != '_' && c != '$');
    let end = trimmed
        .find(|c: char| !c.is_ascii_alphanumeric() && c != '_' && c != '$')
        .unwrap_or(trimmed.len());
    let head = &trimmed[..end];
    if head.is_empty() {
        "__svn_each_unused"
    } else {
        head
    }
}

/// Rewrite `let <name>: T` declarations to `let <name>!: T` for each
/// bind-target identifier. Bug fixture #30 (definite-assignment).
///
/// Only matches `let <name>:` patterns with the colon — declarations with
/// initializers (`let x = ...`) don't have the type-annotation form and
/// don't need the `!` (they're already definitely assigned).
fn rewrite_definite_assignment(script: &str, target_names: &[SmolStr]) -> String {
    if target_names.is_empty() {
        return script.to_string();
    }
    let mut out = String::with_capacity(script.len() + target_names.len() * 2);
    let bytes = script.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if let Some(consumed) = try_match_let_decl(bytes, i, target_names) {
            // Insert: "let <name>!" replacing "let <name>".
            // `consumed.0` is the offset just after the matched name; we
            // splice `!` before continuing.
            out.push_str(&script[i..consumed.name_end]);
            out.push('!');
            i = consumed.name_end;
        } else {
            // Push current byte (handle multi-byte char advance).
            let ch_len = utf8_char_len(bytes[i]);
            out.push_str(&script[i..i + ch_len]);
            i += ch_len;
        }
    }
    out
}

struct LetMatch {
    name_end: usize,
}

/// At byte position `i`, try to match `let <name>` where `<name>` is one of
/// `target_names` AND is followed by `:` (after optional whitespace).
/// Returns the position immediately after the matched name on success.
fn try_match_let_decl(bytes: &[u8], i: usize, target_names: &[SmolStr]) -> Option<LetMatch> {
    // Match `let` keyword at a word boundary.
    if i + 3 > bytes.len() || &bytes[i..i + 3] != b"let" {
        return None;
    }
    if i > 0 && is_ident_byte(bytes[i - 1]) {
        return None;
    }
    let after_let = i + 3;
    if after_let >= bytes.len() || !is_ascii_ws(bytes[after_let]) {
        return None;
    }
    let mut p = after_let;
    while p < bytes.len() && is_ascii_ws(bytes[p]) {
        p += 1;
    }
    let name_start = p;
    while p < bytes.len() && is_ident_byte(bytes[p]) {
        p += 1;
    }
    let name_end = p;
    if name_end == name_start {
        return None;
    }
    let name = &bytes[name_start..name_end];
    if !target_names.iter().any(|t| t.as_bytes() == name) {
        return None;
    }
    // Must be followed by `:` (with optional whitespace). Avoid matching
    // `let x = ...` (which doesn't need `!`) or `let x;` (no annotation).
    let mut q = name_end;
    while q < bytes.len() && is_ascii_ws(bytes[q]) {
        q += 1;
    }
    if q >= bytes.len() || bytes[q] != b':' {
        return None;
    }
    Some(LetMatch { name_end })
}

#[inline]
fn is_ascii_ws(b: u8) -> bool {
    matches!(b, b' ' | b'\t' | b'\n' | b'\r')
}

#[inline]
fn is_ident_byte(b: u8) -> bool {
    b.is_ascii_alphanumeric() || b == b'_' || b == b'$'
}

#[inline]
fn utf8_char_len(b: u8) -> usize {
    if b < 0xC0 {
        1
    } else if b < 0xE0 {
        2
    } else if b < 0xF0 {
        3
    } else {
        4
    }
}

/// Emit `let __svn_action_attrs_N: any = {};` declarations inside
/// `__svn_tpl_check` — one per `use:` directive seen in the template.
///
/// We currently emit them as untyped placeholders. The real action-return
/// helper (`__svn_ensure_action<T>`) gets wired in once the typecheck crate
/// is ready.
fn emit_action_attrs_declarations(out: &mut String, summary: &TemplateSummary) {
    for name in summary.void_refs.names() {
        if name.starts_with("__svn_action_attrs_") {
            let _ = writeln!(out, "        let {name}: any = {{}};");
        }
    }
}

/// Emit `let __svn_bind_pair_N: [() => any, (v: any) => void] = ...;` placeholders.
fn emit_bind_pair_declarations(out: &mut String, summary: &TemplateSummary) {
    for name in summary.void_refs.names() {
        if name.starts_with("__svn_bind_pair_") {
            let _ = writeln!(
                out,
                "        let {name}: [() => any, (v: any) => void] = [() => undefined as any, () => {{}}];"
            );
        }
    }
}

/// Emit the consolidated `void (a, b, c, ...);` block that prevents
/// `noUnusedLocals` from firing on every synthesized name.
fn emit_void_block(out: &mut String, summary: &TemplateSummary) {
    let names = summary.void_refs.names();
    if names.is_empty() {
        return;
    }
    out.push_str("    void (");
    for (i, name) in names.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(name);
    }
    out.push_str(");\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use svn_analyze::walk_template;
    use svn_parser::{parse_all_template_runs, parse_sections};

    fn emit_str(src: &str) -> String {
        let (doc, errors) = parse_sections(src);
        assert!(errors.is_empty(), "parse errors: {errors:?}");
        let (fragment, errors) = parse_all_template_runs(src, &doc.template.text_runs);
        assert!(errors.is_empty(), "template parse errors: {errors:?}");
        let summary = walk_template(&fragment, src);
        emit_document(&doc, &fragment, &summary).typescript
    }

    #[test]
    fn empty_source_still_emits_scaffold() {
        let out = emit_str("");
        assert!(out.contains("function $$render"));
        assert!(out.contains("__svn_tpl_check"));
        assert!(out.contains("void (__svn_tpl_check"));
    }

    #[test]
    fn passes_instance_script_verbatim() {
        let out = emit_str("<script lang=\"ts\">let x: number = 1;</script>");
        assert!(out.contains("let x: number = 1;"));
    }

    #[test]
    fn passes_module_script_verbatim() {
        let out = emit_str("<script context=\"module\">export const A = 1;</script>");
        assert!(out.contains("export const A = 1;"));
    }

    #[test]
    fn both_scripts_in_order_module_first() {
        let src = "<script context=\"module\">export const A = 1;</script>\
                   <script>let b = 2;</script>";
        let out = emit_str(src);
        let a_pos = out.find("export const A").expect("module content present");
        let b_pos = out.find("let b = 2").expect("instance content present");
        assert!(a_pos < b_pos, "module script should come before instance");
    }

    #[test]
    fn includes_svelte_reference_directive() {
        let out = emit_str("<p>hi</p>");
        assert!(out.starts_with("/// <reference types=\"svelte\" />"));
    }

    #[test]
    fn template_check_wrapper_in_void_block() {
        // Bug fixture #7 grey-box.
        let out = emit_str("<p>hi</p>");
        assert!(out.contains("void ("));
        assert!(out.contains("__svn_tpl_check"));
    }

    #[test]
    fn use_directive_emits_action_attrs() {
        // Bug fixture #8 grey-box.
        let out = emit_str("<div use:tooltip>x</div>");
        assert!(out.contains("__svn_action_attrs_0"));
        // Both declared (inside __svn_tpl_check) and void-referenced.
        assert!(out.contains("let __svn_action_attrs_0"));
    }

    #[test]
    fn bind_pair_emits_bind_pair_declaration() {
        // Bug fixture #9 grey-box.
        let out = emit_str("<input bind:value={() => g(), (v) => s(v)} />");
        assert!(out.contains("__svn_bind_pair_0"));
        assert!(out.contains("let __svn_bind_pair_0"));
    }

    #[test]
    fn render_function_is_referenced() {
        let out = emit_str("<p>hi</p>");
        assert!(out.contains("$$render;"));
    }

    #[test]
    fn void_block_is_consolidated() {
        // Multiple synthesized names should appear in ONE void(...) block,
        // not multiple void X; statements.
        let out = emit_str("<div use:a use:b>x</div>");
        let void_count = out.matches("    void (").count();
        assert_eq!(void_count, 1, "expected exactly one void(...) block");
    }

    // ===== Bug fixture #25 (each-without-as-clause) =====
    #[test]
    fn each_block_emits_for_loop() {
        let out = emit_str("{#each items}<span>x</span>{/each}");
        assert!(out.contains("for (const"), "missing for-of loop:\n{out}");
        assert!(
            !out.contains("for (const  of"),
            "double-space before `of` (regression of bug #25):\n{out}"
        );
    }

    #[test]
    fn each_block_with_binding_uses_user_name() {
        let out = emit_str("{#each items as item}<span>{item}</span>{/each}");
        assert!(out.contains("for (const item of"));
    }

    #[test]
    fn each_with_destructured_pattern() {
        let out = emit_str("{#each pairs as { a, b }}<x />{/each}");
        // Should still produce a for-of without double-space-of.
        assert!(out.contains("for (const"));
        assert!(!out.contains("for (const  of"));
    }

    // ===== Bug fixture #30 (definite-assignment) =====
    #[test]
    fn bind_this_target_gets_definite_assignment() {
        let src = "<script lang=\"ts\">let inputEl: HTMLDivElement;</script>\
                   <div bind:this={inputEl}></div>";
        let out = emit_str(src);
        assert!(
            out.contains("let inputEl!:"),
            "missing definite-assignment rewrite:\n{out}"
        );
        assert!(
            !out.contains("let inputEl: "),
            "still has un-rewritten declaration:\n{out}"
        );
    }

    #[test]
    fn non_bind_target_let_unchanged() {
        let src = "<script lang=\"ts\">let other: number = 1;</script>";
        let out = emit_str(src);
        assert!(
            out.contains("let other: number"),
            "non-bind-target should not be rewritten:\n{out}"
        );
        assert!(!out.contains("let other!"));
    }

    #[test]
    fn bind_target_with_initializer_unchanged() {
        // `let x = ...` (no `:`) doesn't need the `!` and we shouldn't
        // touch it. Bug fixture #30 only rewrites declared-but-not-yet-
        // assigned variables.
        let src = "<script lang=\"ts\">let inputEl = null as any as HTMLDivElement;</script>\
                   <div bind:this={inputEl}></div>";
        let out = emit_str(src);
        assert!(
            !out.contains("let inputEl!"),
            "shouldn't add `!` to declarations with initializers:\n{out}"
        );
    }
}
