// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b5ddc729() {
    /** @type {__SvnStoreValue<typeof transitionStore>} */
    let $transitionStore = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof actionStore>} */
    let $actionStore = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof inStore>} */
    let $inStore = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof outStore>} */
    let $outStore = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof animateStore>} */
    let $animateStore = /** @type {any} */ (/** @type {any} */ (null));

	const transitionStore = null;
	const animateStore = null;
	const inStore = null;
	const outStore = null;
	const actionStore = null;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        /** @type {any} */ let __svn_action_attrs_0 = {};
        void __svn_action_attrs_0;
            const __svn_action_0 = __svn_ensure_action($actionStore(__svn_map_element_tag('div')));
        { svelteHTML.createElement("div", __svn_union(__svn_action_0), {});             void __svn_action_0;
        }
    }
    void __svn_tpl_check;
    void $transitionStore;
    void transitionStore;
    void $actionStore;
    void actionStore;
    void $inStore;
    void inStore;
    void $outStore;
    void outStore;
    void $animateStore;
    void animateStore;
    return { props: /** @type {any} */({}) };
}
$$render_b5ddc729;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b5ddc729>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

