// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0bc1cb85() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const foo: any = undefined;
            void foo;
            const bar: any = undefined;
            void bar;
            const await_inside: any = undefined;
            void await_inside;
            const defaultValue: any = undefined;
            void defaultValue;
            const jsDoc: any = undefined;
            void jsDoc;
            {
                void ((x: any) => {
                    void x;
                });
            }
            {
                const bar: any = undefined;
                void bar;
            }
            {
                void ((x: any = '') => {
                    void x;
                });
            }
            Component(__svn_any(), {
                bar: (x) => {
                    void x;
                    return __svn_snippet_return();
                },
            });
            List(__svn_any(), {
                data: ([1, 2, 3]),
                row: (item) => {
                    void item;
                    return __svn_snippet_return();
                },
                await_inside: () => {
                    {
                        const bar: any = undefined;
                        void bar;
                    }
                    return __svn_snippet_return();
                },
            });
            List(__svn_any(), {});
            List(__svn_any(), {
                data: ([1, 2, 3]),
                row1: (item) => {
                    void item;
                    return __svn_snippet_return();
                },
                row2: (item) => {
                    void item;
                    return __svn_snippet_return();
                },
            });
            {
                void ((/**@type {number}*/a: any) => {
                    void type;
                    void number;
                    void a;
                });
            }
        }
    }
    void __svn_tpl_check;
}
$$render_0bc1cb85;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

