// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e40e2c10() {

           let name = "world"
    ;(async () => {
        // template type-check body (incremental)
    });
    void name;
    return { props: /** @type {{ name?: typeof name; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ name: typeof name; }} */ ({}) };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

