// === input.svelte ===
// generated by svelte-check-native; do not edit
  import { getDuration, type AppVideo } from './helpers'
async function $$render_6743ac1f() {

                                                        
  let { item }: { item: unknown } = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        /*svn_I*/(getDuration(item as AppVideo));
    }
    void __svn_tpl_check;
    void item;
    void getDuration;
}
$$render_6743ac1f;
declare const __svn_component_default: import('svelte').Component<{ item: unknown }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ item: unknown }>;
type __svn_tpl_type_refs = [AppVideo];
void (0 as any as __svn_tpl_type_refs);
export default __svn_component_default;

