// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_253956d9() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});         }
    }
    return { props: /** @type {any} */({}) };
}
$$render_253956d9;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_253956d9>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

