// === input.svelte ===
// generated by svelte-check-native; do not edit
	import {writable} from "svelte/store";
	type Foo = typeof $foo;
async function $$render_67fe81da() {
    let $foo!: __SvnStoreValue<typeof foo>;

	                                      
	const foo = writable(1);
	                       
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $foo;
    void foo;
}
$$render_67fe81da;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

