// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const exported1: { [key: string]: any } & ((...args: any[]) => any);
declare const exported2: { [key: string]: any } & ((...args: any[]) => any);
declare const name1: { [key: string]: any } & ((...args: any[]) => any);
declare const name2: { [key: string]: any } & ((...args: any[]) => any);
    type $$Props = {
        exported1: string;
        exported2?: string;
        name1?: string;
        name2: string;
        renamed1?: string;
        renamed2: string;
    }
async function $$render_a154bb54() {


                    
                          
                           
                       
                      
                          
                         
     

           let exported1!: string;
           let exported2: string = '';
exported2 = undefined as any;

    let name1: string = "world"
name1 = undefined as any;
    let name2!: string;

    let rename1: string = '';
rename1 = undefined as any;
    let rename2!: string;

    class Foo {}
    function bar() {}
    const baz: string = '';

    class RenameFoo {}
    function renamebar() {}
    const renamebaz: string = '';

                                                                                                                                                                
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void exported1;
    void exported2;
    void name1;
    void name2;
    void rename1;
    void rename2;
    void Foo;
    void bar;
    void baz;
    void RenameFoo;
    void renamebar;
    void renamebaz;
    return { props: undefined as any as ({ exported1: string; exported2?: string; name1?: string; name2: string; renamed1?: string; renamed2: string; Foo: any; bar: any; baz?: string; RenamedFoo: any; renamedbar: any; renamedbaz?: string; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ exported1: string; exported2: string; }) };
}
$$render_a154bb54;
declare const __svn_component_default: import('svelte').Component<{ exported1: string; exported2?: string; name1?: string; name2: string; renamed1?: string; renamed2: string; Foo: any; bar: any; baz?: string; RenamedFoo: any; renamedbar: any; renamedbaz?: string; }, { exported1: string; exported2: string; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ exported1: string; exported2?: string; name1?: string; name2: string; renamed1?: string; renamed2: string; Foo: any; bar: any; baz?: string; RenamedFoo: any; renamedbar: any; renamedbaz?: string; }> & { exported1: string; exported2: string; };
export default __svn_component_default;

