// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_61aafdfb() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        void ({shorthand} satisfies Partial<__SvnComponentProps<typeof SomeComponent>>);
    }
    void __svn_tpl_check;
}
$$render_61aafdfb;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

