// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (object);
            const $$_await = await $$_promise; const { a, ...rest } = $$_await;
            void a;
            void rest;
        }
        { const $$_promise = (array);
            const $$_await = await $$_promise; const [a, b, ...rest] = $$_await;
            void a;
            void b;
            void rest;
        }
        { const $$_promise = (objectReject);
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }
        {
            const a = __svn_any();
            const rest = __svn_any();
            void a;
            void rest;
        }
        { const $$_promise = (arrayReject);
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }
        {
            const a = __svn_any();
            const b = __svn_any();
            const rest = __svn_any();
            void a;
            void b;
            void rest;
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

