// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_8b99b80f() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (object);
        ;(async () => {
            const $$_await = await $$_promise; const { a, ...rest } = $$_await;
            void a;
            void rest;
        }); }
        { const $$_promise = (array);
        ;(async () => {
            const $$_await = await $$_promise; const [a, b, ...rest] = $$_await;
            void a;
            void b;
            void rest;
        }); }
        { const $$_promise = (objectReject);
        ;(async () => {
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }); }
        {
            const a = undefined;
            const rest = undefined;
            void a;
            void rest;
        }
        { const $$_promise = (arrayReject);
        ;(async () => {
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }); }
        {
            const a = undefined;
            const b = undefined;
            const rest = undefined;
            void a;
            void b;
            void rest;
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_8b99b80f;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_8b99b80f>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

