// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{a: any, b: any}} $$ComponentProps */
async function $$render_8eb00eb4() {

    let { a, b } = $props();
    let x = $state(0);
    let y = $derived(x * 2);
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {$$ComponentProps} */({}) };
}
$$render_8eb00eb4;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_8eb00eb4>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

