// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_de415949() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("html", {
            "lang": `en`,
        });
            { svelteHTML.createElement("body", {});                 { svelteHTML.createElement("h1", {});                 }
            }
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_de415949;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_de415949>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

