// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a8c1b0a7() {

    let { a, b }: { a: number, b: string } = $props();
    let x = $state(0);
    let y = $derived(x * 2);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
}
$$render_a8c1b0a7;
declare function __svn_component_default(__anchor: any, props: { a: number, b: string }): any;
declare type __svn_component_default = (__anchor: any, props: { a: number, b: string }) => any;
export default __svn_component_default;

