// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_50fd1c6b() {

           let a!: number;
           let b!: number | undefined;
           let c: number = 123;
c = undefined as any;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    return { props: undefined as any as ({ a: number; b: number | undefined; c?: number; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ a: number; b: number | undefined; c: number; }) };
}
$$render_50fd1c6b;
declare const __svn_component_default: import('svelte').Component<{ a: number; b: number | undefined; c?: number; }, { a: number; b: number | undefined; c: number; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ a: number; b: number | undefined; c?: number; }> & { a: number; b: number | undefined; c: number; };
export default __svn_component_default;

