// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_636933a9() {
$b=$b.concat(5)
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {
            "on:click": (() => $b=$b.concat(5)),
        });
            ($b);
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_636933a9;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_636933a9>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

