// === Switch.svelte ===
// generated by svelte-check-native; do not edit
type $$ComponentProps = {
        checked: boolean;
        onchange: (event: { checked: boolean }) => void;
    };
async function $$render_1497f2af() {

    let {
        checked,
        onchange,
    }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "onclick": (() => onchange({ checked: !checked })),
        });
            (checked ? 'on' : 'off');
        }
    }
    void __svn_tpl_check;
    void checked;
    void onchange;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_1497f2af;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_1497f2af>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_1497f2af>>['props'], Awaited<ReturnType<typeof $$render_1497f2af>>['events'], Awaited<ReturnType<typeof $$render_1497f2af>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_1497f2af>>['bindings'] } & Awaited<ReturnType<typeof $$render_1497f2af>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_1497f2af>>['props']): Awaited<ReturnType<typeof $$render_1497f2af>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_1497f2af>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

// === input.svelte ===
// generated by svelte-check-native; do not edit
    import Switch from './Switch.svelte';
async function $$render_026729db() {

                                         

    let isOn = $state(false);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_1a4 = __svn_ensure_component(Switch);
            new __svn_C_1a4({ target: __svn_any(), props: {"checked": (isOn), "onchange": (({ checked }) => (isOn = checked))} });
        }
    }
    void __svn_tpl_check;
    void Switch;
    void isOn;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_026729db;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_026729db>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_026729db>>['props'], Awaited<ReturnType<typeof $$render_026729db>>['events'], Awaited<ReturnType<typeof $$render_026729db>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_026729db>>['bindings'] } & Awaited<ReturnType<typeof $$render_026729db>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_026729db>>['props']): Awaited<ReturnType<typeof $$render_026729db>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_026729db>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

