// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_bedc65d7() {
    ;(async () => {
        // template type-check body (incremental)
        ;(async () => {
            const $$_await = await (somePromise); const value = $$_await;
            { svelteHTML.createElement("h1", {});             }
            void value;
        });
        { svelteHTML.createElement("h2", {});         }
    });
    return { props: /** @type {any} */({}) };
}
$$render_bedc65d7;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_bedc65d7>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

