// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    type Size = 'small' | 'large';

    // A long string split across lines with the operator at the end of
    // each line. Nothing may be inserted before the expression finishes.
           let label: string =
        'first part, ' +
        'second part'/*svn:ignore_start*/;label = __svn_any(label);/*svn:ignore_end*/;

           let size: Size = 'small'/*svn:ignore_start*/;size = __svn_any(size);/*svn:ignore_end*/;

    const isLarge = size === 'large';
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             (isLarge);
            label;
        }
    });
    void label;
    void size;
    return { props: undefined as any as ({ label?: string; size?: Size; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] extends Record<string, never> ? { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] } : Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] & { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] }): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

