// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_19e9402e() {
    /** @type {__SvnStoreValue<typeof store>} */
    let $store = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store1>} */
    let $store1 = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store2>} */
    let $store2 = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store3>} */
    let $store3 = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store4>} */
    let $store4 = /** @type {any} */ (/** @type {any} */ (null));

    const store = fromSomewhere();
    const { store1, store2, noStore } = fromSomewhere();
    const [ store3, store4, noStore ] = fromSomewhere();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             ($store);
        }
        { svelteHTML.createElement("p", {});             ($store1);
        }
        { svelteHTML.createElement("p", {});             ($store2);
        }
        { svelteHTML.createElement("p", {});             ($store3);
        }
        { svelteHTML.createElement("p", {});             ($store4);
        }
    }
    void $store;
    void store;
    void $store1;
    void store1;
    void $store2;
    void store2;
    void $store3;
    void store3;
    void $store4;
    void store4;
    return { props: /** @type {any} */({}) };
}
$$render_19e9402e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_19e9402e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

