// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_19e9402e() {
    let $store!: __SvnStoreValue<typeof store>;
    let $store1!: __SvnStoreValue<typeof store1>;
    let $store2!: __SvnStoreValue<typeof store2>;
    let $store3!: __SvnStoreValue<typeof store3>;
    let $store4!: __SvnStoreValue<typeof store4>;

    const store = fromSomewhere();
    const { store1, store2, noStore } = fromSomewhere();
    const [ store3, store4, noStore ] = fromSomewhere();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $store;
    void store;
    void $store1;
    void store1;
    void $store2;
    void store2;
    void $store3;
    void store3;
    void $store4;
    void store4;
}
$$render_19e9402e;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

