// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_469e1c1c() {

    // Reviewer item #1a: `bind:this` on `<svelte:self>` /
    // `<svelte:component>` is a COMPONENT instance ref, not an
    // HTMLElement. Pre-fix the DOM-element bind:this check fired
    // here, wrapping the target with `__svn_bind_this_check<…>`
    // which expected an HTMLElement-compatible value. The
    // component-instance type (e.g. `let me: any`) doesn't
    // satisfy that, so a spurious TS2322 fired at every
    // `<svelte:self bind:this={…}>` site. The full
    // component-instantiation port (#1b) is deferred — for now
    // we just stop emitting the wrong DOM-element check.
    let me: any = null
; me = undefined as any;    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "runes": true,
        });
        }
        {
            const __svn_C_2b0 = __svn_ensure_component(__svn_self_default);
            const __svn_inst_2b0 = new __svn_C_2b0({ target: __svn_any(), props: {} });
            me = __svn_inst_2b0;
        }
    });
    void me;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_469e1c1c;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_469e1c1c>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_469e1c1c>>['props'], Awaited<ReturnType<typeof $$render_469e1c1c>>['events'], Awaited<ReturnType<typeof $$render_469e1c1c>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_469e1c1c>>['bindings'] } & Awaited<ReturnType<typeof $$render_469e1c1c>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_469e1c1c>>['props']): Awaited<ReturnType<typeof $$render_469e1c1c>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_469e1c1c>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

