// === input.svelte ===
// generated by svelte-check-native; do not edit
interface $$Events {
        /**
         * Some doc
         */
        'a-b': boolean;
        'b': string;
        'c';
    }
async function $$render_6ada794f() {

                        
           
                   
           
                       
                    
            
     
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_6ada794f;
declare const __svn_component_default: import('svelte').Component<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
export default __svn_component_default;

