// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7fab75cd() {

    /**
     * DOCS!
     */
           let a: string;
    /**
     * MORE DOCS!
     */
           let b = 1;
           let c = /** @type {any} */ (null);

    // not this one
           let d = /** @type {any} */ (null);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    void d;
    return { props: /** @type {any} */({}) };
}
$$render_7fab75cd;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_7fab75cd>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

