// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f39ccf3a() {

	       let boxes = [
		{width: 3, height: 4},
		{width: 5, height: 7},
		{width: 6, height: 8},
	];
	       let constant = 10;

	function calculate(width, height, constant) {
		return { area: width * height, volume: width * height * constant };
	}
    ;(async () => {
        // template type-check body (incremental)
        for (const { width, height } of __svn_each_items(boxes)) {
            const {area, volume} = calculate(width, height, constant);
            void area;
            void volume;
            const perimeter = (width + height) * constant;
            void perimeter;
            const [_width, _height, sum] = [width * constant, height, width * constant + height];
            void _width;
            void _height;
            void sum;
            { svelteHTML.createElement("div", {});                 (area);
                (volume);
                (perimeter);
                (_width);
                (_height);
                (sum);
            }
            void width;
            void height;
        }
    });
    void boxes;
    void calculate;
    void constant;
    return { props: /** @type {{ boxes?: typeof boxes; constant?: typeof constant; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ boxes: typeof boxes; constant: typeof constant; }} */ ({}) };
}
$$render_f39ccf3a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f39ccf3a>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f39ccf3a>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

