// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9b8ccf5e() {
    let $store!: __SvnStoreValue<typeof store>;

    let store = null;
    const foo = { $store };
    const bar = { $store: $store };
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $store;
    void store;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_9b8ccf5e;
declare const __svn_component_default: import('svelte').Component<Awaited<ReturnType<typeof $$render_9b8ccf5e>>['props']>;
declare type __svn_component_default = import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_9b8ccf5e>>['props']>;
export default __svn_component_default;

