// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9b8ccf5e() {
    let $store!: __SvnStoreValue<typeof store>;

    let store = null;
    const foo = { $store };
    const bar = { $store: $store };
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $store;
    void store;
}
$$render_9b8ccf5e;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

