// === input.svelte ===
// generated by svelte-check-native; do not edit
// Real `createEventDispatcher()` call — must disqualify the
// `__sveltets_2_fn_component` default-export shape and route
// through the iso-component interface so child events surface
// at consumer sites.
import { createEventDispatcher } from 'svelte'
function $$render_e40e2c10() {
    type $$ComponentProps = { value: number };
    type $$Events = ({ [__svn_K in keyof (({ click: { id: number } }))]: CustomEvent<(({ click: { id: number } }))[__svn_K]> }) & { [evt: string]: CustomEvent<any> };

                                                              
                                                             
                                                              
                     
                                              

const dispatch = createEventDispatcher<{ click: { id: number } }>()

let { value }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props()

function handle() {
    dispatch('click', { id: value })
}
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "onclick": (handle),
        });
            (value);
        }
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] extends Record<string, never> ? { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] } : Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] & { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] }): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent & { readonly __svn_events: Awaited<ReturnType<typeof $$render_e40e2c10>>['events'] } = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

