// === input.svelte ===
// generated by svelte-check-native; do not edit
import { createEventDispatcher } from 'svelte'
async function $$render_699ff1eb() {
    type $$ComponentProps = { value: number };
    type $$Events = { click: { id: number } };

// Real `createEventDispatcher()` call — must disqualify the
// `__sveltets_2_fn_component` default-export shape and route
// through the iso-component interface so child events surface
// at consumer sites.
                                              

const dispatch = createEventDispatcher<{ click: { id: number } }>()

let { value }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props()

function handle() {
    dispatch('click', { id: value })
}
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "onclick": (handle),
        });
            (value);
        }
    });
    void value;
    void handle;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [K in keyof $$Events]: CustomEvent<$$Events[K]> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_699ff1eb;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_699ff1eb>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_699ff1eb>>['props'], Awaited<ReturnType<typeof $$render_699ff1eb>>['events'], Awaited<ReturnType<typeof $$render_699ff1eb>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_699ff1eb>>['bindings'] } & Awaited<ReturnType<typeof $$render_699ff1eb>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_699ff1eb>>['props']): Awaited<ReturnType<typeof $$render_699ff1eb>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_699ff1eb>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

