// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ed2b916f() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        void ({type: "radio", value: "Plain"} satisfies Partial<__SvnComponentProps<typeof Component>>);
    }
    void __svn_tpl_check;
}
$$render_ed2b916f;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

