// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0de4bcd9() {

const obj = {
    a: 1,
    b: 2,
    nested: {
        c: 3,
        d: 4,
    },
};

       const {
    a, b, nested: { c, d: g }
} = obj;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    void c;
    void g;
    return { props: /** @type {any} */({}) };
}
$$render_0de4bcd9;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0de4bcd9>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

