// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    const store1 = ''/*svn:ignore_start*/;let $store1 = __svn_store_get(store1);/*svn:ignore_end*/;

    if (store1)
        $store1
    else if (store1)
        $store1
    else
        $store
    if (store1)
        $store1 = 1
    if (store1)
        $store1.x = 1

    for (let i=0; i < 1; i++)
        $store1

    for (const a of b)
        $store1

    for (const a in b)
        $store1

    while (true)
        $store1
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {Record<string, never>} */ ({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

