// === input.svelte ===
// generated by svelte-check-native; do not edit
  type Shape =
    | { kind: 'circle'; radius: number }
    | { kind: 'square'; side: number }
async function $$render_c6382cf7() {
    type $$ComponentProps = { shape: Shape };
    type $$Events = {};

              
                                        
                                      

  let { shape }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props()
    ;(async () => {
        // template type-check body (incremental)
        const k = shape.kind;
        void k;
        { svelteHTML.createElement("p", {});             (k);
        }
        if ((shape.kind === 'circle')) {
            void [shape.kind];
            { svelteHTML.createElement("p", {});                 (shape.radius);
            }
        } else if ((shape.kind === 'square')) {
            void [shape.kind];
            { svelteHTML.createElement("p", {});                 (shape.side);
            }
        }
        const [first, { kind: k2 }, ...rest] = [shape, shape];
        void first;
        void k2;
        void rest;
        { svelteHTML.createElement("p", {});             (first.kind);
            (k2);
            (rest.length);
        }
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_c6382cf7;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_c6382cf7>>['props'],
    Awaited<ReturnType<typeof $$render_c6382cf7>>['exports'],
    Awaited<ReturnType<typeof $$render_c6382cf7>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

