// === input.svelte ===
// generated by svelte-check-native; do not edit
  type Shape =
    | { kind: 'circle'; radius: number }
    | { kind: 'square'; side: number }
function $$render_e40e2c10() {
    type $$ComponentProps = { shape: Shape };

              
                                        
                                      

  let { shape }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props()
    ;(async () => {
        // template type-check body (incremental)
        const k = shape.kind;
        { svelteHTML.createElement("p", {});             (k);
        }
        if ((shape.kind === 'circle')) {
            { svelteHTML.createElement("p", {});                 (shape.radius);
            }
        } else if ((shape.kind === 'square')) {
            { svelteHTML.createElement("p", {});                 (shape.side);
            }
        }
        const [first, { kind: k2 }, ...rest] = [shape, shape];
        { svelteHTML.createElement("p", {});             (first.kind);
            (k2);
            (rest.length);
        }
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_e40e2c10;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_e40e2c10>>['props'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

