// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_bdea4648() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if ((hello)) {
            void [hello];
            {
                const hello: any = undefined;
                /*svn_I*/(hello);
                void hello;
            }
            /*svn_I*/(hello);
            {
                const foo: any = undefined;
                const hello = foo;
                void hello;
                /*svn_I*/(hello);
                void foo;
            }
            /*svn_I*/(hello);
            {
                const hi: any = undefined;
                /*svn_I*/(hello);
                void hi;
            }
            {
                const hello: any = undefined;
                /*svn_I*/(hello);
                void hello;
            }
            {
                const hello: any = undefined;
                /*svn_I*/(hello);
                if ((hello)) {
                    void [hello];
                    /*svn_I*/(hello);
                    /*svn_I*/(hello);
                    {
                        const hello: any = undefined;
                        /*svn_I*/(hello);
                        void hello;
                    }
                    {
                        const hello: any = undefined;
                        if ((hello)) {
                            void [hello];
                            /*svn_I*/(hello);
                        }
                        void hello;
                    }
                    {
                        const foo: any = undefined;
                        const hello = foo;
                        void hello;
                        if ((hello)) {
                            void [hello];
                            /*svn_I*/(hello);
                        }
                        void foo;
                    }
                }
                void hello;
            }
            if ((hi && bye)) {
                void [hi, bye];
                {
                    const bye: any = undefined;
                    /*svn_I*/(bye);
                    void bye;
                }
                {
                    const hello: any = undefined;
                    if ((hello)) {
                        void [hello];
                        /*svn_I*/(hello);
                    }
                    void hello;
                }
            } else if ((cool)) {
                void [cool];
                {
                    const cool: any = undefined;
                    if ((cool)) {
                        void [cool];
                        /*svn_I*/(cool);
                    }
                    void cool;
                }
                {
                    const cool: any = undefined;
                    void cool;
                }
                {
                    const cool: any = undefined;
                    /*svn_I*/(cool);
                    void cool;
                }
            } else {
                {
                    const hello: any = undefined;
                    if ((hello)) {
                        void [hello];
                        /*svn_I*/(hello);
                    }
                    void hello;
                }
            }
        }
        if ((cool)) {
            void [cool];
            /*svn_I*/(cool);
        } else if ((hello)) {
            void [hello];
            /*svn_I*/(hello);
        }
        {
            const cool: any = undefined;
            if ((cool)) {
                void [cool];
                /*svn_I*/(cool);
            } else if ((hello)) {
                void [hello];
                /*svn_I*/(hello);
            }
            void cool;
        }
        {
            const cool: any = undefined;
            if ((cool)) {
                void [cool];
                /*svn_I*/(cool);
            } else if ((hello)) {
                void [hello];
                /*svn_I*/(hello);
            }
            void cool;
        }
    }
    void __svn_tpl_check;
}
$$render_bdea4648;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

