// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7fa5ec53() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if ((name == "world")) {
            void [name];
            if ((bla)) {
                void [bla];
            }
            if ((bla)) {
                void [bla];
            }
        } else if ((foo)) {
            void [foo];
            if ((bla)) {
                void [bla];
            } else {
            }
        } else {
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            }
        }
        if ((name == "world")) {
            void [name];
            if ((bla)) {
                void [bla];
            }
            if ((bla)) {
                void [bla];
            } else {
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            } else {
            }
        } else if ((foo)) {
            void [foo];
            if ((bla)) {
                void [bla];
            }
            if ((bla)) {
                void [bla];
            } else {
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            } else {
            }
        } else {
            if ((bla)) {
                void [bla];
            }
            if ((bla)) {
                void [bla];
            } else {
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            }
            if ((bla)) {
                void [bla];
            } else if ((blubb)) {
                void [blubb];
            } else {
            }
        }
    }
    void __svn_tpl_check;
}
$$render_7fa5ec53;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

