// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_54ce17a1() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_54ce17a1;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

