// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9672a3be() {

	       let foo: number = undefined
foo = undefined as any;
	       let foo2 = undefined
	let clazz!: string
	                         
	       const bar: string = ''
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void foo;
    void foo2;
    void clazz;
    void bar;
}
$$render_9672a3be;
declare const __svn_component_default: import('svelte').Component<{ foo?: number; foo2?: any; class: string; bar?: string; } & __SvnSvelte4PropsWiden<{ foo?: number; foo2?: any; class: string; bar?: string; }>, { foo: number; foo2: any; bar: string; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo?: number; foo2?: any; class: string; bar?: string; } & __SvnSvelte4PropsWiden<{ foo?: number; foo2?: any; class: string; bar?: string; }>> & { foo: number; foo2: any; bar: string; };
export default __svn_component_default;

