// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { createEventDispatcher, abc } from "svelte";
async function $$render_7551b519() {

                                                        

    const notDispatch = abc();
    const dispatch1 = createEventDispatcher();
    const dispatch2 = createEventDispatcher();

    dispatch1('hi', true);
    dispatch2('bye', true);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_7551b519;
declare const __svn_component_default: import('svelte').Component<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
export default __svn_component_default;

