// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_fa6a60ec() {

  let { count } = __svn_invalidate(() => ($data)); void count;
  let { count2 } = __svn_invalidate(() => ($data)); void count2;
  let count3 = /** @type {any} */ (null);
  ;() => { $: ({ count3 } = $data) };
  let bla4 = /** @type {any} */ (null);
  let bla5; ({ bla4, bla5 } = __svn_invalidate(() => ($data))); void bla4; void bla5;

  let [ count ] = __svn_invalidate(() => ($data)); void count;
  let [ count2 ] = __svn_invalidate(() => ($data)); void count2;
  let count3 = /** @type {any} */ (null);
  ;() => { $: ([ count3 ] = $data) };
  let bla4 = /** @type {any} */ (null);
  let bla5; ([ bla4, bla5 ] = __svn_invalidate(() => ($data))); void bla4; void bla5;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_fa6a60ec;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_fa6a60ec>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_fa6a60ec>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

