// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    const store1 = '', store2 = ''/*svn:ignore_start*/;let $store1 = __svn_store_get(store1);;let $store2 = __svn_store_get(store2);/*svn:ignore_end*/;
    const { store3, store4 } = '', [ store5, store6 ] = ''/*svn:ignore_start*/;let $store3 = __svn_store_get(store3);;let $store4 = __svn_store_get(store4);;let $store5 = __svn_store_get(store5);;let $store6 = __svn_store_get(store6);/*svn:ignore_end*/;
    let {store7, store8} = __svn_invalidate(() => (''))/*svn:ignore_start*/;let $store7 = __svn_store_get(store7);;let $store8 = __svn_store_get(store8);/*svn:ignore_end*/;
    let [store9, store10] = __svn_invalidate(() => (''))/*svn:ignore_start*/;let $store9 = __svn_store_get(store9);;let $store10 = __svn_store_get(store10);/*svn:ignore_end*/;
    ;(async () => {
        // template type-check body (incremental)
        ($store1);
        ($store2);
        ($store3);
        ($store4);
        ($store5);
        ($store6);
        ($store7);
        ($store8);
        ($store9);
        ($store10);
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

