// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_cf56d9b2<A, B extends keyof A, C extends boolean>() {

    /** @type {{ a: A; b: B; c: C }} */
    const { a, b, c } = $props();

           function getA() {
        return a;
    }
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    void getA;
}
$$render_cf56d9b2;
declare const __svn_component_default: <A, B extends keyof A, C extends boolean>(__anchor: any, props: Partial<Record<string, any>>) => { getA: () => void; };
declare type __svn_component_default<A, B extends keyof A, C extends boolean> = import('svelte').SvelteComponent<Record<string, any>> & { getA: () => void; };
export default __svn_component_default;

