// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10<A, B extends keyof A, C extends boolean>() {

    /** @type {{ a: A; b: B; c: C }} */
    const { a, b, c } = $props();

           function getA() {
        return a;
    }
    ;(async () => {
        // template type-check body (incremental)
    });
    void getA;
    return { props: /** @type {{ a: A; b: B; c: C }} */({}), events: /** @type {{}} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ getA: typeof getA; }} */ ({}) };
}
$$render_e40e2c10;
/** @type {import('svelte').Component<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

