// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{a: any, b: any, c: any}} $$ComponentProps */
async function $$render_e40e2c10<A, B extends keyof A, C extends boolean>() {

    /** @type {{ a: A; b: B; c: C }} */
    const { a, b, c } = $props();

           function getA() {
        return a;
    }
    ;(async () => {
        // template type-check body (incremental)
    });
    void getA;
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ getA: typeof getA; }} */ ({}) };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

