// === input.svelte ===
// generated by svelte-check-native; do not edit

  // ...
/** @typedef {{icon: any}} $$ComponentProps */
async function $$render_559c7716() {
    /** @type {any} */ const iconSnippet = /** @type {any} */ (undefined);
    void iconSnippet;

  const { icon: Icon } = $props();
    ;(async () => {
        // template type-check body (incremental)
        {
            const iconSnippet = () => {
                {
                    const __svn_C_76 = __svn_ensure_component(Icon);
                    new __svn_C_76({ target: __svn_any(), props: {"size": (16)} });
                }
                return null;
            };
            void iconSnippet;
            (iconSnippet());
        }
    });
    return { props: /** @type {$$ComponentProps} */({}) };
}
$$render_559c7716;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_559c7716>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

