// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0e0b7d84() {

    /**
     * DOCS!
     */
           let a!: any;
    /**
     * not this
     */
    /**
     * MORE DOCS!
     */
           let b!: any;
           let c!: any;
    /**
     * d
     */
           let d,
    /**
     * e
     */
     e;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    void d;
    void e;
}
$$render_0e0b7d84;
declare const __svn_component_default: import('svelte').Component<{ a: any; b: any; c: any; d: any; e: any; } & __SvnSvelte4PropsWiden<{ a: any; b: any; c: any; d: any; e: any; }>, { a: any; b: any; c: any; d: any; e: any; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ a: any; b: any; c: any; d: any; e: any; } & __SvnSvelte4PropsWiden<{ a: any; b: any; c: any; d: any; e: any; }>> & { a: any; b: any; c: any; d: any; e: any; };
export default __svn_component_default;

