// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    /**
     * DOCS!
     */
           let a/*svn:ignore_start*/;a = __svn_any(a);/*svn:ignore_end*/;
    /**
     * not this
     */
    /**
     * MORE DOCS!
     */
           let b/*svn:ignore_start*/;b = __svn_any(b);/*svn:ignore_end*/;
           let c/*svn:ignore_start*/;c = __svn_any(c);/*svn:ignore_end*/;
    /**
     * d
     */
           let d,
    /**
     * e
     */
     e/*svn:ignore_start*/;d = __svn_any(d);/*svn:ignore_end*//*svn:ignore_start*/;e = __svn_any(e);/*svn:ignore_end*/;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    void c;
    void d;
    void e;
    return { props: /** @type {{ a: any; b: any; c: any; d: any; e: any; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

