// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0e0b7d84() {

    /**
     * DOCS!
     */
           let a = /** @type {any} */ (null);
    /**
     * not this
     */
    /**
     * MORE DOCS!
     */
           let b = /** @type {any} */ (null);
           let c = /** @type {any} */ (null);
    /**
     * d
     */
           let d,
    /**
     * e
     */
     e;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    void c;
    void d;
    void e;
    return { props: /** @type {{ a: any; b: any; c: any; d: any; e: any; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ a: typeof a; b: typeof b; c: typeof c; d: typeof d; e: typeof e; }} */ ({}) };
}
$$render_0e0b7d84;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0e0b7d84>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0e0b7d84>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

