// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a41f16c2() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {});         }
        ;(async () => {
            const $$_await = await (Promise.resolve(0)); const n = $$_await;
            (n);
            void n;
        });
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_a41f16c2;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a41f16c2>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

