// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4aa1e856() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("input", {
            "id": `dom-input`,
            "type": `radio`,
            "value": `dom`,
        });
            $compile_options.generate = __svn_any(null);
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_4aa1e856;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4aa1e856>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

