// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2f16c479() {

let { a } = __svn_invalidate(() => ({ a: '' })); void a;
let { b: d } = __svn_invalidate(() => ({ b: '' })); void d;
let { c: { length } } = __svn_invalidate(() => ({ c: '' })); void length;
let { ...e } = __svn_invalidate(() => ({ f: ''})); void e;
let { f } = __svn_invalidate(() => ({ f: ''})); void f;
let { b: g = 1} = __svn_invalidate(() => ({ b: 1 })); void g;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_2f16c479;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

