// === input.svelte ===
// generated by svelte-check-native; do not edit

    enum A {
    }
declare const Abc: { [key: string]: any } & ((...args: any[]) => any);
interface A {
    Abc: number
}
async function $$render_a0aab525() {

             
               
 

let {Abc}: A = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void Abc;
}
$$render_a0aab525;
declare const __svn_component_default: import('svelte').Component<A>;
export default __svn_component_default;

