// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e05c0865() {

    let world = "world";
           let name = world;
    ;(async () => {
        // template type-check body (incremental)
    });
    void name;
    return { props: /** @type {{ name?: typeof name; }} */({}) };
}
$$render_e05c0865;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e05c0865>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

