// === input.svelte ===
// generated by svelte-check-native; do not edit

declare const Abc: { [key: string]: any } & ((...args: any[]) => any);
import { store } from './foo';
interface A {
    Abc: typeof store
}
async function $$render_e40e2c10() {
    type $$Events = {};

                              
             
                     
 

let {Abc}: A = $props()
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (A), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_e40e2c10;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_e40e2c10>>['props'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

