// === input.svelte ===
// generated by svelte-check-native; do not edit

    export function preload() {}
    let b = 5;
async function $$render_39303eb1() {

           let world = "name"
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void world;
}
$$render_39303eb1;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

