// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e34b808e() {
    ;(async () => {
        // template type-check body (incremental)
        {
            const error = __svn_any();
            void error;
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_e34b808e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e34b808e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

