// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e34b808e() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const error: any = undefined;
            void error;
        }
    }
    void __svn_tpl_check;
}
$$render_e34b808e;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

