// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_71583bab() {

           const name: string = "world";
           const SOME = 1, CONSTANT = 2;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void name;
    void SOME;
    void CONSTANT;
}
$$render_71583bab;
declare const __svn_component_default: import('svelte').Component<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>, { name: string; SOME: any; CONSTANT: any; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>> & { name: string; SOME: any; CONSTANT: any; };
export default __svn_component_default;

