// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_03ce1d4e() {


let b = __svn_invalidate(() => ({ a: 1 }['a'])); void b;
let c = __svn_invalidate(() => ({ a: { b: 1} }['a']['b'])); void c;
let d = __svn_invalidate(() => ({ a: { b: 1} }['a']['b']?.['c'])); void d;
let e = __svn_invalidate(() => ({a: 1} ?? { a: 1 })); void e;
let f = __svn_invalidate(() => ({a: 1}[c] ? '' : '1')); void f;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_03ce1d4e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_03ce1d4e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

