// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("input", {
            "type": `text`,
            "bind:value": (value),
        });
            /*svn:ignore_start*/void (() => { value = __svn_any(null); });/*svn:ignore_end*/
        }
        { svelteHTML.createElement("input", {
            "type": `checkbox`,
            "bind:checked": (checked),
        });
            /*svn:ignore_start*/void (() => { checked = __svn_any(null); });/*svn:ignore_end*/
        }
        {
            const __svn_C_49 = __svn_ensure_component(Input);
            const __svn_inst_49 = new __svn_C_49({ target: __svn_any(), props: {"type": "text", value} });
            /*svn:ignore_start*/void (() => { value = __svn_any(null); });/*svn:ignore_end*/
            __svn_inst_49.$$bindings = 'value';
        }
        {
            const __svn_C_6a = __svn_ensure_component(Input);
            const __svn_inst_6a = new __svn_C_6a({ target: __svn_any(), props: {"type": "checkbox", checked} });
            /*svn:ignore_start*/void (() => { checked = __svn_any(null); });/*svn:ignore_end*/
            __svn_inst_6a.$$bindings = 'checked';
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

