// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6ce80dfb() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        void ({type: "text"} satisfies Partial<__SvnComponentProps<typeof Input>>);
        void ({type: "checkbox"} satisfies Partial<__SvnComponentProps<typeof Input>>);
    }
    void __svn_tpl_check;
}
$$render_6ce80dfb;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

