// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6ce80dfb() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        value = null as any as string;
        checked = null as any as HTMLInputElement['checked'];
        {
            const __svn_C_49 = __svn_ensure_component(Input);
            new __svn_C_49({ target: __svn_any(), props: {type: "text", value} });
        }
        {
            const __svn_C_6a = __svn_ensure_component(Input);
            new __svn_C_6a({ target: __svn_any(), props: {type: "checkbox", checked} });
        }
    }
    void __svn_tpl_check;
}
$$render_6ce80dfb;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

