// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{b: any}} $$ComponentProps */
function $$render_e40e2c10<T>() {
    const foo = (bar) => { async () => {
        (bar);
        };
        return null;
    };
    void foo;

  /** @type {{ b: T }}*/
  let { b } = $props();
  let rect;
    ;(async () => {
        // template type-check body (incremental)
        const __svn_create_slot = __svn_create_create_slot();
        { svelteHTML.createElement("div", {});             rect = /*svn:ignore_start*//** @type {DOMRectReadOnly} */ (null)/*svn:ignore_end*/;
        }
        {
            __svn_create_slot("default", {  });
        }
    });
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': {  } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {__SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

