// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{b: any}} $$ComponentProps */
async function $$render_edb4eb12<T>() {

  /** @type {{ b: T }}*/
  let { b } = $props();
  let rect = /** @type {any} */ (null);
    ;(async () => {
        // template type-check body (incremental)
        {
            const foo = undefined;
            void foo;
            {
                void ((bar: any) => {
                    (bar);
                    void bar;
                });
            }
            { svelteHTML.createElement("div", {});                 rect = /** @type {DOMRectReadOnly} */ (null);
            }
        }
    });
    void b;
    void rect;
    return { props: /** @type {$$ComponentProps} */({}) };
}
$$render_edb4eb12;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_edb4eb12>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

