// === input.svelte ===
// generated by svelte-check-native; do not edit
  import { writable } from 'svelte/store';
function $$render_e40e2c10() {

                                          
  const count = writable(0)/*svn:ignore_start*/;let $count = __svn_store_get(count);/*svn:ignore_end*/;
  let myvar = 42 // to show that this is different from ++ or --
  const handler1 = () => $count += myvar
  const handler2 = () => $count -= myvar
  const handler3 = () => $count *= myvar
  const handler4 = () => $count /= myvar
  const handler5 = () => $count **= myvar
  const handler6 = () => $count %= myvar
  const handler7 = () => $count <<= myvar
  const handler8 = () => $count >>= myvar
  const handler9 = () => $count >>>= myvar
  const handler10 = () => $count &= myvar
  const handler11 = () => $count ^= myvar
  const handler12 = () => $count |= myvar
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "on:click": (() => $count += myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count -= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count *= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count /= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count **= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count %= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count <<= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count >>= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count >>>= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count &= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count ^= myvar),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => $count |= myvar),
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

