// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0e8c17e8() {

	// no imports — every dotted tag below is unresolved
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_56 = __svn_ensure_component(Text.Body);
            new __svn_C_56({ target: __svn_any(), props: {} });
        }
        {
            const __svn_C_64 = __svn_ensure_component(Dialog.Content);
            new __svn_C_64({ target: __svn_any(), props: {} });
        }
        {
            const __svn_C_77 = __svn_ensure_component(Select.Trigger);
            new __svn_C_77({ target: __svn_any(), props: {} });
        }
        {
            const __svn_C_8a = __svn_ensure_component(ZzzFakeNamespace.Member);
            new __svn_C_8a({ target: __svn_any(), props: {} });
        }
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_0e8c17e8;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_0e8c17e8>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_0e8c17e8>>['props'], Awaited<ReturnType<typeof $$render_0e8c17e8>>['events'], Awaited<ReturnType<typeof $$render_0e8c17e8>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_0e8c17e8>>['bindings'] } & Awaited<ReturnType<typeof $$render_0e8c17e8>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_0e8c17e8>>['props']): Awaited<ReturnType<typeof $$render_0e8c17e8>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_0e8c17e8>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

