// === input.svelte ===
// generated by svelte-check-native; do not edit

    export const foo = 'foo';
  import { createEventDispatcher } from 'svelte';
async function $$render_87d6d062() {

                                                 

  /** @type {boolean} */
         let bar = /** @type {any} */ (null);
         let foobar = '';

  const dispatch = createEventDispatcher();
  dispatch('hi');
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "on:click": undefined,
        });
        }
    });
    void bar;
    void foobar;
    return { props: /** @type {{ bar: any; foobar?: typeof foobar; }} */({}) };
}
$$render_87d6d062;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_87d6d062>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

