// === input.svelte ===
// generated by svelte-check-native; do not edit
interface WithItems<T> {
        items: T[];
    }
interface Props extends WithItems<T> {
		prop: T;
	}
async function $$render_f45a6d7c<T extends { a: string }>() {

                            
                   
     

	                                      
          
  ;
	let { prop }: Props = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void prop;
}
$$render_f45a6d7c;
declare const __svn_component_default: import('svelte').Component<Props>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props>;
export default __svn_component_default;

