// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const a: { [key: string]: any } & ((...args: any[]) => any);
interface A {
    Abc: typeof a
}
interface Abc {
    foo: A.Abc
}
async function $$render_42b49b9a() {

    const a = 1;

             
                 
 

               
              
 

let {}: Abc = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    return { props: undefined as any as (Abc), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_42b49b9a;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_42b49b9a>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_42b49b9a>>['props'], Awaited<ReturnType<typeof $$render_42b49b9a>>['events'], Awaited<ReturnType<typeof $$render_42b49b9a>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_42b49b9a>>['bindings'] } & Awaited<ReturnType<typeof $$render_42b49b9a>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_42b49b9a>>['props']): Awaited<ReturnType<typeof $$render_42b49b9a>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_42b49b9a>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

