// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a8746c92() {
    let $$restProps = /** @type {Record<string, any>} */ ({});
    void $$restProps;
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             ($$restProps['name']);
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_a8746c92;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a8746c92>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

