// === input.svelte ===
// generated by svelte-check-native; do not edit
	import { readable } from 'svelte/store';
async function $$render_53b84942() {
    let $store!: __SvnStoreValue<typeof store>;

	                                        
	const store = readable(Promise.resolve('test'), () => {});
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const data: any = undefined;
            (data);
            void data;
        }
    }
    void __svn_tpl_check;
    void $store;
    void store;
}
$$render_53b84942;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

