// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e9cac3f6() {
    ;(async () => {
        // template type-check body (incremental)
        (''.);
    });
    return { props: /** @type {any} */({}) };
}
$$render_e9cac3f6;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e9cac3f6>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

