// === input.svelte ===
// generated by svelte-check-native; do not edit
    type Box = { width: number; height: number };
async function $$render_1a406b20() {
    type $$Events = {};

                                                 

    let boxes: Box[] = [
        { width: 3, height: 4 },
        { width: 5, height: 7 }
    ];
    ;(async () => {
        // template type-check body (incremental)
        for (const box of __svn_each_items(boxes)) {
            {
                const foo = (): any => {
                    const area = await 'snippet';
                    void area;
                    (area);
                    return null as any;
                };
                void foo;
                const area = box.width * box.height;
                void area;
                let label = $state(await `${area} square pixels`);
                void label;
                { svelteHTML.createElement("p", {});                     (label);
                }
                { svelteHTML.createElement("div", {});                     const area = await 'nested';
                    void area;
                    (area);
                }
            }
            void box;
        }
    });
    void boxes;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_1a406b20;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_1a406b20>>['props'],
    Awaited<ReturnType<typeof $$render_1a406b20>>['exports'],
    Awaited<ReturnType<typeof $$render_1a406b20>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

