// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_86beef21() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             { svelteHTML.createElement("div", {});             }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_86beef21;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_86beef21>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

