// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d2ad7865() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("input", {
            "type": `radio`,
            "value": `Plain`,
        });
            element = /** @type {HTMLElementTagNameMap['input']} */ (null);
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_d2ad7865;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d2ad7865>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

