// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_31ea5646() {

           let { a = '', b } = c;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    return { props: /** @type {any} */({}) };
}
$$render_31ea5646;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_31ea5646>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

