// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_06b566ea() {
    /** @type {__SvnStoreValue<typeof store>} */
    let $store = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store1>} */
    let $store1 = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof store2>} */
    let $store2 = /** @type {any} */ (/** @type {any} */ (null));

    let store = __svn_invalidate(() => (fromSomewhere())); void store;
    let { store1, noStore } = __svn_invalidate(() => (fromSomewhere())); void store1; void noStore;
    let [ store2, noStore ] = __svn_invalidate(() => (fromSomewhere())); void store2; void noStore;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             ($store);
        }
        { svelteHTML.createElement("p", {});             ($store1);
        }
        { svelteHTML.createElement("p", {});             ($store2);
        }
    }
    void __svn_tpl_check;
    void $store;
    void store;
    void $store1;
    void store1;
    void $store2;
    void store2;
    return { props: /** @type {any} */({}) };
}
$$render_06b566ea;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_06b566ea>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

