// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_40b54088() {

           let foo!:string;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void foo;
    return { props: undefined as any as ({ foo: string; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ foo: string; }) };
}
$$render_40b54088;
declare const __svn_component_default: import('svelte').Component<{ foo: string; }, { foo: string; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo: string; }> & { foo: string; };
export default __svn_component_default;

