// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_40b54088() {

           let foo!:string;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void foo;
}
$$render_40b54088;
declare const __svn_component_default: import('svelte').Component<{ foo: string; }, { foo: string; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo: string; }> & { foo: string; };
export default __svn_component_default;

