// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_aad889ba() {

    let callback!: (id: string) => void;
    let callback2!: {( id: string): void}
    let constructor1!: new (id: string) => { id: string };
    let obj!: { hi(id: string): void }

    let { id } = __svn_invalidate(() => ({ id: '' })); void id;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_aad889ba;
declare const __svn_component_default: import('svelte').Component<Awaited<ReturnType<typeof $$render_aad889ba>>['props']>;
declare type __svn_component_default = import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_aad889ba>>['props']>;
export default __svn_component_default;

