// === input.svelte ===
// generated by svelte-check-native; do not edit

    let module = true;
import { imported } from './x';
async function $$render_3d709d05() {

                                   
    let foo = true;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        let bar: any = undefined;
        void bar;
        {
            const hoistable1: any = undefined;
            void hoistable1;
            const hoistable2: any = undefined;
            void hoistable2;
            const hoistable3: any = undefined;
            void hoistable3;
            const hoistable4: any = undefined;
            void hoistable4;
            const hoistable5: any = undefined;
            void hoistable5;
            const hoistable6: any = undefined;
            void hoistable6;
            const hoistable7: any = undefined;
            void hoistable7;
            const hoistable8: any = undefined;
            void hoistable8;
            const hoistable9: any = undefined;
            void hoistable9;
            const hoistable10: any = undefined;
            void hoistable10;
            const not_hoistable: any = undefined;
            void not_hoistable;
            {
                const bar: any = undefined;
                void bar;
            }
            {
                const bar: any = undefined;
                void bar;
            }
            {
                const foo: any = undefined;
                void foo;
            }
            {
                const props: any = undefined;
                void props;
            }
            {
                const foo: any = undefined;
                void foo;
            }
        }
    }
    void __svn_tpl_check;
    void foo;
    void module;
    void imported;
}
$$render_3d709d05;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

