// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b9dbbb3b() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            const __svn_inst_0 = new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, a } = __svn_inst_0.$$slot_def["b"]; $$_$$;
                { svelteHTML.createElement("div", {});                     {
                        let a: any;
                        void a;
                    }
                }
            }
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_b9dbbb3b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b9dbbb3b>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

