// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_cae62ddc() {
    type $$ComponentProps = {a: any, b?: any, c?: any};
    type $$Events = {};

    let { a, b = $bindable(), c = $bindable(0) as number }: $$ComponentProps = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    void b;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings('b'), exports: undefined as any as ({}) };
}
$$render_cae62ddc;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_cae62ddc>>['props'],
    Awaited<ReturnType<typeof $$render_cae62ddc>>['exports'],
    Awaited<ReturnType<typeof $$render_cae62ddc>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

