// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{props: any}} $$ComponentProps */
function $$render_e40e2c10() {

    let { props } = $props();
    let state = $state(0);
    let derived = $derived(state * 2);
    ;(async () => {
        // template type-check body (incremental)
        state;
        derived;
    });
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {import('svelte').Component<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

