// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_314cb617() {
    ;(async () => {
        // template type-check body (incremental)
        (myfile);
        (myfile);
        (someOtherFile);
        (myfile);
        (someOtherFile);
        (someThirdFile);
    });
    return { props: /** @type {any} */({}) };
}
$$render_314cb617;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_314cb617>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

