// === input.svelte ===
// generated by svelte-check-native; do not edit
    import type { Action } from 'svelte/action';
async function $$render_a1303664() {

                                                

    const myAction: Action<HTMLElement, undefined, { 'on:custom': (e: CustomEvent) => void }> = (node) => {
        return {};
    };
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        let __svn_action_attrs_0: any = {};
        void __svn_action_attrs_0;
    }
    void __svn_tpl_check;
    void myAction;
}
$$render_a1303664;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

