// === input.svelte ===
// generated by svelte-check-native; do not edit
    import type { Action } from 'svelte/action';
async function $$render_a1303664() {

                                                

    const myAction: Action<HTMLElement, undefined, { 'on:custom': (e: CustomEvent) => void }> = (node) => {
        return {};
    };
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        let __svn_action_attrs_0: any = {};
        void __svn_action_attrs_0;
            const __svn_action_0 = __svn_ensure_action(myAction(__svn_map_element_tag('div')));
        { svelteHTML.createElement("div", __svn_union(__svn_action_0), {});             void __svn_action_0;
        }
    }
    void __svn_tpl_check;
    void myAction;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_a1303664;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_a1303664>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_a1303664>>['props'], Awaited<ReturnType<typeof $$render_a1303664>>['events'], Awaited<ReturnType<typeof $$render_a1303664>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_a1303664>>['bindings'] } & Awaited<ReturnType<typeof $$render_a1303664>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_a1303664>>['props']): Awaited<ReturnType<typeof $$render_a1303664>>['exports'];
    z_$$bindings?: Awaited<ReturnType<typeof $$render_a1303664>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

