// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ba14d1a0() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:body", {
            "on:click": undefined,
        });
        }
        { svelteHTML.createElement("svelte:window", {
            "on:resize": undefined,
        });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_ba14d1a0;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ba14d1a0>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

