// === input.svelte ===
// generated by svelte-check-native; do not edit

    namespace A {
        export type Abd = number
    }
interface A {
    Abc: number
}
async function $$render_3dcf5b80() {

             
               
 

let {Abc}: A = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void Abc;
}
$$render_3dcf5b80;
declare const __svn_component_default: import('svelte').Component<A>;
declare type __svn_component_default = import('svelte').SvelteComponent<A>;
export default __svn_component_default;

