// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const destructured: { [key: string]: any } & ((...args: any[]) => any);
declare const prop: { [key: string]: any } & ((...args: any[]) => any);
	type Props = {
		prop: typeof destructured;
	};
async function $$render_94c42fc9() {

	let { destructured } = {};
	              
                            
   
	let { prop }: Props = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    void prop;
    return { props: undefined as any as (Props), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_94c42fc9;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_94c42fc9>>['props'],
    Awaited<ReturnType<typeof $$render_94c42fc9>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

