// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_13e7324c() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             $compile_options = /** @type {HTMLElement['offsetHeight']} */ (null);
        }
        { svelteHTML.createElement("div", {});             $compile_options.foo = /** @type {HTMLElement['offsetHeight']} */ (null);
        }
        { svelteHTML.createElement("div", {});             $compile_options = /** @type {HTMLElementTagNameMap['div']} */ (null);
        }
        { svelteHTML.createElement("div", {});             $compile_options.foo = /** @type {HTMLElementTagNameMap['div']} */ (null);
        }
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("div", {});         }
    }
    return { props: /** @type {any} */({}) };
}
$$render_13e7324c;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_13e7324c>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

