// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1b9e86d7() {

    let name1 = "world"
    let name2

    let rename1 = '';
    let rename2!: any;

    class Foo {}
    function bar() {}
    const baz = '';

    class RenameFoo {}
    function renamebar() {}
    const renamebaz = '';

                                                                                                                                                                
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void name1;
    void name2;
    void rename1;
    void rename2;
    void Foo;
    void bar;
    void baz;
    void RenameFoo;
    void renamebar;
    void renamebaz;
}
$$render_1b9e86d7;
declare const __svn_component_default: import('svelte').Component<{ name1?: any; name2: any; renamed1?: any; renamed2: any; Foo: any; bar: any; baz?: any; RenamedFoo: any; renamedbar: any; renamedbaz?: any; } & __SvnSvelte4PropsWiden<{ name1?: any; name2: any; renamed1?: any; renamed2: any; Foo: any; bar: any; baz?: any; RenamedFoo: any; renamedbar: any; renamedbaz?: any; }>>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ name1?: any; name2: any; renamed1?: any; renamed2: any; Foo: any; bar: any; baz?: any; RenamedFoo: any; renamedbar: any; renamedbaz?: any; } & __SvnSvelte4PropsWiden<{ name1?: any; name2: any; renamed1?: any; renamed2: any; Foo: any; bar: any; baz?: any; RenamedFoo: any; renamedbar: any; renamedbaz?: any; }>>;
export default __svn_component_default;

