// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1110d804() {
    ;(async () => {
        // template type-check body (incremental)
        if ((true)) {
            {
                const __svn_C_b = __svn_ensure_component(__svn_self_default);
                new __svn_C_b({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            }
        }
        {
            const __svn_C_4b = __svn_ensure_component(testComponent);
            new __svn_C_4b({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_1110d804;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_1110d804>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

