// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1110d804() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if ((true)) {
            {
                let prop: any;
                void prop;
            }
        }
        {
            let prop: any;
            void prop;
        }
    }
    void __svn_tpl_check;
}
$$render_1110d804;
declare const __svn_component_default: import('svelte').Component<Partial<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Partial<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>>;
export default __svn_component_default;

