// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1110d804() {
    ;(async () => {
        // template type-check body (incremental)
        if ((true)) {
            {
                const __svn_C_b = __svn_ensure_component(__svn_self_default);
                const __svn_inst_b = new __svn_C_b({ target: __svn_any(), props: {} });
                {
                    const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, prop } = __svn_inst_b.$$slot_def.default; $$_$$;
                    void prop;
                }
            }
        }
        {
            const __svn_C_4b = __svn_ensure_component(testComponent);
            const __svn_inst_4b = new __svn_C_4b({ target: __svn_any(), props: {} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, prop } = __svn_inst_4b.$$slot_def.default; $$_$$;
                void prop;
            }
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': {  } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_1110d804;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_1110d804>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_1110d804>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

