// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_fdf7f947() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        Component(__svn_any(), {hi: (''?.)});
    }
    void __svn_tpl_check;
}
$$render_fdf7f947;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

