// === +page.svelte ===
// generated by svelte-check-native; do not edit
type $$ComponentProps = { data: import('./$types.js').PageData; form?: import('./$types.js').ActionData; };
async function $$render_4e494ca9() {

    // +page.svelte with an untyped $props() destructure. Our emit
    // recognizes the route-file basename and injects
    // `data: import('./$types.js').PageData` (and for `form`,
    // `import('./$types.js').ActionData`) into the synthesized
    // default-export Props shape. Downstream overlays reading
    // `ComponentProps<typeof Page>` then resolve to the real shape
    // instead of `any`.
    let { data, form }: $$ComponentProps = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (data.title);
        }
        { svelteHTML.createElement("p", {});             (data.count);
        }
        if ((form)) {
            void [form];
            { svelteHTML.createElement("span", {});             }
        }
    }
    void __svn_tpl_check;
    void data;
    void form;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_4e494ca9;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_4e494ca9>>['props'],
    Awaited<ReturnType<typeof $$render_4e494ca9>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

