// === input.svelte ===
// generated by svelte-check-native; do not edit

    import {} from 'svelte'
async function $$render_3a14f9f8() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const foo = undefined;
            void foo;
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_3a14f9f8;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_3a14f9f8>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

