// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e40e2c10() {

    const env: WorkerEnv = { SECRET: 'x' };
    const named: Array<[string, string[]]> = [['a', [env.SECRET]]];
    const ungrouped: string[] = ['u'];

    function build() {
        const sections = named.map(([name, rules]) => ({ name, rules }));
        // `name` infers as `string`, so pushing `null` is a real error.
        if (ungrouped) sections.push({ name: null, rules: ungrouped });
        return sections;
    }

    const out = build();
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             (out.length);
        }
    });
    void out;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props']): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

