// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_27b7be6d() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if (((name1 ?? "bla") == "world")) {
            void [name1];
            { svelteHTML.createElement("h1", {});                 (name2);
            }
        } else if ((name3 ?? "blubb")) {
            void [name3];
            { svelteHTML.createElement("h2", {});                 (name4);
            }
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_27b7be6d;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_27b7be6d>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

