// === input.svelte ===
// generated by svelte-check-native; do not edit
    import type Foo from 'somewhere';
async function $$render_e40e2c10<A, B extends ReferencedByGeneric>() {

                                     
    interface ReferencesGeneric {
        a: A;
    }
    interface ReferencedByGeneric {
        b: true;
        f: Foo;
    }
    
                       
                                            

           let a!: ReferencesGeneric;
           let b!: B;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    return { props: undefined as any as ({ a: ReferencesGeneric; b: B; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ a: ReferencesGeneric; b: B; }) };
}
$$render_e40e2c10;
declare class __svn_Render_e40e2c10<A, B extends ReferencedByGeneric> {
    props(): Awaited<ReturnType<typeof $$render_e40e2c10<A, B>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_e40e2c10<A, B>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_e40e2c10<A, B>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_e40e2c10<A, B>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_e40e2c10<A, B>>>['exports'];
}
interface $$IsomorphicComponent {
    new <A, B extends ReferencedByGeneric>(options: import('svelte').ComponentConstructorOptions<ReturnType<__svn_Render_e40e2c10<A, B>['props']>>): import('svelte').SvelteComponent<ReturnType<__svn_Render_e40e2c10<A, B>['props']>, ReturnType<__svn_Render_e40e2c10<A, B>['events']>, ReturnType<__svn_Render_e40e2c10<A, B>['slots']>> & { $$bindings?: ReturnType<__svn_Render_e40e2c10<A, B>['bindings']> } & ReturnType<__svn_Render_e40e2c10<A, B>['exports']>;
    <A, B extends ReferencedByGeneric>(internal: unknown, props: ReturnType<__svn_Render_e40e2c10<A, B>['props']>): ReturnType<__svn_Render_e40e2c10<A, B>['exports']> & { $set?: any; $on?: any };
    z_$$bindings?: ReturnType<__svn_Render_e40e2c10<any, any>['bindings']>;
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default<A, B extends ReferencedByGeneric> = InstanceType<typeof __svn_component_default<A, B>>;
export default __svn_component_default;

