// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f1e333d8() {
    /** @type {__SvnStoreValue<typeof props>} */
    let $props = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof state>} */
    let $state = /** @type {any} */ (/** @type {any} */ (null));
    /** @type {__SvnStoreValue<typeof derived>} */
    let $derived = /** @type {any} */ (/** @type {any} */ (null));

    const props = null;
    $props;
    const state = null;
    $state;
    const derived = null;
    $derived;
    ;(async () => {
        // template type-check body (incremental)
        (state);
        (derived);
    });
    void $props;
    void props;
    void $state;
    void state;
    void $derived;
    void derived;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_f1e333d8;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f1e333d8>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f1e333d8>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

