// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f1e333d8() {

    const props = null;
    $props;
    const state = null;
    $state;
    const derived = null;
    $derived;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        (state);
        (derived);
    }
    void state;
    void derived;
    return { props: /** @type {any} */({}) };
}
$$render_f1e333d8;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f1e333d8>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

