// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2973d64e() {
    ;(async () => {
        // template type-check body (incremental)
        for (const item of __svn_each_items(list)) {
            { svelteHTML.createElement("li", {});                 (flip(__svn_map_element_tag('li'), __svn_AnimationMove, (opt?.)));
                (item);
            }
            void item;
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_2973d64e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2973d64e>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2973d64e>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

