// === input.svelte ===
// generated by svelte-check-native; do not edit

    let value = 1;
declare const a: { [key: string]: any } & ((...args: any[]) => any);
declare const b: { [key: string]: any } & ((...args: any[]) => any);
    type NoComma = true
    type Dependency = {
        a: number;
        b: typeof value;
        c: NoComma
    }
    interface Props<T> {
        a: Dependency;
        b: T;
    }
async function $$render_0d174cf5() {

                       
                       
                  
                        
                  
     

    /** A comment */
                        
                      
             
     

    let { a, b }: Props<boolean> = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    return { props: undefined as any as (Props<boolean>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_0d174cf5;
declare const __svn_component_default: import('svelte').Component<Props<boolean>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props<boolean>>;
export default __svn_component_default;

