// === input.svelte ===
// generated by svelte-check-native; do not edit

declare const Abc: { [key: string]: any } & ((...args: any[]) => any);
interface A extends B<A> {
    Abc: A
    [key: string]: A
}
interface B<T> {}
async function $$render_ed055030() {

                          
          
                    
 

                 

let {Abc}: A = $props()
    ;(async () => {
        // template type-check body (incremental)
    });
    void Abc;
    return { props: undefined as any as (A), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_ed055030;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_ed055030>>['props'],
    Awaited<ReturnType<typeof $$render_ed055030>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

