// === input.svelte ===
// generated by svelte-check-native; do not edit

declare const Abc: { [key: string]: any } & ((...args: any[]) => any);
interface A extends B<A> {
    Abc: A
    [key: string]: A
}
interface B<T> {}
async function $$render_ed055030() {

                          
          
                    
 

                 

let {Abc}: A = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void Abc;
    return { props: undefined as any as (A), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_ed055030;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_ed055030>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_ed055030>>['props'], Awaited<ReturnType<typeof $$render_ed055030>>['events'], Awaited<ReturnType<typeof $$render_ed055030>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_ed055030>>['bindings'] } & Awaited<ReturnType<typeof $$render_ed055030>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_ed055030>>['props']): Awaited<ReturnType<typeof $$render_ed055030>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_ed055030>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

