// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9b0c8b04() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            let new_var: any;
            void new_var;
            let other_var: any;
            void other_var;
            {
                const __svn_C_0 = __svn_ensure_component(Component);
                new __svn_C_0({ target: __svn_any(), props: {} });
            }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_9b0c8b04;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_9b0c8b04>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

