// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_45703bf4() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const item of __svn_each_items(items)) {
            /** @type {number} */ const i = 0;
            { svelteHTML.createElement("div", {});                 (item);
                (i);
            }
            void item;
            void i;
        }
        { svelteHTML.createElement("div", {});         }
    }
    return { props: /** @type {any} */({}) };
}
$$render_45703bf4;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_45703bf4>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

