// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_8be4fc9c() {
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Hello);
            new __svn_C_0({ target: __svn_any(), props: {"|-wtf": "foo"} });
        }
        { svelteHTML.createElement("div", {});         }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_8be4fc9c;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_8be4fc9c>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_8be4fc9c>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

