// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_8be4fc9c() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        Hello(__svn_any(), {"|-wtf": "foo"});
    }
    void __svn_tpl_check;
}
$$render_8be4fc9c;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

