//! Fallback `$app/*` virtual-module ambient declarations.
//!
//! SvelteKit exposes a set of virtual modules (`$app/environment`,
//! `$app/forms`, `$app/navigation`, `$app/paths`, `$app/state`,
//! `$app/server`, `$app/stores`) that are resolved at build time by
//! Kit's bundler plugin. tsgo doesn't run that plugin, so the imports
//! resolve through `node_modules/@sveltejs/kit/...` ambient
//! declarations instead.
//!
//! The gap: workspaces / monorepos where `@sveltejs/kit` is depended-
//! on at the workspace root but not at the per-app `node_modules` —
//! `import { dev } from '$app/environment'` fires TS2307 because the
//! per-app `node_modules` lookup misses the ambient.
//!
//! Fix: emit a fallback ambient declaration file in our cache when
//! the user's `.svelte-kit/types/` exists (signal: this IS a Kit
//! project) but `@sveltejs/kit` types aren't reachable from the
//! workspace's `node_modules`. The fallback declares each `$app/*`
//! module with `any`-typed exports — TS2307 stops firing, property
//! accesses flow through `any`. Users who want strict Kit typing
//! get it from the real `@sveltejs/kit` package; we're a fallback
//! that prevents the noisy TS2307 cascade.
//!
//! Returns `None` when `.svelte-kit/types/` doesn't exist (not a Kit
//! project) or when `@sveltejs/kit` is reachable from the workspace's
//! `node_modules` (real types win — emitting our fallback would
//! collide with TS2300 "Duplicate identifier").

use std::path::PathBuf;

use crate::cache::{CacheLayout, write_if_changed};

const AMBIENTS: &str = r#"// generated by svelte-check-native; do not edit
// Fallback $app/* ambient-module declarations for SvelteKit projects.
// Real types from @sveltejs/kit win when the package is installed
// (this file is only emitted when the package isn't reachable).

declare module '$app/environment' {
    export const browser: boolean;
    export const building: boolean;
    export const dev: boolean;
    export const version: string;
}

// SvelteKit 3 renamed '$app/environment' to '$app/env'. Both are
// declared so one fallback covers either major.
declare module '$app/env' {
    export const browser: boolean;
    export const building: boolean;
    export const dev: boolean;
    export const version: string;
}

declare module '$app/manifest' {
    export const assets: any;
    export const immutable: any;
    export const prerendered: any;
    export const routes: any;
}

declare module '$app/service-worker' {
    export const self: any;
}

declare module '$app/forms' {
    export const applyAction: any;
    export const deserialize: any;
    export const enhance: any;
}

declare module '$app/navigation' {
    export const afterNavigate: any;
    export const beforeNavigate: any;
    export const disableScrollHandling: any;
    export const goto: any;
    export const invalidate: any;
    export const invalidateAll: any;
    export const onNavigate: any;
    export const preloadCode: any;
    export const preloadData: any;
    export const pushState: any;
    export const replaceState: any;
}

declare module '$app/paths' {
    // `base` / `assets` / `resolveRoute` are the SvelteKit 2 surface;
    // `asset` / `resolve` / `match` replace them in SvelteKit 3.
    export const base: string;
    export const assets: string;
    export const resolveRoute: any;
    export const asset: any;
    export const resolve: any;
    export const match: any;
}

declare module '$app/state' {
    export const page: any;
    export const navigating: any;
    export const updated: any;
}

declare module '$app/server' {
    export const read: any;
    export const getRequestEvent: any;
}

declare module '$app/stores' {
    export const page: any;
    export const navigating: any;
    export const updated: any;
    export const getStores: any;
}
"#;

/// Write the `$app/*` ambient declarations file into the cache when
/// the workspace looks like a SvelteKit project AND `@sveltejs/kit`
/// types aren't reachable from its `node_modules`. Returns the path
/// when the file was written, or `None` when no fallback is needed.
pub fn write_ambients(layout: &CacheLayout) -> std::io::Result<Option<PathBuf>> {
    // Detect a Kit project. Two signals, either qualifies:
    //
    // 1. `.svelte-kit/types/` exists (the user has run `svelte-kit
    //    sync` at least once — typical local-dev shape).
    // 2. `svelte.config.js` (or `.ts` / `.mjs`) at the workspace root
    //    references `@sveltejs/kit` somewhere in its source. Catches
    //    fresh checkouts before sync runs, and CI runs that wipe
    //    `.svelte-kit/` for determinism.
    //
    // Either-or because each has a known false-negative case the
    // other catches.
    if !is_kit_project(&layout.workspace) {
        return Ok(None);
    }

    // Skip when @sveltejs/kit's app ambient is reachable — its
    // declarations win and emitting our fallback alongside would
    // cause TS2300 "Duplicate identifier".
    if has_kit_app_types(&layout.workspace) {
        return Ok(None);
    }

    let path = layout.kit_app_ambients();
    write_if_changed(&path, AMBIENTS)?;
    Ok(Some(path))
}

/// Heuristic: does this workspace look like a SvelteKit project?
/// True when `.svelte-kit/types/` exists, or a top-level config file
/// references `@sveltejs/kit`.
///
/// The config probe covers `vite.config.*` as well as `svelte.config.*`
/// because SvelteKit 3 drops `svelte.config.js` entirely — its settings
/// move into the `sveltekit()` plugin call in the Vite config, so a
/// fresh SvelteKit 3 checkout has no `svelte.config.*` to find.
fn is_kit_project(workspace: &std::path::Path) -> bool {
    if workspace.join(".svelte-kit").join("types").is_dir() {
        return true;
    }
    for filename in [
        "svelte.config.js",
        "svelte.config.mjs",
        "svelte.config.ts",
        "vite.config.js",
        "vite.config.mjs",
        "vite.config.ts",
        "vite.config.mts",
    ] {
        let path = workspace.join(filename);
        if let Ok(content) = std::fs::read_to_string(&path) {
            if content.contains("@sveltejs/kit") {
                return true;
            }
        }
    }
    false
}

/// True when `node_modules/@sveltejs/kit/src/runtime/app/` (the
/// directory the `$app/*` path alias resolves to) exists and is
/// reachable from `workspace`. Walks up parent directories so
/// monorepo setups with `@sveltejs/kit` at the root also count as
/// "reachable" — same walk-up semantics as Node module resolution.
fn has_kit_app_types(workspace: &std::path::Path) -> bool {
    let mut cursor = workspace;
    loop {
        let candidate = cursor
            .join("node_modules")
            .join("@sveltejs")
            .join("kit")
            .join("src")
            .join("runtime")
            .join("app");
        if candidate.is_dir() {
            return true;
        }
        match cursor.parent() {
            Some(parent) => cursor = parent,
            None => return false,
        }
    }
}
