//! tsgo integration + tsconfig overlay.
//!
//! ### Pipeline
//!
//! 1. The CLI hands us a list of `.svelte` source files plus the matching
//!    emitted TypeScript (one string per source).
//! 2. We write each generated `.svelte.ts` into the cache directory using
//!    [`cache::write_if_changed`] (so unchanged files don't perturb tsgo's
//!    incremental build info).
//! 3. We write a `.d.svelte.ts` re-export stub for each component so
//!    `import Foo from './Foo.svelte'` resolves at the type level.
//! 4. We generate an overlay tsconfig that extends the user's tsconfig
//!    and lists every generated file via `files`, plus the tsgo-mandatory
//!    `allowArbitraryExtensions: true` and `noEmit: true`.
//! 5. We spawn tsgo with `--project <overlay>.json --pretty true
//!    --noErrorTruncation`, capture combined stdout+stderr, and parse with
//!    [`output::parse`].
//! 6. We map diagnostics back to original `.svelte` paths via the cache
//!    layout. Line/column mapping is best-effort for now (we account for
//!    the wrapper offset added by [`emit::emit_document`] but don't yet
//!    have a real source map).
//!
//! ### What's not yet here
//!
//! - Proper source-map mapping (currently we apply a fixed offset matching
//!   the emitter's wrapper; once the emitter writes sourcemap mappings,
//!   this becomes a v3 source-map consumer).
//! - Path-aliased tsconfig support (`paths`/`rootDirs`/`extends-array`
//!   beyond what the user's tsconfig handles via the extends chain itself).
//! - `references` (project references) propagation.

#![cfg_attr(test, allow(clippy::expect_used, clippy::unwrap_used))]

pub mod cache;
pub mod discovery;
pub mod output;
pub mod overlay;
pub mod runner;

use std::path::{Path, PathBuf};

pub use cache::{CacheLayout, write_if_changed};
pub use discovery::{DiscoveryError, TsgoBinary, discover};
pub use output::{RawDiagnostic, Severity, parse as parse_output};
pub use runner::{RunError, run as run_tsgo};

/// Svelte type shims, baked into the binary. Written into the cache
/// directory on every check so projects without `svelte` installed in
/// node_modules can still type-check (covers all upstream `svelte/*`
/// import paths).
const SVELTE_SHIMS_DTS: &str = include_str!("svelte_shims.d.ts");

/// Number of lines [`svn_emit::emit_document`] inserts before the user's
/// instance script starts. Used to translate tsgo's reported line numbers
/// back to the original `.svelte` line numbers.
///
/// Layout that emit produces (roughly):
/// ```text
/// /// <reference types="svelte" />              line 1
/// // generated by svelte-check-native; do not edit  line 2
/// function $$render() {                          line 3
/// <instance script body starts here>             line 4 of generated == line 1 of user script
/// ```
///
/// The user's script body is itself preceded by `<script>` (line 1) plus
/// the `<script>` tag + the body's opening newline. Mapping back precisely
/// requires knowing how many lines the original file allocated to the
/// `<script>` opening tag — we'd need a source map for that. The constant
/// here is a reasonable fixed approximation that we'll replace with a real
/// source map.
pub const EMIT_PREFIX_LINES: u32 = 3;

/// One file to type-check.
#[derive(Debug, Clone)]
pub struct CheckInput {
    /// Original `.svelte` source path (absolute).
    pub source_path: PathBuf,
    /// Generated TypeScript that should be type-checked.
    pub generated_ts: String,
}

/// A single mapped-back diagnostic ready for presentation.
#[derive(Debug, Clone)]
pub struct CheckDiagnostic {
    /// Original `.svelte` (or `.ts`/`.js`) source path.
    pub source_path: PathBuf,
    /// 1-based line in the original source.
    pub line: u32,
    /// 1-based column in the original source.
    pub column: u32,
    pub severity: Severity,
    /// TypeScript error code (numeric).
    pub code: u32,
    pub message: String,
    pub span_length: Option<u32>,
}

/// Errors from the full check pipeline.
#[derive(Debug, thiserror::Error)]
pub enum CheckError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),

    #[error("tsgo discovery: {0}")]
    Discovery(#[from] DiscoveryError),

    #[error("tsgo run: {0}")]
    Run(#[from] RunError),

    #[error("failed to serialize overlay tsconfig: {0}")]
    Serialize(#[from] serde_json::Error),
}

/// Run the full type-check pipeline.
///
/// `workspace` is the user's project root; `user_tsconfig` is the absolute
/// path to their `tsconfig.json` (or `jsconfig.json`); `inputs` is the list
/// of files-to-check with their generated TS.
///
/// Returns mapped diagnostics ready for output formatting. Returns an empty
/// vec on success with no problems.
pub fn check(
    workspace: &Path,
    user_tsconfig: &Path,
    inputs: &[CheckInput],
) -> Result<Vec<CheckDiagnostic>, CheckError> {
    let layout = CacheLayout::for_workspace(workspace);
    std::fs::create_dir_all(&layout.svelte_dir)?;

    // Ship the svelte type shims into the cache. Provides `svelte`,
    // `svelte/store`, `svelte/transition`, etc. type definitions so
    // projects without a real `svelte` install in node_modules don't
    // fire TS2307 on every `import` from those modules.
    write_if_changed(&layout.svelte_shims, SVELTE_SHIMS_DTS)?;

    // Step 1: write generated TS for each input. Skip identical writes.
    let mut generated_paths: Vec<PathBuf> = Vec::with_capacity(inputs.len());
    for input in inputs {
        let gen_path = layout.generated_path(&input.source_path);
        write_if_changed(&gen_path, &input.generated_ts)?;
        generated_paths.push(gen_path);

        // Re-export stub so `import X from './X.svelte'` resolves at the
        // type level. The `.d.svelte.ts` form is required for
        // `moduleResolution: node16`+. Listed in `files` (below) so tsgo
        // actually loads it; otherwise auto-discovery via
        // `allowArbitraryExtensions` is unreliable across rootDirs
        // boundaries (the `.d.svelte.ts` lives in the cache while the
        // companion `.svelte` source lives in the workspace).
        let dts_path = layout.dts_path(&input.source_path);
        let stem = input
            .source_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("Component");
        let stub = format!(
            "export {{ default }} from \"./++{stem}.svelte.ts\";\n\
             export * from \"./++{stem}.svelte.ts\";\n"
        );
        write_if_changed(&dts_path, &stub)?;
        generated_paths.push(dts_path);
    }

    // Step 2: write overlay tsconfig.
    let overlay = overlay::build(&layout, user_tsconfig, &generated_paths);
    let overlay_text = serde_json::to_string_pretty(&overlay)?;
    write_if_changed(&layout.overlay_tsconfig, &overlay_text)?;

    // Step 3: spawn tsgo.
    let tsgo = discover(workspace)?;
    let raw = run_tsgo(&tsgo, &layout.overlay_tsconfig)?;

    // Step 4: map diagnostics back to source paths + apply line offset.
    Ok(raw
        .into_iter()
        .map(|d| map_diagnostic(d, &layout))
        .collect())
}

fn map_diagnostic(raw: RawDiagnostic, layout: &CacheLayout) -> CheckDiagnostic {
    let (source_path, line) = match layout.original_from_generated(&raw.file) {
        Some(orig) => {
            let adjusted = raw.line.saturating_sub(EMIT_PREFIX_LINES).max(1);
            (orig, adjusted)
        }
        None => (raw.file.clone(), raw.line),
    };
    CheckDiagnostic {
        source_path,
        line,
        column: raw.column,
        severity: raw.severity,
        code: raw.code,
        message: raw.message,
        span_length: raw.span_length,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_generated_file_back_to_source() {
        let layout = CacheLayout::for_workspace("/proj");
        let raw = RawDiagnostic {
            file: PathBuf::from("/proj/.svelte-check/svelte/src/++Foo.svelte.ts"),
            line: 10,
            column: 5,
            severity: Severity::Error,
            code: 2322,
            message: "x".to_string(),
            span_length: None,
        };
        let mapped = map_diagnostic(raw, &layout);
        assert_eq!(mapped.source_path, PathBuf::from("/proj/src/Foo.svelte"));
        // Line offset subtracts EMIT_PREFIX_LINES (3) from 10 → 7.
        assert_eq!(mapped.line, 7);
    }

    #[test]
    fn passes_through_non_generated_files() {
        let layout = CacheLayout::for_workspace("/proj");
        let raw = RawDiagnostic {
            file: PathBuf::from("/proj/src/plain.ts"),
            line: 4,
            column: 1,
            severity: Severity::Error,
            code: 1000,
            message: "x".to_string(),
            span_length: None,
        };
        let mapped = map_diagnostic(raw, &layout);
        assert_eq!(mapped.source_path, PathBuf::from("/proj/src/plain.ts"));
        assert_eq!(mapped.line, 4); // no offset applied to non-generated files
    }

    #[test]
    fn line_offset_clamps_to_one_for_diagnostics_in_wrapper_lines() {
        let layout = CacheLayout::for_workspace("/proj");
        let raw = RawDiagnostic {
            file: PathBuf::from("/proj/.svelte-check/svelte/++X.svelte.ts"),
            line: 1,
            column: 1,
            severity: Severity::Error,
            code: 1,
            message: "wrapper".to_string(),
            span_length: None,
        };
        let mapped = map_diagnostic(raw, &layout);
        assert_eq!(mapped.line, 1);
    }
}
