// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2403d132() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
        }
        { svelteHTML.createElement("svelte:fragment", {});             { svelteHTML.createElement("p", {});             }
        }
        { svelteHTML.createElement("svelte:fragment", {});             { svelteHTML.createElement("p", {});             }
        }
        {
            const __svn_C_a6 = __svn_ensure_component(Component);
            new __svn_C_a6({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
        }
        { svelteHTML.createElement("svelte:fragment", {});             {
                let foo: any;
                void foo;
                let baz: any;
                void baz;
                { svelteHTML.createElement("p", {});                     (foo);
                    (baz);
                }
            }
        }
        { svelteHTML.createElement("svelte:fragment", {});             {
                let foo: any;
                void foo;
                let baz: any;
                void baz;
                { svelteHTML.createElement("p", {});                     (foo);
                    (baz);
                }
            }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_2403d132;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2403d132>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

