// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_31770ada() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if ((name == "world")) {
            void [name];
            { svelteHTML.createElement("h1", {});                 (name);
            }
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_31770ada;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_31770ada>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

