// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_31770ada() {
    ;(async () => {
        // template type-check body (incremental)
        if ((name == "world")) {
            void [name];
            { svelteHTML.createElement("h1", {});                 (name);
            }
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_31770ada;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_31770ada>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_31770ada>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

