// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_30739603() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            new __svn_C_0({ target: __svn_any(), props: {} });
        }
    }
    void __svn_tpl_check;
}
$$render_30739603;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

