// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b55beab5() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        Comp(__svn_any(), {});
        Comp(__svn_any(), {});
    }
    void __svn_tpl_check;
}
$$render_b55beab5;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

