// === Inner.svelte ===
// generated by svelte-check-native; do not edit
function $$render_ebbf9128() {
    type $$ComponentProps = { open: boolean; onToggle: () => void };

    let { open, onToggle }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props();
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "onclick": (onToggle),
        });
            (open ? 'close' : 'open');
        }
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_ebbf9128;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_ebbf9128>>['props'],
    Awaited<ReturnType<typeof $$render_ebbf9128>>['exports'],
    Awaited<ReturnType<typeof $$render_ebbf9128>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

// === Wrapper.svelte ===
// generated by svelte-check-native; do not edit
    import type { Snippet } from 'svelte';
function $$render_74f92bad() {
    type $$ComponentProps = { children: Snippet<[isOpen: boolean, toggle: () => void]> };

                                          
    let { children }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props();
    ;(async () => {
        // template type-check body (incremental)
        __svn_ensure_snippet(children(true, () => {}));
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_74f92bad;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_74f92bad>>['props'],
    Awaited<ReturnType<typeof $$render_74f92bad>>['exports'],
    Awaited<ReturnType<typeof $$render_74f92bad>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

// === input.svelte ===
// generated by svelte-check-native; do not edit
    import Wrapper from './Wrapper.svelte';
    import Inner from './Inner.svelte';
function $$render_e40e2c10() {

                                           
                                       
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_72 = __svn_ensure_component(Wrapper);
            new __svn_C_72({
                target: __svn_any(),
                props: {
                    children: (isOpen, toggle) => { async () => {
                        {
                            const __svn_C_ac = __svn_ensure_component(Inner);
                            new __svn_C_ac({ target: __svn_any(), props: {"open": (isOpen), "onToggle": (toggle)} });
                        }
                        };
                        return __svn_snippet_return();
                    },
                },
            });
        }
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] extends Record<string, never> ? { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] } : Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] & { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] }): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

