// === input.svelte ===
// generated by svelte-check-native; do not edit
  import { writable } from 'svelte/store';
async function $$render_36f25f12() {
    /** @type {__SvnStoreValue<typeof count>} */
    let $count = /** @type {any} */ (/** @type {any} */ (null));

                                          
  const count = writable(0);
  const handler1 = () => !$count
  const handler2 = () => +$count
  const handler3 = () => -$count
  const handler4 = () => ~$count
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "on:click": (() => !$count),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => +$count),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => -$count),
        });
        }
        { svelteHTML.createElement("button", {
            "on:click": (() => ~$count),
        });
        }
    });
    void $count;
    void count;
    return { props: /** @type {any} */({}) };
}
$$render_36f25f12;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_36f25f12>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

