// === input.svelte ===
// generated by svelte-check-native; do not edit
import { writable } from 'svelte/store';
async function $$render_36f25f12() {
    let $count!: __SvnStoreValue<typeof count>;

                                          
  const count = writable(0);
  const handler1 = () => !$count
  const handler2 = () => +$count
  const handler3 = () => -$count
  const handler4 = () => ~$count
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $count;
    void count;
}
$$render_36f25f12;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

