// === input.svelte ===
// generated by svelte-check-native; do not edit

    import X from './X';
declare const foo: any;
import { readable } from 'svelte/store';
interface Props {
        foo?: string;
    }
async function $$render_b09ebc4f() {
    let $store!: __SvnStoreValue<typeof store>;

                                            
    
    const store = readable(1)
 
    /** I should not be sandwitched between the imports */
                     
                     
     
    let { foo }: Props = $props()
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void $store;
    void store;
    void foo;
}
$$render_b09ebc4f;
declare const __svn_component_default: import('svelte').Component<Props>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props>;
export default __svn_component_default;

