// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a3a3d9ca() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        let __svn_action_attrs_0: any = {};
        void __svn_action_attrs_0;
        let __svn_action_attrs_1: any = {};
        void __svn_action_attrs_1;
        let __svn_action_attrs_2: any = {};
        void __svn_action_attrs_2;
        let __svn_action_attrs_3: any = {};
        void __svn_action_attrs_3;
        let __svn_action_attrs_4: any = {};
        void __svn_action_attrs_4;
        const __svn_action_0 = __svn_ensure_action(svgAction(__svn_map_element_tag('svg')));
        void __svn_action_0;
        const __svn_action_1 = __svn_ensure_action(divAction(__svn_map_element_tag('div')));
        void __svn_action_1;
        const __svn_action_2 = __svn_ensure_action(action(__svn_map_element_tag('input')));
        void __svn_action_2;
        const __svn_action_3 = __svn_ensure_action(pAction(__svn_map_element_tag('p')));
        void __svn_action_3;
        const __svn_action_4 = __svn_ensure_action(unknownAction(__svn_map_element_tag('unknownTag')));
        void __svn_action_4;
    }
    void __svn_tpl_check;
}
$$render_a3a3d9ca;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

