// === input.svelte ===
// generated by svelte-check-native; do not edit


async function $$render_50f1c2a8() {

    let foo = true;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const chain: any = undefined;
            void chain;
            const chain2: any = undefined;
            void chain2;
            const chain3: any = undefined;
            void chain3;
            const hoistable: any = undefined;
            void hoistable;
            (foo);
        }
    }
    void __svn_tpl_check;
    void foo;
}
$$render_50f1c2a8;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

