// === input.svelte ===
// generated by svelte-check-native; do not edit


async function $$render_e40e2c10() {
    /** @type {any} */ const chain = /** @type {any} */ (undefined);
    void chain;
    /** @type {any} */ const chain2 = /** @type {any} */ (undefined);
    void chain2;
    /** @type {any} */ const chain3 = /** @type {any} */ (undefined);
    void chain3;
    /** @type {any} */ const hoistable = /** @type {any} */ (undefined);
    void hoistable;

    let foo = true;
    ;(async () => {
        // template type-check body (incremental)
        {
            const chain = () => { async () => {
                { svelteHTML.createElement("div", {});                     (foo);
                }
                };
                return null;
            };
            void chain;
            const chain2 = () => { async () => {
                (chain());
                };
                return null;
            };
            void chain2;
            const chain3 = () => { async () => {
                (chain2());
                };
                return null;
            };
            void chain3;
            const hoistable = () => { async () => {
                { svelteHTML.createElement("h1", {});                 }
                };
                return null;
            };
            void hoistable;
        }
    });
    void foo;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

