// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const destructured: any;
declare const prop: any;
type Props = {
		prop: typeof destructured;
	};
async function $$render_94c42fc9() {

	let { destructured } = {};
	              
                            
   
	let { prop }: Props = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void prop;
}
$$render_94c42fc9;
declare const __svn_component_default: import('svelte').Component<Props>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props>;
export default __svn_component_default;

