// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{a: any, b: any}} $$ComponentProps */
function $$render_e40e2c10() {

    /** @type {SomeType} */
    let { a, b } = $props();
    let x = $state(0);
    let y = $derived(x * 2);
    const __svn_create_slot = __svn_create_create_slot();
    ;(async () => {
        // template type-check body (incremental)
        {
            __svn_create_slot("default", { x, y });
        }
    });
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': { x: (x), y: (y) } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'], Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

