// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{a: any, b: any}} $$ComponentProps */
async function $$render_d2d4cb4e() {

    /** @type {SomeType} */
    let { a, b } = $props();
    let x = $state(0);
    let y = $derived(x * 2);
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    void x;
    void y;
    return { props: /** @type {$$ComponentProps} */({}) };
}
$$render_d2d4cb4e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d2d4cb4e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

