// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_81de568f() {
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_81de568f;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_81de568f>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

