// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e40e2c10() {

    // A body-level const whose *name* is referenced from a TS type alias.
    // The type alias is hoisted to module scope (so hoisted `interface
    // Props`-style exports can reference it); the const stays in the
    // `$$render` body. Without a `declare const` stub at module scope
    // the hoisted type fires "Cannot find name 'chartKinds'".
    const chartKinds = ['line', 'bar', 'area'] as const
    type ChartKind = (typeof chartKinds)[number]

    // Second pattern: `typeof fn` inside a hoisted interface referencing
    // a body-level function declaration.
    async function fetchChart(): Promise<ChartKind> {
        return 'line'
    }
    interface Api {
        fetch: typeof fetchChart
    }

    const kind: ChartKind = 'bar'
    const api: Api = { fetch: fetchChart }
    void kind
    void api
    void chartKinds
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props']): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

