// === +layout.svelte ===
// generated by svelte-check-native; do not edit
type $$ComponentProps = { children?: import('svelte').Snippet; };
async function $$render_7035891f() {

    // +layout.svelte — our emit injects `data: LayoutData` and
    // `children?: Snippet` when the destructure omits them. Here we
    // spell `children` explicitly (common pattern) and omit `data` to
    // exercise the path where a layout takes ONLY children.
    let { children }: $$ComponentProps = $props();
    ;(async () => {
        // template type-check body (incremental)
        (children?.());
    });
    void children;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_7035891f;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_7035891f>>['props'],
    Awaited<ReturnType<typeof $$render_7035891f>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

