// === +layout.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7035891f() {
    type $$ComponentProps = { children: import('svelte').Snippet; };
    type $$Events = {};

    // +layout.svelte — our emit injects `data: LayoutData` and
    // `children?: Snippet` when the destructure omits them. Here we
    // spell `children` explicitly (common pattern) and omit `data` to
    // exercise the path where a layout takes ONLY children.
    let { children }: $$ComponentProps = $props();
    ;(async () => {
        // template type-check body (incremental)
        (children?.());
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_7035891f;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_7035891f>>['props'],
    Awaited<ReturnType<typeof $$render_7035891f>>['exports'],
    Awaited<ReturnType<typeof $$render_7035891f>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

