// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6c5fd365() {
    ;(async () => {
        // template type-check body (incremental)
        (someRecordOrArr[$store]);
        (someObject['$store']);
        (someObject.$store);
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_6c5fd365;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6c5fd365>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6c5fd365>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

