// === input.svelte ===
// generated by svelte-check-native; do not edit
    import storeA from './store';
    import { storeB } from './store';
    import { storeB as storeC } from './store';
async function $$render_7c15f1e0() {
    let $storeA!: __SvnStoreValue<typeof storeA>;
    let $storeB!: __SvnStoreValue<typeof storeB>;
    let $storeC!: __SvnStoreValue<typeof storeC>;

                                 
                                     
                                               
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        /*svn_I*/($storeA);
        /*svn_I*/($storeB);
        /*svn_I*/($storeC);
    }
    void __svn_tpl_check;
    void $storeA;
    void storeA;
    void $storeB;
    void storeB;
    void $storeC;
    void storeC;
}
$$render_7c15f1e0;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

