// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ba1a20ec() {

    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_2f = __svn_ensure_component(T);
            new __svn_C_2f({ target: __svn_any(), props: {"extends": true, "string": true, children: () => __svn_snippet_return()} });
        }
        (val);
        {
            const __svn_C_77 = __svn_ensure_component(T);
            new __svn_C_77({ target: __svn_any(), props: {"extends": true, "|": true, "|": true, "Set": true, children: () => __svn_snippet_return()} });
        }
        (val);
    }
    void __svn_tpl_check;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_ba1a20ec;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_ba1a20ec>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_ba1a20ec>>['props'], Awaited<ReturnType<typeof $$render_ba1a20ec>>['events'], Awaited<ReturnType<typeof $$render_ba1a20ec>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_ba1a20ec>>['bindings'] } & Awaited<ReturnType<typeof $$render_ba1a20ec>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_ba1a20ec>>['props']): Awaited<ReturnType<typeof $$render_ba1a20ec>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_ba1a20ec>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

