// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ba1a20ec() {

    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_2f = __svn_ensure_component(T);
            new __svn_C_2f({ target: __svn_any(), props: {extends: true, string: true, children: () => __svn_snippet_return()} satisfies InstanceType<typeof __svn_C_2f>['$$prop_def'] });
        }
        {
            const __svn_C_77 = __svn_ensure_component(T);
            new __svn_C_77({ target: __svn_any(), props: {extends: true, "|": true, "|": true, Set: true, children: () => __svn_snippet_return()} satisfies InstanceType<typeof __svn_C_77>['$$prop_def'] });
        }
    }
    void __svn_tpl_check;
}
$$render_ba1a20ec;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

