// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_03b58764() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            let n: any;
            void n;
            let shadowed1: any;
            void shadowed1;
            let shadowed2: any;
            void shadowed2;
            let subthing: any;
            void subthing;
            {
                let subthing: any;
                void subthing;
                (thing);
                (subthing);
            }
            {
                let subthing: any;
                void subthing;
                let othersubthing: any;
                void othersubthing;
                {
                    const __svn_C_169 = __svn_ensure_component(Sub);
                    new __svn_C_169({ target: __svn_any(), props: {subthing, children: () => __svn_snippet_return()} });
                }
                (thing);
                (subthing);
            }
            {
                let subthing: any;
                void subthing;
                let othersubthing: any;
                void othersubthing;
                {
                    const __svn_C_205 = __svn_ensure_component(Sub);
                    new __svn_C_205({ target: __svn_any(), props: {subthing, children: () => __svn_snippet_return()} });
                }
                (thing);
                (subthing);
            }
        }
    }
    void __svn_tpl_check;
}
$$render_03b58764;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

