// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_3cecb40c() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        void /* bind:this */ ((): void => { element = null as any as HTMLElement; });
    }
    void __svn_tpl_check;
}
$$render_3cecb40c;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

