// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const data: { [key: string]: any } & ((...args: any[]) => any);
type Props = {
    data: {cfg: string};
};
async function $$render_654e105f() {

              
                        
  
let { data }: Props = $props();

type A = typeof data.cfg;
type B = (typeof data)['cfg'];
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void data;
}
$$render_654e105f;
declare const __svn_component_default: import('svelte').Component<Props>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props>;
export default __svn_component_default;

