// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const data: { [key: string]: any } & ((...args: any[]) => any);
type Props = {
    data: {cfg: string};
};
async function $$render_654e105f() {

              
                        
  
let { data }: Props = $props();

type A = typeof data.cfg;
type B = (typeof data)['cfg'];
    ;(async () => {
        // template type-check body (incremental)
    });
    void data;
    return { props: undefined as any as (Props), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_654e105f;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_654e105f>>['props'],
    Awaited<ReturnType<typeof $$render_654e105f>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

