// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a41317e5() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("div", {});         }
        {
            const error = __svn_any();
            { svelteHTML.createElement("div", {});                 (error);
            }
            void error;
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_a41317e5;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a41317e5>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a41317e5>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

