// === input.svelte ===
// generated by svelte-check-native; do not edit
    interface WithItems<T> {
        items: T[];
    }
async function $$render_e40e2c10<T extends { a: string }>() {
    type $$Events = {};

                            
                   
     

	interface Props extends WithItems<T> {
		prop: T;
	};
	let { prop }: Props = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (Props), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_e40e2c10;
declare class __svn_Render_e40e2c10<T extends { a: string }> {
    props(): Awaited<ReturnType<typeof $$render_e40e2c10<T>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_e40e2c10<T>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_e40e2c10<T>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_e40e2c10<T>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_e40e2c10<T>>>['exports'];
}
interface $$IsomorphicComponent {
    new <T extends { a: string }>(options: import('svelte').ComponentConstructorOptions<ReturnType<__svn_Render_e40e2c10<T>['props']>>): import('svelte').SvelteComponent<ReturnType<__svn_Render_e40e2c10<T>['props']>, ReturnType<__svn_Render_e40e2c10<T>['events']>, ReturnType<__svn_Render_e40e2c10<T>['slots']>> & { $$bindings?: ReturnType<__svn_Render_e40e2c10<T>['bindings']> } & ReturnType<__svn_Render_e40e2c10<T>['exports']>;
    <T extends { a: string }>(internal: unknown, props: ReturnType<__svn_Render_e40e2c10<T>['props']>): ReturnType<__svn_Render_e40e2c10<T>['exports']> & { $set?: any; $on?: any };
    z_$$bindings?: ReturnType<__svn_Render_e40e2c10<any>['bindings']>;
}
const __svn_component_default: $$IsomorphicComponent & { readonly __svn_events: Awaited<ReturnType<typeof $$render_e40e2c10>>['events'] } = null as any;
type __svn_component_default<T extends { a: string }> = InstanceType<typeof __svn_component_default<T>>;
export default __svn_component_default;

