// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_08555e51() {
    let $$restProps = /** @type {Record<string, any>} */ ({});
    void $$restProps;

    let name = $$restProps['name'];
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (name);
        }
    });
    void name;
    return { props: /** @type {any} */({}) };
}
$$render_08555e51;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_08555e51>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

