// === input.svelte ===
// generated by svelte-check-native; do not edit

    import { store2 } from './foo';
    import { store } from './foo';
async function $$render_6c5b63d4() {
    let $store!: __SvnStoreValue<typeof store>;
    let $store2!: __SvnStoreValue<typeof store2>;

                                  
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const _foo: any = undefined;
            void _foo;
            const _foo2: any = undefined;
            void _foo2;
            /*svn_I*/($store);
            /*svn_I*/($store2);
        }
    }
    void __svn_tpl_check;
    void $store;
    void store;
    void $store2;
    void store2;
}
$$render_6c5b63d4;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

