// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_5a7d1551<T extends { id: string }>() {

    // Props type references the component's generic parameter. Before
    // the `generics` attribute was threaded through the emit, the
    // `type Props` declaration got hoisted out of $$render into the
    // overlay's module scope where `T` was unbound, producing
    // "Cannot find name 'T'" against every property that referenced it.
    type Props = { item: T; label: string };
    let { item, label }: Props = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        (label);
        (item.id);
    }
    void __svn_tpl_check;
    void item;
    void label;
    return { props: undefined as any as (Props) };
}
$$render_5a7d1551;
declare class __svn_Render_5a7d1551<T extends { id: string }> { props(): Awaited<ReturnType<typeof $$render_5a7d1551<T>>>['props']; }
declare const __svn_component_default: <T extends { id: string }>(__anchor: any, props: Partial<ReturnType<__svn_Render_5a7d1551<T>['props']>>) => any;
declare type __svn_component_default<T extends { id: string }> = import('svelte').SvelteComponent<ReturnType<__svn_Render_5a7d1551<T>['props']>>;
export default __svn_component_default;

