// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1d4edb02() {

    /**
     * @typedef {'FOO'} FOO
     */

    /**
     * DOCS!
     * @typedef {'ABC'} ABC
     */
           let a!: any;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
}
$$render_1d4edb02;
declare const __svn_component_default: import('svelte').Component<{ a: any; } & __SvnSvelte4PropsWiden<{ a: any; }>, { a: any; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ a: any; } & __SvnSvelte4PropsWiden<{ a: any; }>> & { a: any; };
export default __svn_component_default;

