// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_90d89a0a() {

	       let foo: number = undefined
foo = undefined as any;
	       let foo2: any = undefined
foo2 = undefined as any;
	let clazz!: string
	                         
	       const bar: string = ''
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "accessors": (true),
        });
        }
    }
    void __svn_tpl_check;
    void foo;
    void foo2;
    void clazz;
    void bar;
    return { props: undefined as any as ({ foo?: number; foo2?: any; class: string; bar?: string; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ foo: number; foo2: typeof foo2; bar: string; }) };
}
$$render_90d89a0a;
declare const __svn_component_default: import('svelte').Component<{ foo?: number; foo2?: any; class: string; bar?: string; }, Awaited<ReturnType<typeof $$render_90d89a0a>>['exports']>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo?: number; foo2?: any; class: string; bar?: string; }> & Awaited<ReturnType<typeof $$render_90d89a0a>>['exports'];
export default __svn_component_default;

