// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_90d89a0a() {

	       let foo: number = undefined; foo = undefined as any;
	       let foo2: any = undefined; foo2 = undefined as any;
	let clazz!: string
	                         
	       const bar: string = ''
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "accessors": (true),
        });
        }
    }
    void __svn_tpl_check;
    void foo;
    void foo2;
    void clazz;
    void bar;
    return { props: undefined as any as ({ foo?: number; foo2?: typeof foo2; class: string; bar?: string; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ foo: number; foo2: typeof foo2; bar: string; }) };
}
$$render_90d89a0a;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_90d89a0a>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_90d89a0a>>['props'], Awaited<ReturnType<typeof $$render_90d89a0a>>['events'], Awaited<ReturnType<typeof $$render_90d89a0a>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_90d89a0a>>['bindings'] } & Awaited<ReturnType<typeof $$render_90d89a0a>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_90d89a0a>>['props']): Awaited<ReturnType<typeof $$render_90d89a0a>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_90d89a0a>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

