// === Wrapper.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_367eaaa4() {
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_367eaaa4;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_367eaaa4>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

// === Foo.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_8872ef43() {
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_8872ef43;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_8872ef43>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

// === input.svelte ===
// generated by svelte-check-native; do not edit
    import Bar from './Bar.svelte';
    import Foo from './Foo.svelte';
    import Wrapper from './Wrapper.svelte';
async function $$render_ea0d2cdf() {

                                   
                                   
                                           
    ;(async () => {
        // template type-check body (incremental)
        const __svn_create_slot = __svn_create_create_slot();
        {
            const __svn_C_1cd = __svn_ensure_component(Wrapper);
            const __svn_inst_1cd = new __svn_C_1cd({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            {
                const __svn_C_1db = __svn_ensure_component(Foo);
                new __svn_C_1db({ target: __svn_any(), props: {} });
            }
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, thing } = __svn_inst_1cd.$$slot_def["x"]; $$_$$;
                void thing;
                {
                    const __svn_C_1e7 = __svn_ensure_component(Bar);
                    new __svn_C_1e7({ target: __svn_any(), props: {} });
                    {
                        __svn_create_slot("default", { a: (thing) });
                    }
                }
            }
        }
    });
    void Wrapper;
    void Foo;
    void Bar;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: { 'default': {  } }, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_ea0d2cdf;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<__SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props'], Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props'] & __SvnSvelte4PropsWiden<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props']>>>): import('svelte').SvelteComponent<Partial<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props'] & __SvnSvelte4PropsWiden<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props']>>, Awaited<ReturnType<typeof $$render_ea0d2cdf>>['events'], Awaited<ReturnType<typeof $$render_ea0d2cdf>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_ea0d2cdf>>['bindings'] } & Awaited<ReturnType<typeof $$render_ea0d2cdf>>['exports'];
    (internal: unknown, props: __SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props'], Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props'] & __SvnSvelte4PropsWiden<Awaited<ReturnType<typeof $$render_ea0d2cdf>>['props']>>): Awaited<ReturnType<typeof $$render_ea0d2cdf>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_ea0d2cdf>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

// === Bar.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4836fa5b() {
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_4836fa5b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4836fa5b>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

