// === input.svelte ===
// generated by svelte-check-native; do not edit
interface Props extends T {
	}
async function $$render_e800a6a5<T extends { a: string }>() {

	                           
  ;
	let { a }: Props = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
}
$$render_e800a6a5;
declare const __svn_component_default: import('svelte').Component<Props>;
declare type __svn_component_default = import('svelte').SvelteComponent<Props>;
export default __svn_component_default;

