// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_71b5302a() {
    let $$props = /** @type {Record<string, any>} */ ({});
    void $$props;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             ($$props['name']);
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_71b5302a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_71b5302a>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

