// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b67cf125() {
    ;(async () => {
        // template type-check body (incremental)
        if ((hello)) {
            void [hello];
            { const $$_promise = (hello.foo);
            ;(async () => {
                const $$_await = await $$_promise; const y = $$_await;
                (y);
                void y;
            }); }
            { const $$_promise = (x);
            ;(async () => {
                const $$_await = await $$_promise; const y = $$_await;
                (y);
                void y;
            }); }
            (hello);
            if ((hi && bye)) {
                void [hi, bye];
                { const $$_promise = (x);
                ;(async () => {
                    const $$_await = await $$_promise; const y = $$_await;
                    (y);
                    void y;
                }); }
            } else if ((cool)) {
                void [cool];
                { const $$_promise = (x);
                ;(async () => {
                    const $$_await = await $$_promise; const y = $$_await;
                    (y);
                    void y;
                }); }
            } else {
                { const $$_promise = (x);
                ;(async () => {
                    const $$_await = await $$_promise; const y = $$_await;
                    (y);
                    void y;
                }); }
            }
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_b67cf125;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b67cf125>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b67cf125>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

