// === DerivedBy.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_56c6b8a3() {
    type $$Events = {};
    let $derived!: __SvnStoreValue<typeof derived>;

    // A binding literally named `derived` makes `$derived.by(...)` a
    // store subscription of that binding (the identifier sits in a
    // member access, not the rune-decl call position). The alias
    // references `derived`, whose init references `$derived` — a
    // self-referential declaration, so TS7022 fires. Upstream
    // svelte2tsx emits the same subscription and fires the same
    // diagnostic at the same user position.
    const derived = $derived.by(() => 1);
    void derived;
    ;(async () => {
        // template type-check body (incremental)
    });
    void $derived;
    void derived;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_56c6b8a3;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_56c6b8a3>>['props'],
    Awaited<ReturnType<typeof $$render_56c6b8a3>>['exports'],
    Awaited<ReturnType<typeof $$render_56c6b8a3>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { writable } from 'svelte/store';
async function $$render_a8fbf675() {
    let $state!: __SvnStoreValue<typeof state>;

                                            

    // A Svelte-4 store literally named `state`: `$state.count` is a
    // subscription to it, not rune usage. The subscription alias must
    // be declared so the member access resolves against the store's
    // value type.
    const state = writable({ count: 0 });
    const doubled = $state.count * 2;
    void doubled;
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             ($state.count);
        }
    });
    void $state;
    void state;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_a8fbf675;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_a8fbf675>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_a8fbf675>>['props'], Awaited<ReturnType<typeof $$render_a8fbf675>>['events'], Awaited<ReturnType<typeof $$render_a8fbf675>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_a8fbf675>>['bindings'] } & Awaited<ReturnType<typeof $$render_a8fbf675>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_a8fbf675>>['props']): Awaited<ReturnType<typeof $$render_a8fbf675>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_a8fbf675>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

// === Bad.svelte ===
// generated by svelte-check-native; do not edit
    import { writable } from 'svelte/store';
async function $$render_ef21db2d() {
    let $state!: __SvnStoreValue<typeof state>;

                                            

    const state = writable({ count: 0 });
    // `missing` is not on the store's value type — the subscription
    // alias carries the real value type, so this fires TS2339.
    const broken = $state.missing;
    void broken;
    ;(async () => {
        // template type-check body (incremental)
    });
    void $state;
    void state;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_ef21db2d;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_ef21db2d>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_ef21db2d>>['props'], Awaited<ReturnType<typeof $$render_ef21db2d>>['events'], Awaited<ReturnType<typeof $$render_ef21db2d>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_ef21db2d>>['bindings'] } & Awaited<ReturnType<typeof $$render_ef21db2d>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_ef21db2d>>['props']): Awaited<ReturnType<typeof $$render_ef21db2d>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_ef21db2d>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

