// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d7008d7a() {

    function x(tr) {
        for (let notAStore of tr.effects) {}
    }

    $notAStore;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_d7008d7a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d7008d7a>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d7008d7a>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

