// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d7008d7a() {

    function x(tr) {
        for (let notAStore of tr.effects) {}
    }

    $notAStore;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_d7008d7a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d7008d7a>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

