// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4ae41d3d() {

    const p: Promise<number> = Promise.resolve(1);
    const q: Promise<string> = Promise.reject(new Error('nope'));

    function fetchData(url: string, retries: number): Promise<boolean> {
        void url;
        void retries;
        return Promise.resolve(true);
    }
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (p);
        ;(async () => {
            const $$_await = await $$_promise; const v = $$_await;
            { svelteHTML.createElement("span", {});                 (v.toFixed(2));
            }
            void v;
        }); }
        {
            const e = __svn_any();
            { svelteHTML.createElement("span", {});                 (String(e));
            }
            void e;
        }
        { const $$_promise = (fetchData(
    'https://example.com',
    3
));
        ;(async () => {
            const $$_await = await $$_promise; const ok = $$_await;
            { svelteHTML.createElement("span", {});                 (ok ? 'yes' : 'no');
            }
            void ok;
        }); }
    });
    void p;
    void q;
    void fetchData;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_4ae41d3d;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_4ae41d3d>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_4ae41d3d>>['props'], Awaited<ReturnType<typeof $$render_4ae41d3d>>['events'], Awaited<ReturnType<typeof $$render_4ae41d3d>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_4ae41d3d>>['bindings'] } & Awaited<ReturnType<typeof $$render_4ae41d3d>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_4ae41d3d>>['props']): Awaited<ReturnType<typeof $$render_4ae41d3d>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_4ae41d3d>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

