// === input.svelte ===
// generated by svelte-check-native; do not edit
    import ''
async function $$render_941ec73b() {

    // non-leading comment

    /**@typedef {{ a: string }} Foo */
             
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {Foo} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_941ec73b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_941ec73b>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_941ec73b>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

