// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ba1a20ec() {

    async function __svn_tpl_check() {
        // template type-check body (incremental)
        T(__svn_any(), {extends: true, string: true});
        T(__svn_any(), {extends: true, "|": true, "|": true, Set: true});
    }
    void __svn_tpl_check;
}
$$render_ba1a20ec;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

