// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4a2d9092() {

	       let foo: number = undefined;
foo = undefined as any;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void foo;
    return { props: undefined as any as ({ foo?: number; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ foo: number; }) };
}
$$render_4a2d9092;
declare const __svn_component_default: import('svelte').Component<{ foo?: number; }, Awaited<ReturnType<typeof $$render_4a2d9092>>['exports']>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo?: number; }> & Awaited<ReturnType<typeof $$render_4a2d9092>>['exports'];
export default __svn_component_default;

