// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_2e970f76() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:head", {});             { svelteHTML.createElement("title", {});             }
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_2e970f76;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_2e970f76>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

