// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_677076f2() {

    let name1: string = "world"
    let name2: string;
    let name3: string = '', name4: string;

    let rename1: string = '';
    let rename2: string;

    class Foo {}
    function bar() {}
    const baz: string = '';

    class RenameFoo {}
    function renamebar() {}
    const renamebaz: string = '';

                                                                                                                                                                              
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "runes": true,
        });
        }
    }
    void name1;
    void name2;
    void name3;
    void name4;
    void rename1;
    void rename2;
    void Foo;
    void bar;
    void baz;
    void RenameFoo;
    void renamebar;
    void renamebaz;
    return { props: /** @type {any} */({}) };
}
$$render_677076f2;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_677076f2>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

