// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    let name1: string = "world"/*svn:ignore_start*/;name1 = __svn_any(name1);/*svn:ignore_end*/
    let name2: string/*svn:ignore_start*/;name2 = __svn_any(name2);/*svn:ignore_end*/;
    let name3: string = '', name4: string/*svn:ignore_start*/;name3 = __svn_any(name3);/*svn:ignore_end*//*svn:ignore_start*/;name4 = __svn_any(name4);/*svn:ignore_end*/;

    let rename1: string = ''/*svn:ignore_start*/;rename1 = __svn_any(rename1);/*svn:ignore_end*/;
    let rename2: string/*svn:ignore_start*/;rename2 = __svn_any(rename2);/*svn:ignore_end*/;

    class Foo {}
    function bar() {}
    const baz: string = '';

    class RenameFoo {}
    function renamebar() {}
    const renamebaz: string = '';

                                                                                                                                                                              
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "runes": true,
        });
        }
    });
    void name1;
    void name2;
    void name3;
    void name4;
    void rename1;
    void rename2;
    void Foo;
    void bar;
    void baz;
    void RenameFoo;
    void renamebar;
    void renamebaz;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ name1: typeof name1; name2: typeof name2; name3: typeof name3; name4: typeof name4; renamed1: typeof rename1; renamed2: typeof rename2; Foo: typeof Foo; bar: typeof bar; baz: typeof baz; RenamedFoo: typeof RenameFoo; renamedbar: typeof renamebar; renamedbaz: typeof renamebaz; }} */ ({}) };
}
$$render_e40e2c10;
/** @type {import('svelte').Component<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

