// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_62c79e0f() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("iframe", {
            "src": "",
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_62c79e0f;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_62c79e0f>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_62c79e0f>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

