// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d8e573c4() {
    ;(async () => {
        // template type-check body (incremental)
        for (const item of __svn_each_items(items)) {
            { svelteHTML.createElement("div", {});                 (item);
            }
            void item;
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_d8e573c4;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_d8e573c4>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

