// === input.svelte ===
// generated by svelte-check-native; do not edit

    let a = '';
type $$ComponentProps = { someProp: typeof a };
async function $$render_bf18a5c0() {

    let a = true;
    let { someProp }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void someProp;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_bf18a5c0;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_bf18a5c0>>['props'],
    Awaited<ReturnType<typeof $$render_bf18a5c0>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

