// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6a73bb59() {

           let a = /** @type {any} */ (null);
           let b = /** @type {any} */ (null);
           let c = 123;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void a;
    void b;
    void c;
    return { props: /** @type {{ a: any; b: any; c?: typeof c; }} */({}) };
}
$$render_6a73bb59;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6a73bb59>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

