// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_af2b5ddf() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (somePromise);
        ;(async () => {
            const $$_await = await $$_promise; const value = $$_await;
            { svelteHTML.createElement("h1", {});             }
            void value;
        }); }
        { svelteHTML.createElement("h1", {});         }
        { const $$_promise = (somePromise);
        ;(async () => {
            const $$_await = await $$_promise; void $$_await;
            { svelteHTML.createElement("h1", {});             }
        }); }
    });
    return { props: /** @type {any} */({}) };
}
$$render_af2b5ddf;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_af2b5ddf>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

