// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_bf9851b3() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("div", {});         }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_bf9851b3;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_bf9851b3>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

