// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e50f2117() {

const array = [1, 2, 3, [4]];

       const [a, b, c, [d]] = array;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    void d;
    return { props: /** @type {any} */({}) };
}
$$render_e50f2117;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e50f2117>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

