// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e50f2117() {

const array = [1, 2, 3, [4]];

       const [a, b, c, [d]] = array;
    ;(async () => {
        // template type-check body (incremental)
    });
    void a;
    void b;
    void c;
    void d;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ a: typeof a; b: typeof b; c: typeof c; d: typeof d; }} */ ({}) };
}
$$render_e50f2117;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e50f2117>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e50f2117>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

