// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_08b74697() {
    let $$props: Record<string, any> = {};
    void $$props;

    let name = $$props['name'];
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void name;
}
$$render_08b74697;
declare const __svn_component_default: import('svelte').Component<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>>;
export default __svn_component_default;

