// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_08b74697() {
    let $$props = /** @type {Record<string, any>} */ ({});
    void $$props;

    let name = $$props['name'];
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (name);
        }
    });
    void name;
    return { props: /** @type {any} */({}) };
}
$$render_08b74697;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_08b74697>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

