// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6cdf582f() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        __svn_any_as<import('svelte/elements').SvelteMediaTimeRange[]>(bind:buffered);
        __svn_any_as<import('svelte/elements').SvelteMediaTimeRange[]>(bind:seekable);
        __svn_any_as<import('svelte/elements').SvelteMediaTimeRange[]>(bind:played);
    }
    void __svn_tpl_check;
}
$$render_6cdf582f;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

