// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6cdf582f() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        width = null as any as HTMLElement['clientWidth'];
        height = null as any as HTMLElement['clientHeight'];
        offsetWidth = null as any as HTMLElement['offsetWidth'];
        offsetHeight = null as any as HTMLElement['offsetHeight'];
        duration = null as any as HTMLMediaElement['duration'];
        buffered = null as any as import('svelte/elements').SvelteMediaTimeRange[];
        seekable = null as any as import('svelte/elements').SvelteMediaTimeRange[];
        seeking = null as any as HTMLMediaElement['seeking'];
        played = null as any as import('svelte/elements').SvelteMediaTimeRange[];
        ended = null as any as HTMLMediaElement['ended'];
    }
    void __svn_tpl_check;
}
$$render_6cdf582f;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

