// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f62214bb() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, styles.);
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_f62214bb;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f62214bb>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f62214bb>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

