// === +page.svelte ===
// generated by svelte-check-native; do not edit
    import type { PageProps } from './$types';
async function $$render_025ab80d() {
    type $$Events = {};

                                              

    let { data, form }: PageProps = $props();

    const needsNumber = (n: number) => n;
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (data.title);
        }
        { svelteHTML.createElement("p", {});             (needsNumber(data.count));
        }
        { svelteHTML.createElement("p", {});             (needsNumber(data.title));
        }
        if ((form?.ok)) {
            void [form?.ok];
            { svelteHTML.createElement("span", {});             }
        }
    });
    void needsNumber;
    return { props: undefined as any as (PageProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_025ab80d;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_025ab80d>>['props'],
    Awaited<ReturnType<typeof $$render_025ab80d>>['exports'],
    Awaited<ReturnType<typeof $$render_025ab80d>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

