// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_be9ffc73() {

           let { name: rename } = { name: "world" };
    ;(async () => {
        // template type-check body (incremental)
    });
    void rename;
    return { props: /** @type {any} */({}) };
}
$$render_be9ffc73;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_be9ffc73>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

