// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_758fb137() {

           let [a,b,c] = [1,2,3];
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    void c;
    return { props: /** @type {any} */({}) };
}
$$render_758fb137;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_758fb137>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

