// === input.svelte ===
// generated by svelte-check-native; do not edit

  export { row };
const row = (n: number): ReturnType<import('svelte').Snippet> => { async () => {
    { svelteHTML.createElement("b", {});         (n);
    }
    };
    return __svn_any(0);
};
function $$render_e40e2c10() {

  let count = $state(0);
    ;(async () => {
        // template type-check body (incremental)
        __svn_ensure_snippet(row(count));
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_e40e2c10>>['props'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

