// === AllNested.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7b8fa947() {
    type $$Events = {};

    // Every leaf nested: upstream emits bare `Record<string, any>` —
    // no invented `user` requirement, no `age` prop key.
    let { user: { name, age } } = $props();
    void name;
    void age;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (Record<string, any>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_7b8fa947;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_7b8fa947>>['props'],
    Awaited<ReturnType<typeof $$render_7b8fa947>>['exports'],
    Awaited<ReturnType<typeof $$render_7b8fa947>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

// === input.svelte ===
// generated by svelte-check-native; do not edit
    import AllNested from './AllNested.svelte';
    import Nested from './Nested.svelte';
async function $$render_e40e2c10() {

                                               
                                         

    const u = { name: 'ada' };
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_150 = __svn_ensure_component(Nested);
            new __svn_C_150({ target: __svn_any(), props: {"user": (u), "age": (1), "extra": (2)} });
        }
        {
            const __svn_C_176 = __svn_ensure_component(AllNested);
            new __svn_C_176({ target: __svn_any(), props: {"user": ({ name: 'ada', age: 1 }), "whatever": "ok"} });
        }
    });
    void Nested;
    void u;
    void AllNested;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props']): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

// === Nested.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7bce2ba4() {
    type $$ComponentProps = {age: any} & Record<string, any>;
    type $$Events = {};

    // Untyped $props() with a nested destructure element. The
    // synthesised $$ComponentProps must be `{ age: any } &
    // Record<string, any>`: `age` survives as a prop key, the nested
    // `user` element widens the type instead of becoming an invented
    // required prop, and `name` never surfaces as a key.
    let { user: { name }, age }: $$ComponentProps = $props();
    void name;
    void age;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: __svn_$$bindings(), exports: undefined as any as ({}) };
}
$$render_7bce2ba4;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_7bce2ba4>>['props'],
    Awaited<ReturnType<typeof $$render_7bce2ba4>>['exports'],
    Awaited<ReturnType<typeof $$render_7bce2ba4>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

