// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { createEventDispatcher } from "svelte";
async function $$render_4a528901() {

                                                   

    const dispatch = createEventDispatcher();
    dispatch("mount", { input });
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("input", {
            "on:focus": undefined,
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_4a528901;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4a528901>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4a528901>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

