// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_bbc70e42() {

           let number1!: number
           let number2!: number
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        (number1);
        (number2);
        (number1 + number2);
    }
    void __svn_tpl_check;
    void number1;
    void number2;
}
$$render_bbc70e42;
declare const __svn_component_default: import('svelte').Component<Record<string, any>, { number1: number; number2: number; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>> & { number1: number; number2: number; };
export default __svn_component_default;

