// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_47fd19aa() {

           class Foo {};
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void Foo;
    return { props: /** @type {any} */({}) };
}
$$render_47fd19aa;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_47fd19aa>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

