// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_47fd19aa() {

           class Foo {};
    ;(async () => {
        // template type-check body (incremental)
    });
    void Foo;
    return { props: /** @type {{ Foo?: typeof Foo; }} */({}) };
}
$$render_47fd19aa;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_47fd19aa>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

