// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0f30816b() {
    ;(async () => {
        // template type-check body (incremental)
        /** @type {any} */ let __svn_action_attrs_0 = {};
        void __svn_action_attrs_0;
            const __svn_action_0 = __svn_ensure_action(blink(__svn_map_element_tag('h1')));
        { svelteHTML.createElement("h1", __svn_union(__svn_action_0), {});             void __svn_action_0;
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_0f30816b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0f30816b>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0f30816b>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

