// === input.svelte ===
// generated by svelte-check-native; do not edit
    type $$Events = {
        /**
         * Some *doc*
         */
        a: boolean;
        b: string;
        c;
    }
async function $$render_7d31ee4a() {

                     
           
                     
           
                   
                  
          
     
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_7d31ee4a;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_7d31ee4a>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_7d31ee4a>>['props'], Awaited<ReturnType<typeof $$render_7d31ee4a>>['events'], Awaited<ReturnType<typeof $$render_7d31ee4a>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_7d31ee4a>>['bindings'] } & Awaited<ReturnType<typeof $$render_7d31ee4a>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_7d31ee4a>>['props']): Awaited<ReturnType<typeof $$render_7d31ee4a>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_7d31ee4a>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent & { readonly __svn_events: $$Events } = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

