// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_27bf4bf4() {
$var
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    return { props: /** @type {any} */({}) };
}
$$render_27bf4bf4;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_27bf4bf4>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

