// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_5dcb960f() {

    const label: string = 'ok';
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             (label);
        }
    });
    void label;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_5dcb960f;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_5dcb960f>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_5dcb960f>>['props'], Awaited<ReturnType<typeof $$render_5dcb960f>>['events'], Awaited<ReturnType<typeof $$render_5dcb960f>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_5dcb960f>>['bindings'] } & Awaited<ReturnType<typeof $$render_5dcb960f>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_5dcb960f>>['props']): Awaited<ReturnType<typeof $$render_5dcb960f>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_5dcb960f>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

