// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_063ede7a<const T extends readonly string[]>() {

       let items!: T;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void items;
    return { props: undefined as any as ({ items: T; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as {} };
}
$$render_063ede7a;
declare class __svn_Render_063ede7a<const T extends readonly string[]> {
    props(): Awaited<ReturnType<typeof $$render_063ede7a<const T>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_063ede7a<const T>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_063ede7a<const T>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_063ede7a<const T>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_063ede7a<const T>>>['exports'];
}
declare const __svn_component_default: <const T extends readonly string[]>(__anchor: any, props: Partial<ReturnType<__svn_Render_063ede7a<const T>['props']>>) => { items: T; };
declare type __svn_component_default<const T extends readonly string[]> = import('svelte').SvelteComponent<ReturnType<__svn_Render_063ede7a<const T>['props']>> & { items: T; };
export default __svn_component_default;

