// === input.svelte ===
// generated by svelte-check-native; do not edit

    export const foo = _foo;
async function $$render_665a52b9() {
    /** @type {any} */ const _foo = /** @type {any} */ (undefined);
    void _foo;
    ;(async () => {
        // template type-check body (incremental)
        {
            const _foo = () => {
                return null;
            };
            void _foo;
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_665a52b9;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_665a52b9>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

