// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b690e7bd() {

    const items: number[] = [1, 2, 3];
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const __svn_each_unused of __svn_each_items(items)) {
            void __svn_each_unused;
        }
    }
    void __svn_tpl_check;
    void items;
}
$$render_b690e7bd;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

