// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_d9f25341() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        Input(__svn_any(), {type: "text"});
        Input(__svn_any(), {type: "text"});
        Input(__svn_any(), {type: "text"});
        Input(__svn_any(), {type: "text"});
    }
    void __svn_tpl_check;
}
$$render_d9f25341;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

