// === input.svelte ===
// generated by svelte-check-native; do not edit
    import type { Writable } from "svelte/store";
async function $$render_9827a5f8() {

                                                 
    
           let store: Writable<string[]> | null = null;
store = undefined as any;
    
    if ($store) {
        $store.length
    }
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void store;
}
$$render_9827a5f8;
declare const __svn_component_default: import('svelte').Component<Record<string, any>, { store: Writable<string[]> | null; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>> & { store: Writable<string[]> | null; };
export default __svn_component_default;

