// === input.svelte ===
// generated by svelte-check-native; do not edit

    let foo = true;
async function $$render_9abb519b() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const hoistable1: any = undefined;
            void hoistable1;
            const hoistable2: any = undefined;
            void hoistable2;
            /*svn_I*/(foo);
        }
    }
    void __svn_tpl_check;
    void foo;
}
$$render_9abb519b;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

