// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6aa75f08() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {
            "on:click-outside": undefined,
            "on:click-outside2": (() => 'hi'),
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_6aa75f08;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6aa75f08>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6aa75f08>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

