// === input.svelte ===
// generated by svelte-check-native; do not edit

    let value = 1;
declare const a: { [key: string]: any } & ((...args: any[]) => any);
declare const b: { [key: string]: any } & ((...args: any[]) => any);
    interface Dependency {
        a: number;
        b: typeof value;
    }
type $$ComponentProps = { a: Dependency, b: string };
async function $$render_07606356() {

                          
                  
                        
     

    let { a, b }: /*Ωignore_startΩ*/$$ComponentProps/*Ωignore_endΩ*/ = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
    return { props: undefined as any as ($$ComponentProps), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_07606356;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_07606356>>['props'],
    Awaited<ReturnType<typeof $$render_07606356>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

