// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0e3f1ff7() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("p", {});         }
    });
    return { props: /** @type {any} */({}) };
}
$$render_0e3f1ff7;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0e3f1ff7>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

