// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        const __svn_create_slot = __svn_create_create_slot();
        {
            __svn_create_slot("default", {  });
        }
        { svelteHTML.createElement("div", {});         }
        {
            __svn_create_slot("foo", { bar: bar, baz: `boo` });
        }
        { svelteHTML.createElement("p", {});         }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': {  }, 'foo': { bar: (bar), baz: ("boo") } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/**
 * @typedef {__SvnSvelte4SlotedProps<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e40e2c10>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

