// === input.svelte ===
// generated by svelte-check-native; do not edit
interface A {}
async function $$render_7a575470() {

                  
           let a!: A;
           let b: A = {};
b = undefined as any;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
}
$$render_7a575470;
declare const __svn_component_default: import('svelte').Component<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>, { a: A; b: A; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any> & __SvnSvelte4PropsWiden<Record<string, any>>> & { a: A; b: A; };
export default __svn_component_default;

