// GENERATED — do not edit. Run `cargo run -p xtask --bin regen-lint-catalog`.
//
// Source: .svelte-upstream/svelte/packages/svelte/messages/compile-warnings/*.md

#![allow(non_camel_case_types)]

/// All known compile-warning codes from `svelte/compiler`.
///
/// Variant name matches the upstream snake_case code verbatim so the
/// `as_str` round-trip is trivial and generated-code scope is tiny.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Code {
    a11y_accesskey,
    a11y_aria_activedescendant_has_tabindex,
    a11y_aria_attributes,
    a11y_autocomplete_valid,
    a11y_autofocus,
    a11y_click_events_have_key_events,
    a11y_consider_explicit_label,
    a11y_distracting_elements,
    a11y_figcaption_index,
    a11y_figcaption_parent,
    a11y_hidden,
    a11y_img_redundant_alt,
    a11y_incorrect_aria_attribute_type,
    a11y_incorrect_aria_attribute_type_boolean,
    a11y_incorrect_aria_attribute_type_id,
    a11y_incorrect_aria_attribute_type_idlist,
    a11y_incorrect_aria_attribute_type_integer,
    a11y_incorrect_aria_attribute_type_token,
    a11y_incorrect_aria_attribute_type_tokenlist,
    a11y_incorrect_aria_attribute_type_tristate,
    a11y_interactive_supports_focus,
    a11y_invalid_attribute,
    a11y_label_has_associated_control,
    a11y_media_has_caption,
    a11y_misplaced_role,
    a11y_misplaced_scope,
    a11y_missing_attribute,
    a11y_missing_content,
    a11y_mouse_events_have_key_events,
    a11y_no_abstract_role,
    a11y_no_interactive_element_to_noninteractive_role,
    a11y_no_noninteractive_element_interactions,
    a11y_no_noninteractive_element_to_interactive_role,
    a11y_no_noninteractive_tabindex,
    a11y_no_redundant_roles,
    a11y_no_static_element_interactions,
    a11y_positive_tabindex,
    a11y_role_has_required_aria_props,
    a11y_role_supports_aria_props,
    a11y_role_supports_aria_props_implicit,
    a11y_unknown_aria_attribute,
    a11y_unknown_role,
    animation_duplicate,
    animation_invalid_placement,
    animation_missing_key,
    attribute_avoid_is,
    attribute_contenteditable_dynamic,
    attribute_contenteditable_missing,
    attribute_global_event_reference,
    attribute_illegal_colon,
    attribute_invalid_event_handler,
    attribute_invalid_multiple,
    attribute_invalid_name,
    attribute_invalid_property_name,
    attribute_invalid_sequence_expression,
    attribute_invalid_type,
    attribute_quoted,
    attribute_unquoted_sequence,
    bidirectional_control_characters,
    bind_group_invalid_expression,
    bind_group_invalid_snippet_parameter,
    bind_invalid_each_rest,
    bind_invalid_expression,
    bind_invalid_name,
    bind_invalid_parens,
    bind_invalid_target,
    bind_invalid_value,
    bindable_invalid_location,
    block_empty,
    block_unexpected_character,
    component_invalid_directive,
    component_name_lowercase,
    const_tag_invalid_placement,
    constant_assignment,
    constant_binding,
    css_unused_selector,
    custom_element_props_identifier,
    dollar_binding_invalid,
    dollar_prefix_invalid,
    each_item_invalid_assignment,
    each_key_without_as,
    element_implicitly_closed,
    element_invalid_self_closing_tag,
    event_directive_deprecated,
    event_handler_invalid_component_modifier,
    event_handler_invalid_modifier,
    event_handler_invalid_modifier_combination,
    experimental_async,
    export_let_unused,
    global_reference_invalid,
    illegal_await_expression,
    illegal_element_attribute,
    js_parse_error,
    legacy_await_invalid,
    legacy_code,
    legacy_component_creation,
    legacy_export_invalid,
    legacy_reactive_statement_invalid,
    let_directive_invalid_placement,
    mixed_event_handler_syntaxes,
    module_illegal_default_export,
    node_invalid_placement,
    node_invalid_placement_ssr,
    non_reactive_update,
    options_deprecated_accessors,
    options_deprecated_immutable,
    options_missing_custom_element,
    options_removed_enable_sourcemap,
    options_removed_hydratable,
    options_removed_loop_guard_timeout,
    options_renamed_ssr_dom,
    perf_avoid_inline_class,
    perf_avoid_nested_class,
    props_duplicate,
    props_invalid_placement,
    reactive_declaration_invalid_placement,
    reactive_declaration_module_script_dependency,
    render_tag_invalid_call_expression,
    render_tag_invalid_spread_argument,
    script_context_deprecated,
    script_unknown_attribute,
    slot_attribute_duplicate,
    slot_attribute_invalid,
    slot_attribute_invalid_placement,
    slot_default_duplicate,
    slot_element_deprecated,
    slot_element_invalid_attribute,
    slot_element_invalid_name,
    slot_element_invalid_name_default,
    slot_snippet_conflict,
    snippet_conflict,
    snippet_invalid_rest_parameter,
    snippet_parameter_assignment,
    state_referenced_locally,
    store_rune_conflict,
    style_directive_invalid_modifier,
    svelte_body_illegal_attribute,
    svelte_boundary_invalid_attribute,
    svelte_boundary_invalid_attribute_value,
    svelte_component_deprecated,
    svelte_element_invalid_this,
    svelte_fragment_invalid_attribute,
    svelte_fragment_invalid_placement,
    svelte_head_illegal_attribute,
    svelte_meta_invalid_content,
    svelte_self_deprecated,
    svelte_self_invalid_placement,
    textarea_invalid_content,
    title_illegal_attribute,
    title_invalid_content,
    transition_conflict,
    transition_duplicate,
    typescript_invalid_feature,
    unknown_code,
}

impl Code {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::a11y_accesskey => "a11y_accesskey",
            Self::a11y_aria_activedescendant_has_tabindex => {
                "a11y_aria_activedescendant_has_tabindex"
            }
            Self::a11y_aria_attributes => "a11y_aria_attributes",
            Self::a11y_autocomplete_valid => "a11y_autocomplete_valid",
            Self::a11y_autofocus => "a11y_autofocus",
            Self::a11y_click_events_have_key_events => "a11y_click_events_have_key_events",
            Self::a11y_consider_explicit_label => "a11y_consider_explicit_label",
            Self::a11y_distracting_elements => "a11y_distracting_elements",
            Self::a11y_figcaption_index => "a11y_figcaption_index",
            Self::a11y_figcaption_parent => "a11y_figcaption_parent",
            Self::a11y_hidden => "a11y_hidden",
            Self::a11y_img_redundant_alt => "a11y_img_redundant_alt",
            Self::a11y_incorrect_aria_attribute_type => "a11y_incorrect_aria_attribute_type",
            Self::a11y_incorrect_aria_attribute_type_boolean => {
                "a11y_incorrect_aria_attribute_type_boolean"
            }
            Self::a11y_incorrect_aria_attribute_type_id => "a11y_incorrect_aria_attribute_type_id",
            Self::a11y_incorrect_aria_attribute_type_idlist => {
                "a11y_incorrect_aria_attribute_type_idlist"
            }
            Self::a11y_incorrect_aria_attribute_type_integer => {
                "a11y_incorrect_aria_attribute_type_integer"
            }
            Self::a11y_incorrect_aria_attribute_type_token => {
                "a11y_incorrect_aria_attribute_type_token"
            }
            Self::a11y_incorrect_aria_attribute_type_tokenlist => {
                "a11y_incorrect_aria_attribute_type_tokenlist"
            }
            Self::a11y_incorrect_aria_attribute_type_tristate => {
                "a11y_incorrect_aria_attribute_type_tristate"
            }
            Self::a11y_interactive_supports_focus => "a11y_interactive_supports_focus",
            Self::a11y_invalid_attribute => "a11y_invalid_attribute",
            Self::a11y_label_has_associated_control => "a11y_label_has_associated_control",
            Self::a11y_media_has_caption => "a11y_media_has_caption",
            Self::a11y_misplaced_role => "a11y_misplaced_role",
            Self::a11y_misplaced_scope => "a11y_misplaced_scope",
            Self::a11y_missing_attribute => "a11y_missing_attribute",
            Self::a11y_missing_content => "a11y_missing_content",
            Self::a11y_mouse_events_have_key_events => "a11y_mouse_events_have_key_events",
            Self::a11y_no_abstract_role => "a11y_no_abstract_role",
            Self::a11y_no_interactive_element_to_noninteractive_role => {
                "a11y_no_interactive_element_to_noninteractive_role"
            }
            Self::a11y_no_noninteractive_element_interactions => {
                "a11y_no_noninteractive_element_interactions"
            }
            Self::a11y_no_noninteractive_element_to_interactive_role => {
                "a11y_no_noninteractive_element_to_interactive_role"
            }
            Self::a11y_no_noninteractive_tabindex => "a11y_no_noninteractive_tabindex",
            Self::a11y_no_redundant_roles => "a11y_no_redundant_roles",
            Self::a11y_no_static_element_interactions => "a11y_no_static_element_interactions",
            Self::a11y_positive_tabindex => "a11y_positive_tabindex",
            Self::a11y_role_has_required_aria_props => "a11y_role_has_required_aria_props",
            Self::a11y_role_supports_aria_props => "a11y_role_supports_aria_props",
            Self::a11y_role_supports_aria_props_implicit => {
                "a11y_role_supports_aria_props_implicit"
            }
            Self::a11y_unknown_aria_attribute => "a11y_unknown_aria_attribute",
            Self::a11y_unknown_role => "a11y_unknown_role",
            Self::animation_duplicate => "animation_duplicate",
            Self::animation_invalid_placement => "animation_invalid_placement",
            Self::animation_missing_key => "animation_missing_key",
            Self::attribute_avoid_is => "attribute_avoid_is",
            Self::attribute_contenteditable_dynamic => "attribute_contenteditable_dynamic",
            Self::attribute_contenteditable_missing => "attribute_contenteditable_missing",
            Self::attribute_global_event_reference => "attribute_global_event_reference",
            Self::attribute_illegal_colon => "attribute_illegal_colon",
            Self::attribute_invalid_event_handler => "attribute_invalid_event_handler",
            Self::attribute_invalid_multiple => "attribute_invalid_multiple",
            Self::attribute_invalid_name => "attribute_invalid_name",
            Self::attribute_invalid_property_name => "attribute_invalid_property_name",
            Self::attribute_invalid_sequence_expression => "attribute_invalid_sequence_expression",
            Self::attribute_invalid_type => "attribute_invalid_type",
            Self::attribute_quoted => "attribute_quoted",
            Self::attribute_unquoted_sequence => "attribute_unquoted_sequence",
            Self::bidirectional_control_characters => "bidirectional_control_characters",
            Self::bind_group_invalid_expression => "bind_group_invalid_expression",
            Self::bind_group_invalid_snippet_parameter => "bind_group_invalid_snippet_parameter",
            Self::bind_invalid_each_rest => "bind_invalid_each_rest",
            Self::bind_invalid_expression => "bind_invalid_expression",
            Self::bind_invalid_name => "bind_invalid_name",
            Self::bind_invalid_parens => "bind_invalid_parens",
            Self::bind_invalid_target => "bind_invalid_target",
            Self::bind_invalid_value => "bind_invalid_value",
            Self::bindable_invalid_location => "bindable_invalid_location",
            Self::block_empty => "block_empty",
            Self::block_unexpected_character => "block_unexpected_character",
            Self::component_invalid_directive => "component_invalid_directive",
            Self::component_name_lowercase => "component_name_lowercase",
            Self::const_tag_invalid_placement => "const_tag_invalid_placement",
            Self::constant_assignment => "constant_assignment",
            Self::constant_binding => "constant_binding",
            Self::css_unused_selector => "css_unused_selector",
            Self::custom_element_props_identifier => "custom_element_props_identifier",
            Self::dollar_binding_invalid => "dollar_binding_invalid",
            Self::dollar_prefix_invalid => "dollar_prefix_invalid",
            Self::each_item_invalid_assignment => "each_item_invalid_assignment",
            Self::each_key_without_as => "each_key_without_as",
            Self::element_implicitly_closed => "element_implicitly_closed",
            Self::element_invalid_self_closing_tag => "element_invalid_self_closing_tag",
            Self::event_directive_deprecated => "event_directive_deprecated",
            Self::event_handler_invalid_component_modifier => {
                "event_handler_invalid_component_modifier"
            }
            Self::event_handler_invalid_modifier => "event_handler_invalid_modifier",
            Self::event_handler_invalid_modifier_combination => {
                "event_handler_invalid_modifier_combination"
            }
            Self::experimental_async => "experimental_async",
            Self::export_let_unused => "export_let_unused",
            Self::global_reference_invalid => "global_reference_invalid",
            Self::illegal_await_expression => "illegal_await_expression",
            Self::illegal_element_attribute => "illegal_element_attribute",
            Self::js_parse_error => "js_parse_error",
            Self::legacy_await_invalid => "legacy_await_invalid",
            Self::legacy_code => "legacy_code",
            Self::legacy_component_creation => "legacy_component_creation",
            Self::legacy_export_invalid => "legacy_export_invalid",
            Self::legacy_reactive_statement_invalid => "legacy_reactive_statement_invalid",
            Self::let_directive_invalid_placement => "let_directive_invalid_placement",
            Self::mixed_event_handler_syntaxes => "mixed_event_handler_syntaxes",
            Self::module_illegal_default_export => "module_illegal_default_export",
            Self::node_invalid_placement => "node_invalid_placement",
            Self::node_invalid_placement_ssr => "node_invalid_placement_ssr",
            Self::non_reactive_update => "non_reactive_update",
            Self::options_deprecated_accessors => "options_deprecated_accessors",
            Self::options_deprecated_immutable => "options_deprecated_immutable",
            Self::options_missing_custom_element => "options_missing_custom_element",
            Self::options_removed_enable_sourcemap => "options_removed_enable_sourcemap",
            Self::options_removed_hydratable => "options_removed_hydratable",
            Self::options_removed_loop_guard_timeout => "options_removed_loop_guard_timeout",
            Self::options_renamed_ssr_dom => "options_renamed_ssr_dom",
            Self::perf_avoid_inline_class => "perf_avoid_inline_class",
            Self::perf_avoid_nested_class => "perf_avoid_nested_class",
            Self::props_duplicate => "props_duplicate",
            Self::props_invalid_placement => "props_invalid_placement",
            Self::reactive_declaration_invalid_placement => {
                "reactive_declaration_invalid_placement"
            }
            Self::reactive_declaration_module_script_dependency => {
                "reactive_declaration_module_script_dependency"
            }
            Self::render_tag_invalid_call_expression => "render_tag_invalid_call_expression",
            Self::render_tag_invalid_spread_argument => "render_tag_invalid_spread_argument",
            Self::script_context_deprecated => "script_context_deprecated",
            Self::script_unknown_attribute => "script_unknown_attribute",
            Self::slot_attribute_duplicate => "slot_attribute_duplicate",
            Self::slot_attribute_invalid => "slot_attribute_invalid",
            Self::slot_attribute_invalid_placement => "slot_attribute_invalid_placement",
            Self::slot_default_duplicate => "slot_default_duplicate",
            Self::slot_element_deprecated => "slot_element_deprecated",
            Self::slot_element_invalid_attribute => "slot_element_invalid_attribute",
            Self::slot_element_invalid_name => "slot_element_invalid_name",
            Self::slot_element_invalid_name_default => "slot_element_invalid_name_default",
            Self::slot_snippet_conflict => "slot_snippet_conflict",
            Self::snippet_conflict => "snippet_conflict",
            Self::snippet_invalid_rest_parameter => "snippet_invalid_rest_parameter",
            Self::snippet_parameter_assignment => "snippet_parameter_assignment",
            Self::state_referenced_locally => "state_referenced_locally",
            Self::store_rune_conflict => "store_rune_conflict",
            Self::style_directive_invalid_modifier => "style_directive_invalid_modifier",
            Self::svelte_body_illegal_attribute => "svelte_body_illegal_attribute",
            Self::svelte_boundary_invalid_attribute => "svelte_boundary_invalid_attribute",
            Self::svelte_boundary_invalid_attribute_value => {
                "svelte_boundary_invalid_attribute_value"
            }
            Self::svelte_component_deprecated => "svelte_component_deprecated",
            Self::svelte_element_invalid_this => "svelte_element_invalid_this",
            Self::svelte_fragment_invalid_attribute => "svelte_fragment_invalid_attribute",
            Self::svelte_fragment_invalid_placement => "svelte_fragment_invalid_placement",
            Self::svelte_head_illegal_attribute => "svelte_head_illegal_attribute",
            Self::svelte_meta_invalid_content => "svelte_meta_invalid_content",
            Self::svelte_self_deprecated => "svelte_self_deprecated",
            Self::svelte_self_invalid_placement => "svelte_self_invalid_placement",
            Self::textarea_invalid_content => "textarea_invalid_content",
            Self::title_illegal_attribute => "title_illegal_attribute",
            Self::title_invalid_content => "title_invalid_content",
            Self::transition_conflict => "transition_conflict",
            Self::transition_duplicate => "transition_duplicate",
            Self::typescript_invalid_feature => "typescript_invalid_feature",
            Self::unknown_code => "unknown_code",
        }
    }

    pub fn try_from_str(s: &str) -> Option<Self> {
        match s {
            "a11y_accesskey" => Some(Self::a11y_accesskey),
            "a11y_aria_activedescendant_has_tabindex" => {
                Some(Self::a11y_aria_activedescendant_has_tabindex)
            }
            "a11y_aria_attributes" => Some(Self::a11y_aria_attributes),
            "a11y_autocomplete_valid" => Some(Self::a11y_autocomplete_valid),
            "a11y_autofocus" => Some(Self::a11y_autofocus),
            "a11y_click_events_have_key_events" => Some(Self::a11y_click_events_have_key_events),
            "a11y_consider_explicit_label" => Some(Self::a11y_consider_explicit_label),
            "a11y_distracting_elements" => Some(Self::a11y_distracting_elements),
            "a11y_figcaption_index" => Some(Self::a11y_figcaption_index),
            "a11y_figcaption_parent" => Some(Self::a11y_figcaption_parent),
            "a11y_hidden" => Some(Self::a11y_hidden),
            "a11y_img_redundant_alt" => Some(Self::a11y_img_redundant_alt),
            "a11y_incorrect_aria_attribute_type" => Some(Self::a11y_incorrect_aria_attribute_type),
            "a11y_incorrect_aria_attribute_type_boolean" => {
                Some(Self::a11y_incorrect_aria_attribute_type_boolean)
            }
            "a11y_incorrect_aria_attribute_type_id" => {
                Some(Self::a11y_incorrect_aria_attribute_type_id)
            }
            "a11y_incorrect_aria_attribute_type_idlist" => {
                Some(Self::a11y_incorrect_aria_attribute_type_idlist)
            }
            "a11y_incorrect_aria_attribute_type_integer" => {
                Some(Self::a11y_incorrect_aria_attribute_type_integer)
            }
            "a11y_incorrect_aria_attribute_type_token" => {
                Some(Self::a11y_incorrect_aria_attribute_type_token)
            }
            "a11y_incorrect_aria_attribute_type_tokenlist" => {
                Some(Self::a11y_incorrect_aria_attribute_type_tokenlist)
            }
            "a11y_incorrect_aria_attribute_type_tristate" => {
                Some(Self::a11y_incorrect_aria_attribute_type_tristate)
            }
            "a11y_interactive_supports_focus" => Some(Self::a11y_interactive_supports_focus),
            "a11y_invalid_attribute" => Some(Self::a11y_invalid_attribute),
            "a11y_label_has_associated_control" => Some(Self::a11y_label_has_associated_control),
            "a11y_media_has_caption" => Some(Self::a11y_media_has_caption),
            "a11y_misplaced_role" => Some(Self::a11y_misplaced_role),
            "a11y_misplaced_scope" => Some(Self::a11y_misplaced_scope),
            "a11y_missing_attribute" => Some(Self::a11y_missing_attribute),
            "a11y_missing_content" => Some(Self::a11y_missing_content),
            "a11y_mouse_events_have_key_events" => Some(Self::a11y_mouse_events_have_key_events),
            "a11y_no_abstract_role" => Some(Self::a11y_no_abstract_role),
            "a11y_no_interactive_element_to_noninteractive_role" => {
                Some(Self::a11y_no_interactive_element_to_noninteractive_role)
            }
            "a11y_no_noninteractive_element_interactions" => {
                Some(Self::a11y_no_noninteractive_element_interactions)
            }
            "a11y_no_noninteractive_element_to_interactive_role" => {
                Some(Self::a11y_no_noninteractive_element_to_interactive_role)
            }
            "a11y_no_noninteractive_tabindex" => Some(Self::a11y_no_noninteractive_tabindex),
            "a11y_no_redundant_roles" => Some(Self::a11y_no_redundant_roles),
            "a11y_no_static_element_interactions" => {
                Some(Self::a11y_no_static_element_interactions)
            }
            "a11y_positive_tabindex" => Some(Self::a11y_positive_tabindex),
            "a11y_role_has_required_aria_props" => Some(Self::a11y_role_has_required_aria_props),
            "a11y_role_supports_aria_props" => Some(Self::a11y_role_supports_aria_props),
            "a11y_role_supports_aria_props_implicit" => {
                Some(Self::a11y_role_supports_aria_props_implicit)
            }
            "a11y_unknown_aria_attribute" => Some(Self::a11y_unknown_aria_attribute),
            "a11y_unknown_role" => Some(Self::a11y_unknown_role),
            "animation_duplicate" => Some(Self::animation_duplicate),
            "animation_invalid_placement" => Some(Self::animation_invalid_placement),
            "animation_missing_key" => Some(Self::animation_missing_key),
            "attribute_avoid_is" => Some(Self::attribute_avoid_is),
            "attribute_contenteditable_dynamic" => Some(Self::attribute_contenteditable_dynamic),
            "attribute_contenteditable_missing" => Some(Self::attribute_contenteditable_missing),
            "attribute_global_event_reference" => Some(Self::attribute_global_event_reference),
            "attribute_illegal_colon" => Some(Self::attribute_illegal_colon),
            "attribute_invalid_event_handler" => Some(Self::attribute_invalid_event_handler),
            "attribute_invalid_multiple" => Some(Self::attribute_invalid_multiple),
            "attribute_invalid_name" => Some(Self::attribute_invalid_name),
            "attribute_invalid_property_name" => Some(Self::attribute_invalid_property_name),
            "attribute_invalid_sequence_expression" => {
                Some(Self::attribute_invalid_sequence_expression)
            }
            "attribute_invalid_type" => Some(Self::attribute_invalid_type),
            "attribute_quoted" => Some(Self::attribute_quoted),
            "attribute_unquoted_sequence" => Some(Self::attribute_unquoted_sequence),
            "bidirectional_control_characters" => Some(Self::bidirectional_control_characters),
            "bind_group_invalid_expression" => Some(Self::bind_group_invalid_expression),
            "bind_group_invalid_snippet_parameter" => {
                Some(Self::bind_group_invalid_snippet_parameter)
            }
            "bind_invalid_each_rest" => Some(Self::bind_invalid_each_rest),
            "bind_invalid_expression" => Some(Self::bind_invalid_expression),
            "bind_invalid_name" => Some(Self::bind_invalid_name),
            "bind_invalid_parens" => Some(Self::bind_invalid_parens),
            "bind_invalid_target" => Some(Self::bind_invalid_target),
            "bind_invalid_value" => Some(Self::bind_invalid_value),
            "bindable_invalid_location" => Some(Self::bindable_invalid_location),
            "block_empty" => Some(Self::block_empty),
            "block_unexpected_character" => Some(Self::block_unexpected_character),
            "component_invalid_directive" => Some(Self::component_invalid_directive),
            "component_name_lowercase" => Some(Self::component_name_lowercase),
            "const_tag_invalid_placement" => Some(Self::const_tag_invalid_placement),
            "constant_assignment" => Some(Self::constant_assignment),
            "constant_binding" => Some(Self::constant_binding),
            "css_unused_selector" => Some(Self::css_unused_selector),
            "custom_element_props_identifier" => Some(Self::custom_element_props_identifier),
            "dollar_binding_invalid" => Some(Self::dollar_binding_invalid),
            "dollar_prefix_invalid" => Some(Self::dollar_prefix_invalid),
            "each_item_invalid_assignment" => Some(Self::each_item_invalid_assignment),
            "each_key_without_as" => Some(Self::each_key_without_as),
            "element_implicitly_closed" => Some(Self::element_implicitly_closed),
            "element_invalid_self_closing_tag" => Some(Self::element_invalid_self_closing_tag),
            "event_directive_deprecated" => Some(Self::event_directive_deprecated),
            "event_handler_invalid_component_modifier" => {
                Some(Self::event_handler_invalid_component_modifier)
            }
            "event_handler_invalid_modifier" => Some(Self::event_handler_invalid_modifier),
            "event_handler_invalid_modifier_combination" => {
                Some(Self::event_handler_invalid_modifier_combination)
            }
            "experimental_async" => Some(Self::experimental_async),
            "export_let_unused" => Some(Self::export_let_unused),
            "global_reference_invalid" => Some(Self::global_reference_invalid),
            "illegal_await_expression" => Some(Self::illegal_await_expression),
            "illegal_element_attribute" => Some(Self::illegal_element_attribute),
            "js_parse_error" => Some(Self::js_parse_error),
            "legacy_await_invalid" => Some(Self::legacy_await_invalid),
            "legacy_code" => Some(Self::legacy_code),
            "legacy_component_creation" => Some(Self::legacy_component_creation),
            "legacy_export_invalid" => Some(Self::legacy_export_invalid),
            "legacy_reactive_statement_invalid" => Some(Self::legacy_reactive_statement_invalid),
            "let_directive_invalid_placement" => Some(Self::let_directive_invalid_placement),
            "mixed_event_handler_syntaxes" => Some(Self::mixed_event_handler_syntaxes),
            "module_illegal_default_export" => Some(Self::module_illegal_default_export),
            "node_invalid_placement" => Some(Self::node_invalid_placement),
            "node_invalid_placement_ssr" => Some(Self::node_invalid_placement_ssr),
            "non_reactive_update" => Some(Self::non_reactive_update),
            "options_deprecated_accessors" => Some(Self::options_deprecated_accessors),
            "options_deprecated_immutable" => Some(Self::options_deprecated_immutable),
            "options_missing_custom_element" => Some(Self::options_missing_custom_element),
            "options_removed_enable_sourcemap" => Some(Self::options_removed_enable_sourcemap),
            "options_removed_hydratable" => Some(Self::options_removed_hydratable),
            "options_removed_loop_guard_timeout" => Some(Self::options_removed_loop_guard_timeout),
            "options_renamed_ssr_dom" => Some(Self::options_renamed_ssr_dom),
            "perf_avoid_inline_class" => Some(Self::perf_avoid_inline_class),
            "perf_avoid_nested_class" => Some(Self::perf_avoid_nested_class),
            "props_duplicate" => Some(Self::props_duplicate),
            "props_invalid_placement" => Some(Self::props_invalid_placement),
            "reactive_declaration_invalid_placement" => {
                Some(Self::reactive_declaration_invalid_placement)
            }
            "reactive_declaration_module_script_dependency" => {
                Some(Self::reactive_declaration_module_script_dependency)
            }
            "render_tag_invalid_call_expression" => Some(Self::render_tag_invalid_call_expression),
            "render_tag_invalid_spread_argument" => Some(Self::render_tag_invalid_spread_argument),
            "script_context_deprecated" => Some(Self::script_context_deprecated),
            "script_unknown_attribute" => Some(Self::script_unknown_attribute),
            "slot_attribute_duplicate" => Some(Self::slot_attribute_duplicate),
            "slot_attribute_invalid" => Some(Self::slot_attribute_invalid),
            "slot_attribute_invalid_placement" => Some(Self::slot_attribute_invalid_placement),
            "slot_default_duplicate" => Some(Self::slot_default_duplicate),
            "slot_element_deprecated" => Some(Self::slot_element_deprecated),
            "slot_element_invalid_attribute" => Some(Self::slot_element_invalid_attribute),
            "slot_element_invalid_name" => Some(Self::slot_element_invalid_name),
            "slot_element_invalid_name_default" => Some(Self::slot_element_invalid_name_default),
            "slot_snippet_conflict" => Some(Self::slot_snippet_conflict),
            "snippet_conflict" => Some(Self::snippet_conflict),
            "snippet_invalid_rest_parameter" => Some(Self::snippet_invalid_rest_parameter),
            "snippet_parameter_assignment" => Some(Self::snippet_parameter_assignment),
            "state_referenced_locally" => Some(Self::state_referenced_locally),
            "store_rune_conflict" => Some(Self::store_rune_conflict),
            "style_directive_invalid_modifier" => Some(Self::style_directive_invalid_modifier),
            "svelte_body_illegal_attribute" => Some(Self::svelte_body_illegal_attribute),
            "svelte_boundary_invalid_attribute" => Some(Self::svelte_boundary_invalid_attribute),
            "svelte_boundary_invalid_attribute_value" => {
                Some(Self::svelte_boundary_invalid_attribute_value)
            }
            "svelte_component_deprecated" => Some(Self::svelte_component_deprecated),
            "svelte_element_invalid_this" => Some(Self::svelte_element_invalid_this),
            "svelte_fragment_invalid_attribute" => Some(Self::svelte_fragment_invalid_attribute),
            "svelte_fragment_invalid_placement" => Some(Self::svelte_fragment_invalid_placement),
            "svelte_head_illegal_attribute" => Some(Self::svelte_head_illegal_attribute),
            "svelte_meta_invalid_content" => Some(Self::svelte_meta_invalid_content),
            "svelte_self_deprecated" => Some(Self::svelte_self_deprecated),
            "svelte_self_invalid_placement" => Some(Self::svelte_self_invalid_placement),
            "textarea_invalid_content" => Some(Self::textarea_invalid_content),
            "title_illegal_attribute" => Some(Self::title_illegal_attribute),
            "title_invalid_content" => Some(Self::title_invalid_content),
            "transition_conflict" => Some(Self::transition_conflict),
            "transition_duplicate" => Some(Self::transition_duplicate),
            "typescript_invalid_feature" => Some(Self::typescript_invalid_feature),
            "unknown_code" => Some(Self::unknown_code),
            _ => None,
        }
    }
}

/// All known codes, alphabetically sorted.
pub const CODES: &[&str; 154] = &[
    "a11y_accesskey",
    "a11y_aria_activedescendant_has_tabindex",
    "a11y_aria_attributes",
    "a11y_autocomplete_valid",
    "a11y_autofocus",
    "a11y_click_events_have_key_events",
    "a11y_consider_explicit_label",
    "a11y_distracting_elements",
    "a11y_figcaption_index",
    "a11y_figcaption_parent",
    "a11y_hidden",
    "a11y_img_redundant_alt",
    "a11y_incorrect_aria_attribute_type",
    "a11y_incorrect_aria_attribute_type_boolean",
    "a11y_incorrect_aria_attribute_type_id",
    "a11y_incorrect_aria_attribute_type_idlist",
    "a11y_incorrect_aria_attribute_type_integer",
    "a11y_incorrect_aria_attribute_type_token",
    "a11y_incorrect_aria_attribute_type_tokenlist",
    "a11y_incorrect_aria_attribute_type_tristate",
    "a11y_interactive_supports_focus",
    "a11y_invalid_attribute",
    "a11y_label_has_associated_control",
    "a11y_media_has_caption",
    "a11y_misplaced_role",
    "a11y_misplaced_scope",
    "a11y_missing_attribute",
    "a11y_missing_content",
    "a11y_mouse_events_have_key_events",
    "a11y_no_abstract_role",
    "a11y_no_interactive_element_to_noninteractive_role",
    "a11y_no_noninteractive_element_interactions",
    "a11y_no_noninteractive_element_to_interactive_role",
    "a11y_no_noninteractive_tabindex",
    "a11y_no_redundant_roles",
    "a11y_no_static_element_interactions",
    "a11y_positive_tabindex",
    "a11y_role_has_required_aria_props",
    "a11y_role_supports_aria_props",
    "a11y_role_supports_aria_props_implicit",
    "a11y_unknown_aria_attribute",
    "a11y_unknown_role",
    "animation_duplicate",
    "animation_invalid_placement",
    "animation_missing_key",
    "attribute_avoid_is",
    "attribute_contenteditable_dynamic",
    "attribute_contenteditable_missing",
    "attribute_global_event_reference",
    "attribute_illegal_colon",
    "attribute_invalid_event_handler",
    "attribute_invalid_multiple",
    "attribute_invalid_name",
    "attribute_invalid_property_name",
    "attribute_invalid_sequence_expression",
    "attribute_invalid_type",
    "attribute_quoted",
    "attribute_unquoted_sequence",
    "bidirectional_control_characters",
    "bind_group_invalid_expression",
    "bind_group_invalid_snippet_parameter",
    "bind_invalid_each_rest",
    "bind_invalid_expression",
    "bind_invalid_name",
    "bind_invalid_parens",
    "bind_invalid_target",
    "bind_invalid_value",
    "bindable_invalid_location",
    "block_empty",
    "block_unexpected_character",
    "component_invalid_directive",
    "component_name_lowercase",
    "const_tag_invalid_placement",
    "constant_assignment",
    "constant_binding",
    "css_unused_selector",
    "custom_element_props_identifier",
    "dollar_binding_invalid",
    "dollar_prefix_invalid",
    "each_item_invalid_assignment",
    "each_key_without_as",
    "element_implicitly_closed",
    "element_invalid_self_closing_tag",
    "event_directive_deprecated",
    "event_handler_invalid_component_modifier",
    "event_handler_invalid_modifier",
    "event_handler_invalid_modifier_combination",
    "experimental_async",
    "export_let_unused",
    "global_reference_invalid",
    "illegal_await_expression",
    "illegal_element_attribute",
    "js_parse_error",
    "legacy_await_invalid",
    "legacy_code",
    "legacy_component_creation",
    "legacy_export_invalid",
    "legacy_reactive_statement_invalid",
    "let_directive_invalid_placement",
    "mixed_event_handler_syntaxes",
    "module_illegal_default_export",
    "node_invalid_placement",
    "node_invalid_placement_ssr",
    "non_reactive_update",
    "options_deprecated_accessors",
    "options_deprecated_immutable",
    "options_missing_custom_element",
    "options_removed_enable_sourcemap",
    "options_removed_hydratable",
    "options_removed_loop_guard_timeout",
    "options_renamed_ssr_dom",
    "perf_avoid_inline_class",
    "perf_avoid_nested_class",
    "props_duplicate",
    "props_invalid_placement",
    "reactive_declaration_invalid_placement",
    "reactive_declaration_module_script_dependency",
    "render_tag_invalid_call_expression",
    "render_tag_invalid_spread_argument",
    "script_context_deprecated",
    "script_unknown_attribute",
    "slot_attribute_duplicate",
    "slot_attribute_invalid",
    "slot_attribute_invalid_placement",
    "slot_default_duplicate",
    "slot_element_deprecated",
    "slot_element_invalid_attribute",
    "slot_element_invalid_name",
    "slot_element_invalid_name_default",
    "slot_snippet_conflict",
    "snippet_conflict",
    "snippet_invalid_rest_parameter",
    "snippet_parameter_assignment",
    "state_referenced_locally",
    "store_rune_conflict",
    "style_directive_invalid_modifier",
    "svelte_body_illegal_attribute",
    "svelte_boundary_invalid_attribute",
    "svelte_boundary_invalid_attribute_value",
    "svelte_component_deprecated",
    "svelte_element_invalid_this",
    "svelte_fragment_invalid_attribute",
    "svelte_fragment_invalid_placement",
    "svelte_head_illegal_attribute",
    "svelte_meta_invalid_content",
    "svelte_self_deprecated",
    "svelte_self_invalid_placement",
    "textarea_invalid_content",
    "title_illegal_attribute",
    "title_invalid_content",
    "transition_conflict",
    "transition_duplicate",
    "typescript_invalid_feature",
    "unknown_code",
];

/// The codes above that are compiler errors rather than warnings, kept
/// by hand next to the hand-added entries. A `svelte-ignore` comment only
/// knows the compiler's warning codes, so naming one of these reports
/// `unknown_code` and suppresses nothing.
pub const COMPILER_ERROR_CODES: &[&str] = &[
    "animation_duplicate",
    "animation_invalid_placement",
    "animation_missing_key",
    "attribute_contenteditable_dynamic",
    "attribute_contenteditable_missing",
    "attribute_invalid_event_handler",
    "attribute_invalid_multiple",
    "attribute_invalid_name",
    "attribute_invalid_sequence_expression",
    "attribute_invalid_type",
    "attribute_unquoted_sequence",
    "bind_group_invalid_expression",
    "bind_group_invalid_snippet_parameter",
    "bind_invalid_expression",
    "bind_invalid_name",
    "bind_invalid_parens",
    "bind_invalid_target",
    "bind_invalid_value",
    "bindable_invalid_location",
    "block_unexpected_character",
    "component_invalid_directive",
    "const_tag_invalid_placement",
    "constant_assignment",
    "constant_binding",
    "dollar_binding_invalid",
    "dollar_prefix_invalid",
    "each_item_invalid_assignment",
    "each_key_without_as",
    "event_handler_invalid_component_modifier",
    "event_handler_invalid_modifier",
    "event_handler_invalid_modifier_combination",
    "experimental_async",
    "global_reference_invalid",
    "illegal_await_expression",
    "illegal_element_attribute",
    "js_parse_error",
    "legacy_await_invalid",
    "legacy_export_invalid",
    "legacy_reactive_statement_invalid",
    "let_directive_invalid_placement",
    "mixed_event_handler_syntaxes",
    "module_illegal_default_export",
    "node_invalid_placement",
    "props_duplicate",
    "props_invalid_placement",
    "render_tag_invalid_call_expression",
    "render_tag_invalid_spread_argument",
    "slot_attribute_duplicate",
    "slot_attribute_invalid",
    "slot_attribute_invalid_placement",
    "slot_default_duplicate",
    "slot_element_invalid_attribute",
    "slot_element_invalid_name",
    "slot_element_invalid_name_default",
    "slot_snippet_conflict",
    "snippet_conflict",
    "snippet_invalid_rest_parameter",
    "snippet_parameter_assignment",
    "style_directive_invalid_modifier",
    "svelte_body_illegal_attribute",
    "svelte_boundary_invalid_attribute",
    "svelte_boundary_invalid_attribute_value",
    "svelte_fragment_invalid_attribute",
    "svelte_fragment_invalid_placement",
    "svelte_head_illegal_attribute",
    "svelte_meta_invalid_content",
    "svelte_self_invalid_placement",
    "textarea_invalid_content",
    "title_illegal_attribute",
    "title_invalid_content",
    "transition_conflict",
    "transition_duplicate",
    "typescript_invalid_feature",
];
