// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_253c43cc() {
    /** @type {any} */ const bar = /** @type {any} */ (undefined);
    void bar;

    let foo = true;
    bar;
    ;(async () => {
        // template type-check body (incremental)
        {
            const bar = () => {
                (foo);
                return null;
            };
            void bar;
        }
    });
    void foo;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_253c43cc;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_253c43cc>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_253c43cc>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

