// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f8f5930c() {

    const name: string = 'widget';
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:head", {});             { svelteHTML.createElement("style", {});             }
            { svelteHTML.createElement("script", {
                "type": `application/ld+json`,
            });
            }
        }
        { svelteHTML.createElement("svg", {});             { svelteHTML.createElement("style", {});             }
            { svelteHTML.createElement("style", {});             }
        }
        { svelteHTML.createElement("p", {});             (name);
        }
    });
    void name;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_f8f5930c;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_f8f5930c>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_f8f5930c>>['props'], Awaited<ReturnType<typeof $$render_f8f5930c>>['events'], Awaited<ReturnType<typeof $$render_f8f5930c>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_f8f5930c>>['bindings'] } & Awaited<ReturnType<typeof $$render_f8f5930c>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_f8f5930c>>['props']): Awaited<ReturnType<typeof $$render_f8f5930c>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_f8f5930c>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

