// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e40e2c10() {
    type $$Events = {};

	let el: HTMLInputElement | null = $state(null);
	if (el) el.focus();
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("input", {});             el = null as any as HTMLElementTagNameMap['input'];
        }
    });
    void el;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_e40e2c10>>['props'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'],
    Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

