// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_96849c5d() {

	       let foo: number = undefined
foo = undefined as any;
	       const bar: string = ''
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "accessors": (false),
        });
        }
    }
    void __svn_tpl_check;
    void foo;
    void bar;
    return { props: undefined as any as ({ foo?: number; bar?: string; }), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ foo: number; bar: string; }) };
}
$$render_96849c5d;
declare const __svn_component_default: import('svelte').Component<{ foo?: number; bar?: string; }, { foo: number; bar: string; }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ foo?: number; bar?: string; }> & { foo: number; bar: string; };
export default __svn_component_default;

