// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4a1879bf() {

           let a = '';
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    return { props: /** @type {{ a?: typeof a; }} */({}) };
}
$$render_4a1879bf;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4a1879bf>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

