// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_e5ad478b() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:boundary", {
            "onerror": (e => e),
        });
            {
                const failed = undefined;
                void failed;
                {
                    const __svn_C_27 = __svn_ensure_component(ComponentThatFails);
                    new __svn_C_27({ target: __svn_any(), props: {} });
                }
                {
                    void ((e: any) => {
                        { svelteHTML.createElement("p", {});                             (e);
                        }
                        void e;
                    });
                }
            }
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_e5ad478b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_e5ad478b>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

