// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ebd292b2() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const item of __svn_each_items(items)) {
            const i: number = 0;
            void item;
            void i;
        }
    }
    void __svn_tpl_check;
}
$$render_ebd292b2;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

