// === input.svelte ===
// generated by svelte-check-native; do not edit

    import { store1 } from './somewhere';
    const store2 = ''/*svn:ignore_start*/;let $store2 = __svn_store_get(store2);/*svn:ignore_end*/;
function $$render_e40e2c10() {
    /*svn:ignore_start*/;let $store1 = __svn_store_get(store1);/*svn:ignore_end*/
    ;(async () => {
        // template type-check body (incremental)
        $store1;
        $store2;
    });
    return { props: /** @type {Record<string, never>} */ ({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

