// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_15c46473() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {
            "is": `custom-element`,
            "camelCase": `true`,
            "kebab-case": `true`,
            "PascalCase": `true`,
            "snake_case": `true`,
        });
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_15c46473;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_15c46473>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_15c46473>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

