// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_edd507a7() {

    import A
    import C = require('');
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_edd507a7;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

