// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_42f07443() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {
            "on:click": (click),
        });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_42f07443;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_42f07443>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

