// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_31d2f31d() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("use", {
            "xlink:href": (test),
        });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_31d2f31d;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_31d2f31d>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

