// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_5c7bdfaa() {
    let $$props: Record<string, any> = {};
    void $$props;
 
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             ($$props['name']);
        }
    }
    void __svn_tpl_check;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as {}, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_5c7bdfaa;
declare const __svn_component_default: import('svelte').Component<Awaited<ReturnType<typeof $$render_5c7bdfaa>>['props'] & __SvnAllProps>;
declare type __svn_component_default = import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_5c7bdfaa>>['props'] & __SvnAllProps>;
export default __svn_component_default;

