// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { createEventDispatcher } from 'svelte';
async function $$render_a0e138e9() {
    type $$Events = { [__svn_K in keyof ({ "foo": any })]: CustomEvent<({ "foo": any })[__svn_K]> };

                                                   

    const dispatch = createEventDispatcher();
    dispatch('foo');
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "on:click": undefined,
        });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_a0e138e9;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a0e138e9>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

