// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_037def03() {


let b = __svn_invalidate(() => ({ a: 1 })); void b;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_037def03;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

