// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_037def03() {


let b = __svn_invalidate(() => ({ a: 1 })); void b;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_037def03;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_037def03>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_037def03>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

