// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_037def03() {


let b = __svn_invalidate(() => ({ a: 1 })); void b;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_037def03;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_037def03>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

