// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, shorthand);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, value);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, value);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `${value}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string${mixed}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string{mixed}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `${mixed}string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string${mixed}string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `template${literal}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, shorthand);
        }
    });
    return { props: /** @type {Record<string, never>} */ ({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

