// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_96f6c695() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});         }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, value);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, value);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `${value}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string${mixed}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string{mixed}`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `${mixed}string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `string${mixed}string`);
        }
        { svelteHTML.createElement("div", {});             __svn_ensure_type(String, Number, `template${literal}`);
        }
        { svelteHTML.createElement("div", {});         }
    });
    return { props: /** @type {any} */({}) };
}
$$render_96f6c695;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_96f6c695>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

