// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0aec257e() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Button);
            new __svn_C_0({ target: __svn_any(), props: {} satisfies InstanceType<typeof __svn_C_0>['$$prop_def'] });
        }
    }
    void __svn_tpl_check;
}
$$render_0aec257e;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

