// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6270ac78() {
    let $$slots = /** @type {Record<string, boolean | undefined>} */ ({});
    void $$slots;

    let name = $$slots.foo;
    let dashedName = $$slots['dashed-name'];
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (name);
        }
    });
    void name;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'foo': {  }, 'dashed-name': {  }, 'default': {  } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_6270ac78;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6270ac78>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6270ac78>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

