// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6d46058b() {

	const config = { branding: { primaryColor: '#012345' } },
		branding = config?.branding;

	const cssString = `<style>:root {--primary-color: ${
		branding?.primaryColor ?? '#ABCDEF'
	};}</style>`;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_6d46058b;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_6d46058b>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

