// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_04fb2c94() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Comp);
            new __svn_C_0({ target: __svn_any(), props: {multilineattr: "hello\nworld"} });
        }
        {
            const __svn_C_25 = __svn_ensure_component(Comp);
            new __svn_C_25({ target: __svn_any(), props: {multilineattr: "he`llo\nworld"} });
        }
    }
    void __svn_tpl_check;
}
$$render_04fb2c94;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

