// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_04fb2c94() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        void ({multilineattr: "hello\nworld"} satisfies Partial<__SvnComponentProps<typeof Comp>>);
        void ({multilineattr: "he`llo\nworld"} satisfies Partial<__SvnComponentProps<typeof Comp>>);
    }
    void __svn_tpl_check;
}
$$render_04fb2c94;
declare const __svn_component_default: any;
declare type __svn_component_default = any;
export default __svn_component_default;

