// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { getUser, getCount } from './data.remote.ts';
async function $$render_e40e2c10() {

    // Import from a `.remote.ts` file — these are SvelteKit's
    // experimental remote functions. svelte-check-native treats
    // them as plain TypeScript modules; type-checking the import +
    // call should "just work" because the bundler resolves the
    // explicit `.remote.ts` extension and tsgo follows the export
    // signatures.
                                                         

    const user = await getUser('1');
    const count = await getCount();

    // Type narrowing: `user.name` is `string`, `user.missing` would
    // be a TS2339 error — this asserts the cross-file types flow.
    const greeting: string = `Hello, ${user.name}!`;
    const total: number = count + 1;
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("p", {});             (greeting);
        }
        { svelteHTML.createElement("p", {});             (total);
        }
    });
    void greeting;
    void total;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props']): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

