// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const A: { [key: string]: any } & ((...args: any[]) => any);
declare const B: { [key: string]: any } & ((...args: any[]) => any);
declare const C: { [key: string]: any } & ((...args: any[]) => any);
    interface $$Events {
        /**
         * Some doc
         */
        [A]: boolean;
        [B]: string;
        [C];
    }
async function $$render_d1f99cf5() {

    const A = 'a';
    const B = 'b', C = 'c';
                        
           
                   
           
                     
                    
            
     
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    return { props: undefined as any as (Record<string, any>), events: undefined as any as $$Events, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_d1f99cf5;
declare const __svn_component_default: import('svelte').Component<Awaited<ReturnType<typeof $$render_d1f99cf5>>['props']> & { readonly __svn_events: $$Events };
declare type __svn_component_default = import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_d1f99cf5>>['props']>;
export default __svn_component_default;

