// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ddc80822() {

    let callback = (id) => undefined;
    class B {
        constructor(id) { }

        method(id) { }

        set id(id) { }
    }

    let { id } = __svn_invalidate(() => ({ id: '' })); void id;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}) };
}
$$render_ddc80822;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ddc80822>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

