// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ddc80822() {

    let callback = (id) => undefined;
    class B {
        constructor(id) { }

        method(id) { }

        set id(id) { }
    }

    let { id } = __svn_invalidate(() => ({ id: '' })); void id;
    ;(async () => {
        // template type-check body (incremental)
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_ddc80822;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ddc80822>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ddc80822>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

