// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_1043e2cd() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
}
$$render_1043e2cd;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

