// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_0ae9a766() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (Promise.);
        ;(async () => {
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }); }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_0ae9a766;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0ae9a766>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_0ae9a766>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

