// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_031ccee2() {

    let name1 = "world"
    let name2

    let rename1 = '';
    let rename2;

    class Foo {}
    function bar() {}
    const baz = '';

    class RenameFoo {}
    function renamebar() {}
    const renamebaz = '';

                                                                                                                                                                
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void name1;
    void name2;
    void rename1;
    void rename2;
    void Foo;
    void bar;
    void baz;
    void RenameFoo;
    void renamebar;
    void renamebaz;
}
$$render_031ccee2;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

