// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        /** @type {[() => any, (v: any) => void]} */ let __svn_bind_pair_0 = [() => undefined, () => {}];
        void __svn_bind_pair_0;
        /** @type {[() => any, (v: any) => void]} */ let __svn_bind_pair_1 = [() => undefined, () => {}];
        void __svn_bind_pair_1;
        /** @type {[() => any, (v: any) => void]} */ let __svn_bind_pair_2 = [() => undefined, () => {}];
        void __svn_bind_pair_2;
        /** @type {[() => any, (v: any) => void]} */ let __svn_bind_pair_3 = [() => undefined, () => {}];
        void __svn_bind_pair_3;
        { svelteHTML.createElement("div", {});             ( set)(null as any as HTMLElementTagNameMap['div']);
        }
        { svelteHTML.createElement("div", {});             ( new_v => v = new_v)(null as any as HTMLElementTagNameMap['div']);
        }
        {
            const __svn_C_54 = __svn_ensure_component(Input);
            const __svn_inst_54 = new __svn_C_54({ target: __svn_any(), props: {} });
            ( set)(__svn_inst_54);
        }
        {
            const __svn_C_7a = __svn_ensure_component(Input);
            const __svn_inst_7a = new __svn_C_7a({ target: __svn_any(), props: {} });
            ( new_v => v = new_v)(__svn_inst_7a);
        }
    });
    return { props: /** @type {Record<string, never>} */ ({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

