// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f9263703() {

	let i = 0;
	let undoStack = [[]];
	let circles = [];
	let selected;
	let adjusting = false;
	let adjusted = false;

	function handleClick(event) {
		if (adjusting) {
			adjusting = false;

			// if circle was adjusted,
			// push to the stack
			if (adjusted) push();
			return;
		}

		const circle = {
			cx: event.clientX,
			cy: event.clientY,
			r: 50
		};

		circles = circles.concat(circle);
		selected = circle;

		push();
	}

	function adjust(event) {
		selected.r = +event.target.value;
		circles = circles;
		adjusted = true;
	}

	function select(circle, event) {
		if (!adjusting) {
			event.stopPropagation();
			selected = circle;
		}
	}

	function push() {
		const newUndoStack = undoStack.slice(0, ++i);
		newUndoStack.push(clone(circles));
		undoStack = newUndoStack;
	}

	function travel(d) {
		circles = clone(undoStack[i += d]);
		adjusting = false;
	}

	function clone(circles) {
		return circles.map(({ cx, cy, r }) => ({ cx, cy, r }));
	}
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const circle of __svn_each_items(circles)) {
            void circle;
        }
        if ((adjusting)) {
            void [adjusting];
            (selected.cx);
            (selected.cy);
        }
    }
    void __svn_tpl_check;
    void travel;
    void i;
    void undoStack;
    void handleClick;
    void circles;
    void select;
    void adjusting;
    void selected;
    void adjust;
}
$$render_f9263703;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

