// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9a2c7966() {

           let world = "name"
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (world);
        }
    });
    void world;
    return { props: /** @type {{ world?: typeof world; }} */({}) };
}
$$render_9a2c7966;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_9a2c7966>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

