// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9500b63a() {
    ;(async () => {
        // template type-check body (incremental)
        { const $$_promise = (promise);
        ;(async () => {
            const $$_await = await $$_promise; const value = $$_await;
            void value;
        }); }
        {
            const err = undefined;
            void err;
        }
        { const $$_promise = (promise2);
        ;(async () => {
            const $$_await = await $$_promise; const { b } = $$_await;
            void b;
        }); }
    });
    return { props: /** @type {any} */({}) };
}
$$render_9500b63a;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_9500b63a>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

