// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_a82beb00() {
    ;(async () => {
        // template type-check body (incremental)
        { const __svn_each_arr = __svn_each_items(items); for (const items of __svn_each_arr) {
            void items;
        }
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': { a: /** @type {(__SvnEachItem<typeof items>)} */ (/** @type {any} */ (null)) } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_a82beb00;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a82beb00>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_a82beb00>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

