// === input.svelte ===
// generated by svelte-check-native; do not edit
declare const bye: { [key: string]: any } & ((...args: any[]) => any);
    import { createEventDispatcher } from "svelte";
    type Events = {
        hi: boolean;
        bye: boolean;
        btn: string;
    };
async function $$render_6194130b() {

                                                   

                   
                    
                     
                    
      

    const dispatch = createEventDispatcher<Events>();

    dispatch('hi', true);

    function bye() {
        const bla = 'bye';
        dispatch(bla, false);
    }
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("button", {
            "on:click": (() => dispatch('btn', '')),
        });
        }
    });
    void dispatch;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_6194130b;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_6194130b>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_6194130b>>['props'], Awaited<ReturnType<typeof $$render_6194130b>>['events'], Awaited<ReturnType<typeof $$render_6194130b>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_6194130b>>['bindings'] } & Awaited<ReturnType<typeof $$render_6194130b>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_6194130b>>['props']): Awaited<ReturnType<typeof $$render_6194130b>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_6194130b>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

