// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4160f2ef() {

  let tag = 'div';
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement((tag), {});         }
        {
        }
        { svelteHTML.createElement((tag ? 'a' : 'b'), {});         }
        { svelteHTML.createElement((tag), {});             (tag);
        }
        { svelteHTML.createElement((tag), {
            "on:click": (() => tag),
        });
        }
        { svelteHTML.createElement(('a'), {
            "href": `https://kit.svelte.dev`,
        });
        }
    });
    void tag;
    return { props: /** @type {any} */({}) };
}
$$render_4160f2ef;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4160f2ef>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

