// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_4160f2ef() {

  let tag = 'div';
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement((tag), {});         }
        {
        }
        { svelteHTML.createElement((tag ? 'a' : 'b'), {});         }
        { svelteHTML.createElement((tag), {});             (tag);
        }
        { svelteHTML.createElement((tag), {
            "on:click": (() => tag),
        });
        }
        { svelteHTML.createElement(('a'), {
            "data-sveltekit-preload-data": true,
            "href": `https://kit.svelte.dev`,
        });
        }
    });
    void tag;
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_4160f2ef;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4160f2ef>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_4160f2ef>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

