// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_19f891e5() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            let foo: any;
            void foo;
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_19f891e5;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_19f891e5>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

