// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_01d4c0b9() {

	let {...props} = $props();
	let id = $props.id();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        (id);
        (props);
    }
    void __svn_tpl_check;
    void props;
    void id;
}
$$render_01d4c0b9;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

