// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { dev } from '$app/environment';
    import { page } from '$app/state';
async function $$render_4feca29a() {

                                           
                                      
    ;(async () => {
        // template type-check body (incremental)
        (dev);
        (page.url.pathname);
    });
    void dev;
    void page;
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_4feca29a;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_4feca29a>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_4feca29a>>['props'], Awaited<ReturnType<typeof $$render_4feca29a>>['events'], Awaited<ReturnType<typeof $$render_4feca29a>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_4feca29a>>['bindings'] } & Awaited<ReturnType<typeof $$render_4feca29a>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_4feca29a>>['props']): Awaited<ReturnType<typeof $$render_4feca29a>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_4feca29a>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

