// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_34fb20f4() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        for (const item of __svn_each_items(someObject?.items)) {
            void item;
        }
    }
    void __svn_tpl_check;
}
$$render_34fb20f4;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
export default __svn_component_default;

