// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ef638edf() {

    let name = "world"
    let name2 = "world"
                                             
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "runes": true,
        });
        }
    });
    void name;
    void name2;
    return { props: /** @type {{ name3?: typeof name; name4?: typeof name2; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_ef638edf;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ef638edf>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ef638edf>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

