// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_178afe2e() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("div", {});             (obj.);
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_178afe2e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_178afe2e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

