// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_79986fd7() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             (your?.name ?? 'Unknown');
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_79986fd7;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_79986fd7>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

