// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_85d5a1f5() {
    ;(async () => {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Me);
            new __svn_C_0({ target: __svn_any(), props: {"f": `${$s} `} });
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_85d5a1f5;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_85d5a1f5>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

