// === input.svelte ===
// generated by svelte-check-native; do not edit
    import { createEventDispatcher } from 'svelte';
async function $$render_94f45523<A, B extends keyof A, C extends boolean>() {

                                                   

           let a!: A;
           let b!: B;
           let c!: C;

    const dispatch = createEventDispatcher<{a: A}>();

           function getA() {
        return a;
    }
    ;(async () => {
        // template type-check body (incremental)
    });
    void c;
    void a;
    void b;
    void getA;
    return { props: undefined as any as ({ a: A; b: B; c: C; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: { 'default': { c: (c) } }, bindings: undefined as any as string, exports: undefined as any as ({ a: A; b: B; c: C; getA: () => void; }) };
}
$$render_94f45523;
declare class __svn_Render_94f45523<A, B extends keyof A, C extends boolean> {
    props(): Awaited<ReturnType<typeof $$render_94f45523<A, B, C>>>['props'];
    events(): Awaited<ReturnType<typeof $$render_94f45523<A, B, C>>>['events'];
    slots(): Awaited<ReturnType<typeof $$render_94f45523<A, B, C>>>['slots'];
    bindings(): Awaited<ReturnType<typeof $$render_94f45523<A, B, C>>>['bindings'];
    exports(): Awaited<ReturnType<typeof $$render_94f45523<A, B, C>>>['exports'];
}
interface $$IsomorphicComponent {
    new <A, B extends keyof A, C extends boolean>(options: import('svelte').ComponentConstructorOptions<Partial<ReturnType<__svn_Render_94f45523<A, B, C>['props']> & __SvnSvelte4PropsWiden<{ a: A; b: B; c: C; }>> & { children?: any }>): import('svelte').SvelteComponent<Partial<ReturnType<__svn_Render_94f45523<A, B, C>['props']> & __SvnSvelte4PropsWiden<{ a: A; b: B; c: C; }>>, ReturnType<__svn_Render_94f45523<A, B, C>['events']>, ReturnType<__svn_Render_94f45523<A, B, C>['slots']>> & { $$bindings?: ReturnType<__svn_Render_94f45523<A, B, C>['bindings']> } & ReturnType<__svn_Render_94f45523<A, B, C>['exports']>;
    <A, B extends keyof A, C extends boolean>(internal: unknown, props: Partial<ReturnType<__svn_Render_94f45523<A, B, C>['props']> & __SvnSvelte4PropsWiden<{ a: A; b: B; c: C; }>> & { children?: any }): ReturnType<__svn_Render_94f45523<A, B, C>['exports']> & { $set?: any; $on?: any };
    z_$$bindings?: ReturnType<__svn_Render_94f45523<any, any, any>['bindings']>;
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default<A, B extends keyof A, C extends boolean> = InstanceType<typeof __svn_component_default<A, B, C>>;
export default __svn_component_default;

