// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b08c173d() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            let n: any;
            void n;
            let thing: any;
            void thing;
            let whatever: any;
            void whatever;
            {
                const __svn_C_0 = __svn_ensure_component(Component);
                new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_b08c173d;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b08c173d>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

