// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_b08c173d() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            const __svn_inst_0 = new __svn_C_0({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, name: n, thing, whatever: { bla } } = __svn_inst_0.$$slot_def.default; $$_$$;
            }
        }
    }
    return { props: /** @type {any} */({}) };
}
$$render_b08c173d;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_b08c173d>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

