// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {
    ;(async () => {
        // template type-check body (incremental)
        const __svn_create_slot = __svn_create_create_slot();
        {
            const __svn_C_0 = __svn_ensure_component(Component);
            const __svn_inst_0 = new __svn_C_0({ target: __svn_any(), props: {} });
            {
                const { /*Ωignore_startΩ*/$$_$$/*Ωignore_endΩ*/, name: n, thing, whatever: { bla } } = __svn_inst_0.$$slot_def.default; $$_$$;
                {
                    __svn_create_slot("default", { n, thing, bla });
                }
            }
        }
    });
    return { props: /** @type {any} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: { 'default': { n: (__svn_instance_of(Component).$$slot_def['default'].name), thing: (__svn_instance_of(Component).$$slot_def['default'].thing), bla: ((({ bla }) => bla)(__svn_instance_of(Component).$$slot_def['default'].whatever)) } }, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_e40e2c10;
/** @type {__SvnIsomorphicComponent<__SvnSvelte4SlotedProps<__SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>, __SvnExpand<__SvnPropsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], __SvnExpand<__SvnSlotsAnyFallback<Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']>>, Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'], Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings']>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {InstanceType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

