// === +page.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_f7f0c7ab() {

           let data = /** @type {import('./$types.js').PageData} */ (/** @type {any} */ (null));
           let form = /** @type {import('./$types.js').ActionData} */ (/** @type {any} */ (null));
           const snapshot = {};
    ;(async () => {
        // template type-check body (incremental)
    });
    void data;
    void form;
    void snapshot;
    return { props: /** @type {{ data: any; form: any; snapshot?: typeof snapshot; }} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: /** @type {{ data: typeof data; form: typeof form; snapshot: typeof snapshot; }} */ ({}) };
}
$$render_f7f0c7ab;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f7f0c7ab>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_f7f0c7ab>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

