// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ba148a9e() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Dotted.ComponentName);
            new __svn_C_0({ target: __svn_any(), props: {} });
        }
        {
            const __svn_C_19 = __svn_ensure_component(Dotted.ComponentName);
            new __svn_C_19({ target: __svn_any(), props: {} });
        }
    }
    void __svn_tpl_check;
    return { props: /** @type {any} */({}) };
}
$$render_ba148a9e;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_ba148a9e>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
const __svn_component_default = /** @type {any} */ (null);
export default __svn_component_default;

