// === input.svelte ===
// generated by svelte-check-native; do not edit
import Test from './Test.svelte';
async function $$render_460d82f0() {

                                      
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        {
            const __svn_C_0 = __svn_ensure_component(Test);
            new __svn_C_0({ target: __svn_any(), props: {b: "6"} satisfies InstanceType<typeof __svn_C_0>['$$prop_def'] });
        }
    }
    void __svn_tpl_check;
    void Test;
}
$$render_460d82f0;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

