// === input.svelte ===
// generated by svelte-check-native; do not edit
/** @typedef {{props: any}} $$ComponentProps */
async function $$render_26417913() {

	let { props } = $props();
	let id = $props.id();
    ;(async () => {
        // template type-check body (incremental)
        (id);
        (props);
    });
    void id;
    return { props: /** @type {$$ComponentProps} */({}), events: /** @type {{ [evt: string]: CustomEvent<any> }} */ ({}), slots: {}, bindings: /** @type {string} */ (''), exports: {} };
}
$$render_26417913;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_26417913>>['props']} __SvnDefaultProps
 */
/**
 * @typedef {Awaited<ReturnType<typeof $$render_26417913>>['exports']} __SvnDefaultExports
 */
/** @type {import('svelte').Component<__SvnDefaultProps, __SvnDefaultExports>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

