// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_26417913() {

	let { props } = $props();
	let id = $props.id();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        /*svn_I*/(id);
        /*svn_I*/(props);
    }
    void __svn_tpl_check;
    void props;
    void id;
}
$$render_26417913;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

