// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_6b1a6441<T>() {

    let { a, b }: { a: T, b: string } = $props();
    let x = $state<T>(0);
    let y = $derived(x * 2);
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void a;
    void b;
}
$$render_6b1a6441;
declare const __svn_component_default: import('svelte').Component<{ a: T, b: string }>;
declare type __svn_component_default = import('svelte').SvelteComponent<{ a: T, b: string }>;
export default __svn_component_default;

