// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_7737f456() {
    ;(async () => {
        // template type-check body (incremental)
        { svelteHTML.createElement("h1", {});             __svn_ensure_transition(blink(__svn_map_element_tag('h1')));
        }
        { svelteHTML.createElement("h1", {});             __svn_ensure_transition(blink(__svn_map_element_tag('h1')));
        }
        { svelteHTML.createElement("h1", {});             __svn_ensure_transition(blink(__svn_map_element_tag('h1')));
        }
    });
    return { props: /** @type {any} */({}) };
}
$$render_7737f456;
/**
 * @typedef {Awaited<ReturnType<typeof $$render_7737f456>>['props']} __SvnDefaultProps
 */
/** @type {import('svelte').Component<__SvnDefaultProps>} */
export const __svn_component_default = /** @type {any} */ (null);
/** @typedef {ReturnType<typeof __svn_component_default>} __svn_component_default */
export default __svn_component_default;

