// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_ddf2ba9e() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        if ((hello && hello1)) {
            void [hello, hello1];
            {
                let hello: any;
                void hello;
                {
                    const __svn_C_1a = __svn_ensure_component(Comp);
                    new __svn_C_1a({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                }
                {
                    let hello: any;
                    void hello;
                    {
                        const __svn_C_43 = __svn_ensure_component(Comp);
                        new __svn_C_43({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                    }
                    if ((hello)) {
                        void [hello];
                    }
                }
                {
                    let hello: any;
                    void hello;
                    {
                        const __svn_C_ae = __svn_ensure_component(Comp);
                        new __svn_C_ae({ target: __svn_any(), props: {hello, children: () => __svn_snippet_return()} });
                    }
                    if ((hello)) {
                        void [hello];
                    }
                }
                {
                    let hello: any;
                    void hello;
                    if ((hello)) {
                        void [hello];
                    }
                }
                {
                    let hello: any;
                    void hello;
                    if ((hello)) {
                        void [hello];
                    }
                }
                {
                    let hello: any;
                    void hello;
                    {
                        const __svn_C_223 = __svn_ensure_component(Comp);
                        new __svn_C_223({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                    }
                    if ((hello)) {
                        void [hello];
                    }
                }
                if ((hello)) {
                    void [hello];
                    {
                        let hello: any;
                        void hello;
                        {
                            const __svn_C_2b4 = __svn_ensure_component(Comp);
                            new __svn_C_2b4({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                        }
                        if ((hello)) {
                            void [hello];
                        }
                    }
                    {
                        let foo: any;
                        void foo;
                        {
                            const __svn_C_333 = __svn_ensure_component(Comp);
                            new __svn_C_333({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                        }
                        const hello = foo;
                        void hello;
                        if ((hello)) {
                            void [hello];
                        }
                    }
                }
            }
            if ((hi && bye)) {
                void [hi, bye];
                {
                    let bye: any;
                    void bye;
                    {
                        const __svn_C_3ff = __svn_ensure_component(Comp);
                        new __svn_C_3ff({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                    }
                }
            } else if ((cool)) {
                void [cool];
                {
                    const __svn_C_452 = __svn_ensure_component(Comp);
                    new __svn_C_452({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                }
                {
                    let cool: any;
                    void cool;
                    let hello: any;
                    void hello;
                }
            } else {
                {
                    const __svn_C_4da = __svn_ensure_component(Comp);
                    new __svn_C_4da({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
                }
                {
                    let hello: any;
                    void hello;
                    let other: any;
                    void other;
                }
            }
        }
        {
            let hello: any;
            void hello;
            {
                const __svn_C_56f = __svn_ensure_component(Comp);
                new __svn_C_56f({ target: __svn_any(), props: {children: () => __svn_snippet_return()} });
            }
            if ((hello && bye)) {
                void [hello, bye];
            } else if ((hello && bye)) {
                void [hello, bye];
            } else {
            }
            {
                let hello: any;
                void hello;
                if ((hello && bye)) {
                    void [hello, bye];
                } else if ((hello && bye)) {
                    void [hello, bye];
                } else {
                }
            }
            {
                let hello: any;
                void hello;
                if ((hello && bye)) {
                    void [hello, bye];
                } else if ((hello && bye)) {
                    void [hello, bye];
                } else {
                }
            }
            {
                let foo: any;
                void foo;
                const hello = foo;
                void hello;
                if ((hello && bye)) {
                    void [hello, bye];
                } else if ((hello && bye)) {
                    void [hello, bye];
                } else {
                }
            }
        }
    }
    void __svn_tpl_check;
}
$$render_ddf2ba9e;
declare const __svn_component_default: import('svelte').Component<Record<string, any>>;
declare type __svn_component_default = import('svelte').SvelteComponent<Record<string, any>>;
export default __svn_component_default;

