// === input.svelte ===
// generated by svelte-check-native; do not edit
    type A = $$Generic;
async function $$render_491a605d() {

                       

           let a!: A;
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        { svelteHTML.createElement("svelte:options", {
            "accessors": true,
        });
        }
    }
    void __svn_tpl_check;
    void a;
    return { props: undefined as any as ({ a: A; }), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({ a: A; }) };
}
$$render_491a605d;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_491a605d>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_491a605d>>['props'], Awaited<ReturnType<typeof $$render_491a605d>>['events'], Awaited<ReturnType<typeof $$render_491a605d>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_491a605d>>['bindings'] } & Awaited<ReturnType<typeof $$render_491a605d>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_491a605d>>['props']): Awaited<ReturnType<typeof $$render_491a605d>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_491a605d>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

