// === input.svelte ===
// generated by svelte-check-native; do not edit
async function $$render_9b14236f() {
    async function __svn_tpl_check() {
        // template type-check body (incremental)
        SomeComponent(__svn_any(), {attr: "text", attrtwo: "text"});
    }
    void __svn_tpl_check;
}
$$render_9b14236f;
declare function __svn_component_default(__anchor: any, props: any): any;
declare type __svn_component_default = any;
export default __svn_component_default;

