// === input.svelte ===
// generated by svelte-check-native; do not edit
    interface Dependency {
        a: number;
    }
    interface Props {
        [k: string]: Dependency;
    }
async function $$render_5da896c9() {

                          
                  
     

                     
                                
     

    let { foo }: Props = $props();
    ;(async () => {
        // template type-check body (incremental)
    });
    void foo;
    return { props: undefined as any as (Props), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_5da896c9;
const __svn_component_default: import('svelte').Component<
    Awaited<ReturnType<typeof $$render_5da896c9>>['props'],
    Awaited<ReturnType<typeof $$render_5da896c9>>['exports'],
    ''
> = null as any;
type __svn_component_default = ReturnType<typeof __svn_component_default>;
export default __svn_component_default;

