// === input.svelte ===
// generated by svelte-check-native; do not edit
    interface Dependency {
        a: number;
    }
    interface Props {
        [k: string]: Dependency;
    }
async function $$render_5da896c9() {

                          
                  
     

                     
                                
     

    let { foo }: Props = $props();
    async function __svn_tpl_check() {
        // template type-check body (incremental)
    }
    void __svn_tpl_check;
    void foo;
    return { props: undefined as any as (Props), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_5da896c9;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_5da896c9>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_5da896c9>>['props'], Awaited<ReturnType<typeof $$render_5da896c9>>['events'], Awaited<ReturnType<typeof $$render_5da896c9>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_5da896c9>>['bindings'] } & Awaited<ReturnType<typeof $$render_5da896c9>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_5da896c9>>['props']): Awaited<ReturnType<typeof $$render_5da896c9>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_5da896c9>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

