// === input.svelte ===
// generated by svelte-check-native; do not edit
function $$render_e40e2c10() {

    type Action<N, T> = (node: N, params?: T) => {
        destroy?: () => void
    }
    const intersection: Action<HTMLElement, { cb: (n: number) => void }> = () => ({})
    const items = ['a', 'b', 'c']
    let active = 0
    ;(async () => {
        // template type-check body (incremental)
        let __svn_action_attrs_0: any = {};
        void __svn_action_attrs_0;
        for (let item of __svn_each_items(items)) {
            let index = 1;
            (index);
            const label = `slide-${index}`;
                const __svn_action_0 = __svn_ensure_action(intersection(__svn_map_element_tag('div'), ({
            cb: (_n) => {
                active = index
                void label
            },
        })));
            { svelteHTML.createElement("div", __svn_union(__svn_action_0), {});                 void __svn_action_0;
                item;
            }
        }
    });
    return { props: undefined as any as (Record<string, never>), events: undefined as any as { [evt: string]: CustomEvent<any> }, slots: undefined as any as {}, bindings: undefined as any as string, exports: undefined as any as ({}) };
}
$$render_e40e2c10;
interface $$IsomorphicComponent {
    new (options: import('svelte').ComponentConstructorOptions<Awaited<ReturnType<typeof $$render_e40e2c10>>['props']>): import('svelte').SvelteComponent<Awaited<ReturnType<typeof $$render_e40e2c10>>['props'], Awaited<ReturnType<typeof $$render_e40e2c10>>['events'], Awaited<ReturnType<typeof $$render_e40e2c10>>['slots']> & { $$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'] } & Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'];
    (internal: unknown, props: Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] extends Record<string, never> ? { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] } : Awaited<ReturnType<typeof $$render_e40e2c10>>['props'] & { $$events?: Awaited<ReturnType<typeof $$render_e40e2c10>>['events']; $$slots?: Awaited<ReturnType<typeof $$render_e40e2c10>>['slots'] }): Awaited<ReturnType<typeof $$render_e40e2c10>>['exports'] & { $set?: any; $on?: any };
    z_$$bindings?: Awaited<ReturnType<typeof $$render_e40e2c10>>['bindings'];
}
const __svn_component_default: $$IsomorphicComponent = null as any;
type __svn_component_default = InstanceType<typeof __svn_component_default>;
export default __svn_component_default;

